import WebTypes

// MARK: - Typography
public let typographyFontSans: CSSFontFamily = "var(--typography-font-sans)"
public let typographyFontSansItalic: CSSFontFamily = "var(--typography-font-sans-italic)"
public let typographyFontSerif: CSSFontFamily = "var(--typography-font-serif)"
public let typographyFontSerifItalic: CSSFontFamily = "var(--typography-font-serif-italic)"
public let typographyFontMono: CSSFontFamily = "var(--typography-font-mono)"

// MARK: - Extreme Colors
public let extreme: CSSColor = "var(--extreme)"
public let extremeInverted: CSSColor = "var(--extreme-inverted)"


// MARK: - OKLCH Hue Angles (Apple HIG)
// Each hue's glyph/fill tokens are set to the absolute sRGB gamut peak in HueTokensCSS.
// Mode functions can override --glyph-{hue}/--fill-{hue} with srgbMaxChroma(l:h:).
public let hueRed: String = "var(--hue-red)"
public let hueOrange: String = "var(--hue-orange)"
public let hueYellow: String = "var(--hue-yellow)"
public let hueGreen: String = "var(--hue-green)"
public let hueMint: String = "var(--hue-mint)"
public let hueTeal: String = "var(--hue-teal)"
public let hueCyan: String = "var(--hue-cyan)"
public let hueBlue: String = "var(--hue-blue)"
public let hueIndigo: String = "var(--hue-indigo)"
public let huePurple: String = "var(--hue-purple)"
public let huePink: String = "var(--hue-pink)"
public let hueBrown: String = "var(--hue-brown)"
public let hueGray: String = "var(--hue-gray)"

// MARK: - Source: Hue Colors (glyph = foreground, fill = background)
// Pattern: {tier}{Hue} — e.g. glyphRed, fillIndigo (gray remains grayGlyph/grayFill to avoid collision)
public let glyphRed: CSSColor = "var(--glyph-red)"
public let fillRed: CSSColor = "var(--fill-red)"
public let glyphOrange: CSSColor = "var(--glyph-orange)"
public let fillOrange: CSSColor = "var(--fill-orange)"
public let glyphYellow: CSSColor = "var(--glyph-yellow)"
public let fillYellow: CSSColor = "var(--fill-yellow)"
public let glyphGreen: CSSColor = "var(--glyph-green)"
public let fillGreen: CSSColor = "var(--fill-green)"
public let glyphMint: CSSColor = "var(--glyph-mint)"
public let fillMint: CSSColor = "var(--fill-mint)"
public let glyphTeal: CSSColor = "var(--glyph-teal)"
public let fillTeal: CSSColor = "var(--fill-teal)"
public let glyphCyan: CSSColor = "var(--glyph-cyan)"
public let fillCyan: CSSColor = "var(--fill-cyan)"
public let glyphBlue: CSSColor = "var(--glyph-blue)"
public let fillBlue: CSSColor = "var(--fill-blue)"
public let glyphIndigo: CSSColor = "var(--glyph-indigo)"
public let fillIndigo: CSSColor = "var(--fill-indigo)"
public let glyphPurple: CSSColor = "var(--glyph-purple)"
public let fillPurple: CSSColor = "var(--fill-purple)"
public let glyphPink: CSSColor = "var(--glyph-pink)"
public let fillPink: CSSColor = "var(--fill-pink)"
public let glyphBrown: CSSColor = "var(--glyph-brown)"
public let fillBrown: CSSColor = "var(--fill-brown)"
public let grayGlyph: CSSColor = "var(--gray-glyph)"
public let grayFill: CSSColor = "var(--gray-fill)"

// MARK: - Source: Fill
public let fill: CSSColor = "var(--fill)"
public let fillAlpha: CSSColor = "var(--fill-alpha)"
public let fillSecondary: CSSColor = "var(--fill-secondary)"
public let fillTertiary: CSSColor = "var(--fill-tertiary)"
public let fillTertiaryAlpha: CSSColor = "var(--fill-tertiary-alpha)"
public let fillQuaternaryAlpha: CSSColor = "var(--fill-quaternary-alpha)"
public let fillGray: CSSColor = "var(--fill-gray)"
public let fillGrayAlpha: CSSColor = "var(--fill-gray-alpha)"
public let fillGrayHover: CSSColor = "var(--fill-gray-hover)"
public let fillGrayActive: CSSColor = "var(--fill-gray-active)"
public let fillGraySecondary: CSSColor = "var(--fill-gray-secondary)"
public let fillGraySecondaryAlpha: CSSColor = "var(--fill-gray-secondary-alpha)"
public let fillGrayTertiary: CSSColor = "var(--fill-gray-tertiary)"
public let fillGrayTertiaryAlpha: CSSColor = "var(--fill-gray-tertiary-alpha)"
public let fillGrayQuaternary: CSSColor = "var(--fill-gray-quaternary)"
public let fillGrayQuaternaryAlpha: CSSColor = "var(--fill-gray-quaternary-alpha)"

// MARK: - Source: Glyph
public let glyph: CSSColor = "var(--glyph)"
public let glyphFixed: CSSColor = "var(--glyph-fixed)"
public let glyphGray: CSSColor = "var(--glyph-gray)"
public let glyphGrayAlpha: CSSColor = "var(--glyph-gray-alpha)"
public let glyphGrayFixed: CSSColor = "var(--glyph-gray-fixed)"
public let glyphGraySecondary: CSSColor = "var(--glyph-gray-secondary)"
public let glyphGraySecondaryAlpha: CSSColor = "var(--glyph-gray-secondary-alpha)"
public let glyphGraySecondaryAlt: CSSColor = "var(--glyph-gray-secondary-alt)"
public let glyphGraySecondaryAltAlpha: CSSColor = "var(--glyph-gray-secondary-alt-alpha)"
public let glyphGrayTertiary: CSSColor = "var(--glyph-gray-tertiary)"
public let glyphGrayTertiaryAlpha: CSSColor = "var(--glyph-gray-tertiary-alpha)"

// MARK: - Source: Semantic Bridge (unified applied function)
public let borderNeutral: CSSColor = "var(--border-neutral)"
public let borderEmphasis: CSSColor = "var(--border-emphasis)"
public let borderInteractive: CSSColor = "var(--border-interactive)"
public let shadowAlpha: CSSColor = "var(--shadow-alpha)"
public let backdropLight: CSSColor = "var(--backdrop-light)"
public let backdropDark: CSSColor = "var(--backdrop-dark)"

// MARK: - Source: Background Layers (Dark Mode)
public let backgroundPrimary: CSSColor = "var(--background-primary)"
public let backgroundLayer1: CSSColor = "var(--background-layer1)"
public let backgroundLayer2: CSSColor = "var(--background-layer2)"
public let backdrop: CSSColor = "var(--backdrop)"
public let sidebar: CSSColor = "var(--sidebar)"
public let separator: CSSColor = "var(--separator)"

// MARK: - Applied: Text/Foreground
public let colorBase: CSSColor = "var(--color-base)"
public let colorBaseFixed: CSSColor = "var(--color-base-fixed)"
public let colorBaseHover: CSSColor = "var(--color-base-hover)"
public let colorEmphasized: CSSColor = "var(--color-emphasized)"
public let colorSubtle: CSSColor = "var(--color-subtle)"
public let colorPlaceholder: CSSColor = "var(--color-placeholder)"
public let colorDisabled: CSSColor = "var(--color-disabled)"
public let colorDisabledEmphasized: CSSColor = "var(--color-disabled-emphasized)"
public let colorInverted: CSSColor = "var(--color-inverted)"
public let colorInvertedFixed: CSSColor = "var(--color-inverted-fixed)"

// MARK: - Applied: Content Diff
public let colorContentAdded: CSSColor = "var(--color-content-added)"
public let colorContentRemoved: CSSColor = "var(--color-content-removed)"

// MARK: - Applied: HIG Component Colors (Foreground)
// Hue order: red, orange, yellow, green, mint, teal, cyan, blue, indigo, purple, pink, brown, gray
public let colorRed: CSSColor = "var(--color-red)"
public let colorRedHover: CSSColor = "var(--color-red-hover)"
public let colorRedActive: CSSColor = "var(--color-red-active)"
public let colorRedFocus: CSSColor = "var(--color-red-focus)"
public let colorOrange: CSSColor = "var(--color-orange)"
public let colorOrangeHover: CSSColor = "var(--color-orange-hover)"
public let colorOrangeActive: CSSColor = "var(--color-orange-active)"
public let colorOrangeFocus: CSSColor = "var(--color-orange-focus)"
public let colorYellow: CSSColor = "var(--color-yellow)"
public let colorYellowHover: CSSColor = "var(--color-yellow-hover)"
public let colorYellowActive: CSSColor = "var(--color-yellow-active)"
public let colorYellowFocus: CSSColor = "var(--color-yellow-focus)"
public let colorGreen: CSSColor = "var(--color-green)"
public let colorGreenHover: CSSColor = "var(--color-green-hover)"
public let colorGreenActive: CSSColor = "var(--color-green-active)"
public let colorGreenFocus: CSSColor = "var(--color-green-focus)"
public let colorMint: CSSColor = "var(--color-mint)"
public let colorMintHover: CSSColor = "var(--color-mint-hover)"
public let colorMintActive: CSSColor = "var(--color-mint-active)"
public let colorMintFocus: CSSColor = "var(--color-mint-focus)"
public let colorTeal: CSSColor = "var(--color-teal)"
public let colorTealHover: CSSColor = "var(--color-teal-hover)"
public let colorTealActive: CSSColor = "var(--color-teal-active)"
public let colorTealFocus: CSSColor = "var(--color-teal-focus)"
public let colorCyan: CSSColor = "var(--color-cyan)"
public let colorCyanHover: CSSColor = "var(--color-cyan-hover)"
public let colorCyanActive: CSSColor = "var(--color-cyan-active)"
public let colorCyanFocus: CSSColor = "var(--color-cyan-focus)"
public let colorBlue: CSSColor = "var(--color-blue)"
public let colorBlueHover: CSSColor = "var(--color-blue-hover)"
public let colorBlueActive: CSSColor = "var(--color-blue-active)"
public let colorBlueFocus: CSSColor = "var(--color-blue-focus)"
public let colorIndigo: CSSColor = "var(--color-indigo)"
public let colorIndigoHover: CSSColor = "var(--color-indigo-hover)"
public let colorIndigoActive: CSSColor = "var(--color-indigo-active)"
public let colorIndigoFocus: CSSColor = "var(--color-indigo-focus)"
public let colorPurple: CSSColor = "var(--color-purple)"
public let colorPurpleHover: CSSColor = "var(--color-purple-hover)"
public let colorPurpleActive: CSSColor = "var(--color-purple-active)"
public let colorPurpleFocus: CSSColor = "var(--color-purple-focus)"
public let colorPink: CSSColor = "var(--color-pink)"
public let colorPinkHover: CSSColor = "var(--color-pink-hover)"
public let colorPinkActive: CSSColor = "var(--color-pink-active)"
public let colorPinkFocus: CSSColor = "var(--color-pink-focus)"
public let colorBrown: CSSColor = "var(--color-brown)"
public let colorBrownHover: CSSColor = "var(--color-brown-hover)"
public let colorBrownActive: CSSColor = "var(--color-brown-active)"
public let colorBrownFocus: CSSColor = "var(--color-brown-focus)"
public let colorGray: CSSColor = "var(--color-gray)"
public let colorGrayHover: CSSColor = "var(--color-gray-hover)"
public let colorGrayActive: CSSColor = "var(--color-gray-active)"
public let colorGrayFocus: CSSColor = "var(--color-gray-focus)"

// MARK: - Applied: Opacity
public let opacityBase: CSSNumber = "var(--opacity-base)"
public let opacityMedium: CSSNumber = "var(--opacity-medium)"
public let opacityLow: CSSNumber = "var(--opacity-low)"
public let opacityTransparent: CSSNumber = "var(--opacity-transparent)"
public let filterInvertIcon: CSSNumber = "var(--filter-invert-icon)"
public let filterInvertPrimaryButtonIcon: CSSNumber = "var(--filter-invert-primary-button-icon)"

// MARK: - Applied: Layout
public let backgroundPositionBase: CSSBackgroundPosition = "var(--background-position-base)"
public let backgroundSizeSearchFigure: CSSBackgroundSize = "var(--background-size-search-figure)"
public let zIndexBottom: CSSNumber = "var(--z-index-bottom)"
public let zIndexBase: CSSNumber = "var(--z-index-base)"
public let zIndexAboveContent: CSSNumber = "var(--z-index-above-content)"
public let zIndexToolbar: CSSNumber = "var(--z-index-toolbar)"
public let zIndexDropdown: CSSNumber = "var(--z-index-dropdown)"
public let zIndexSticky: CSSNumber = "var(--z-index-sticky)"
public let zIndexFixed: CSSNumber = "var(--z-index-fixed)"
public let zIndexOffCanvasBackdrop: CSSNumber = "var(--z-index-off-canvas-backdrop)"
public let zIndexOffCanvas: CSSNumber = "var(--z-index-off-canvas)"
public let zIndexOverlayBackdrop: CSSNumber = "var(--z-index-overlay-backdrop)"
public let zIndexOverlay: CSSNumber = "var(--z-index-overlay)"
public let zIndexPopover: CSSNumber = "var(--z-index-popover)"
public let zIndexTooltip: CSSNumber = "var(--z-index-tooltip)"
public let zIndexToastNotification: CSSNumber = "var(--z-index-toast-notification)"
public let zIndexTop: CSSNumber = "var(--z-index-top)"
public let zIndexStacking0: CSSNumber = "var(--z-index-stacking-0)"
public let zIndexStacking1: CSSNumber = "var(--z-index-stacking-1)"
public let zIndexStacking2: CSSNumber = "var(--z-index-stacking-2)"
public let zIndexStacking3: CSSNumber = "var(--z-index-stacking-3)"
public let boxSizingBase: CSSBoxSizing = "var(--box-sizing-base)"

// MARK: - Applied: Sizing
public let size0: Length = "var(--size-0)"
public let size1: Length = "var(--size-1)"
public let size2: Length = "var(--size-2)"
public let size4: Length = "var(--size-4)"
public let size8: Length = "var(--size-8)"
public let size12: Length = "var(--size-12)"
public let size16: Length = "var(--size-16)"
public let size20: Length = "var(--size-20)"
public let size24: Length = "var(--size-24)"
public let size32: Length = "var(--size-32)"
public let size40: Length = "var(--size-40)"
public let size44: Length = "var(--size-44)"
public let size48: Length = "var(--size-48)"
public let size64: Length = "var(--size-64)"
public let size128: Length = "var(--size-128)"
public let size192: Length = "var(--size-192)"
public let size256: Length = "var(--size-256)"
public let size384: Length = "var(--size-384)"
public let size448: Length = "var(--size-448)"
public let size512: Length = "var(--size-512)"
public let size640: Length = "var(--size-640)"
public let size896: Length = "var(--size-896)"
public let sizeViewportWidthFull: Length = "var(--size-viewport-width-full)"
public let sizeViewportHeightFull: Length = "var(--size-viewport-height-full)"
public let sizeAbsolute1: Length = "var(--size-absolute-1)"
public let sizeAbsolute9999: Length = "var(--size-absolute-9999)"
public let sizeContentMin: Length = "var(--size-content-min)"
public let sizeContentFit: Length = "var(--size-content-fit)"
public let sizeContentMax: Length = "var(--size-content-max)"
public let sizeThird: Percentage = "var(--size-third)"
public let sizeHalf: Percentage = "var(--size-half)"
public let sizeFull: Percentage = "var(--size-full)"
public let sizeDouble: Percentage = "var(--size-double)"
public let sizeSearchFigure: Length = "var(--size-search-figure)"
public let maxWidthBase: Length = "var(--max-width-base)"
// Breakpoints use raw px() values, not CSSProtocol variables — media queries don't support var()
public let maxWidthBreakpointPhoneNarrow: Length = px(479) // NEW
public let maxWidthBreakpointMobile: Length = px(768)
public let maxWidthBreakpointTablet: Length = px(1024)
public let maxWidthBreakpointDesktop: Length = px(1279)
public let maxWidthButton: Length = "var(--max-width-button)"

// MARK: - Applied: Borders & Shadows
public let borderStyleBase: CSSBorder.LineStyle = "var(--border-style-base)"
public let borderStyleDashed: CSSBorder.LineStyle = "var(--border-style-dashed)"
public let boxShadowInsetSmall: CSSSpreadShadow = "var(--box-shadow-inset-small)"
public let boxShadowInsetMedium: CSSSpreadShadow = "var(--box-shadow-inset-medium)"
public let boxShadowInsetMediumVertical: CSSSpreadShadow = "var(--box-shadow-inset-medium-vertical)"
public let boxShadowOutsetSmall: CSSSpreadShadow = "var(--box-shadow-outset-small)"
public let boxShadowOutsetSmallTop: CSSSpreadShadow = "var(--box-shadow-outset-small-top)"
public let boxShadowOutsetSmallBottom: CSSSpreadShadow = "var(--box-shadow-outset-small-bottom)"
public let boxShadowOutsetSmallStart: CSSSpreadShadow = "var(--box-shadow-outset-small-start)"
public let boxShadowOutsetMediumBelow: CSSSpreadShadow = "var(--box-shadow-outset-medium-below)"
public let boxShadowOutsetMediumAround: CSSSpreadShadow = "var(--box-shadow-outset-medium-around)"
public let boxShadowOutsetLargeBelow: CSSSpreadShadow = "var(--box-shadow-outset-large-below)"
public let boxShadowOutsetLargeAround: CSSSpreadShadow = "var(--box-shadow-outset-large-around)"
public let boxShadowColorBase: CSSColor = "var(--box-shadow-color-base)"
public let boxShadowColorInverted: CSSColor = "var(--box-shadow-color-inverted)"
public let boxShadowColorAlphaBase: CSSColor = "var(--box-shadow-color-alpha-base)"
public let boxShadowColorTransparent: CSSColor = "var(--box-shadow-color-transparent)"

// MARK: - Applied: Typography
public let fontFamilyBase: CSSFontFamily = "var(--font-family-base)"
public let fontFamilySystemSans: CSSFontFamily = "var(--font-family-system-sans)"
public let fontFamilySansFallback: CSSFontFamily = "var(--font-family-sans--fallback)"
public let fontFamilySerif: CSSFontFamily = "var(--font-family-serif)"
public let fontFamilySerifFallback: CSSFontFamily = "var(--font-family-serif--fallback)"
public let fontFamilyMonospace: CSSFontFamily = "var(--font-family-monospace)"
public let fontFamilyMonospaceFallback: CSSFontFamily = "var(--font-family-monospace--fallback)"
public let fontFamilyHeadingMain: CSSFontFamily = "var(--font-family-heading-main)"
public let fontSizeXSmall12: Length = "var(--font-size-x-small-12)"
public let fontSizeSmall14: Length = "var(--font-size-small-14)"
public let fontSizeMedium16: Length = "var(--font-size-medium-16)"
public let fontSizeLarge18: Length = "var(--font-size-large-18)"
public let fontSizeXLarge20: Length = "var(--font-size-x-large-20)"
public let fontSizeXXLarge24: Length = "var(--font-size-xx-large-24)"
public let fontSizeXXXLarge28: Length = "var(--font-size-xxx-large-28)"
public let fontWeightHairline: CSSFontWeight = "var(--font-weight-hairline)"
public let fontWeightLight: CSSFontWeight = "var(--font-weight-light)"
public let fontWeightNormal: CSSFontWeight = "var(--font-weight-normal)"
public let fontWeightSemiBold: CSSFontWeight = "var(--font-weight-semi-bold)"
public let fontWeightBold: CSSFontWeight = "var(--font-weight-bold)"
public let lineHeightXSmall20: Length = "var(--line-height-x-small-20)"
public let lineHeightSmall22: Length = "var(--line-height-small-22)"
public let lineHeightMedium26: Length = "var(--line-height-medium-26)"
public let lineHeightLarge28: Length = "var(--line-height-large-28)"
public let lineHeightXLarge30: Length = "var(--line-height-x-large-30)"
public let lineHeightXXLarge34: Length = "var(--line-height-xx-large-34)"
public let lineHeightXXXLarge38: Length = "var(--line-height-xxx-large-38)"
public let lineHeightContent: Length = "var(--line-height-content)"
public let textDecorationNone: CSSTextDecoration = "var(--text-decoration-none)"
public let textDecorationLineThrough: CSSTextDecoration = "var(--text-decoration-line-through)"
public let textDecorationUnderline: CSSTextDecoration = "var(--text-decoration-underline)"
public let textOverflowClip: CSSTextOverflow = "var(--text-overflow-clip)"
public let textOverflowEllipsis: CSSTextOverflow = "var(--text-overflow-ellipsis)"
public let tabSizeBase: CSSNumber = "var(--tab-size-base)"

// MARK: - Applied: Transforms & Transitions
public let transformCheckboxTickChecked: CSSTransformFunction = "var(--transform-checkbox-tick-checked)"
public let transformProgressIndicatorSpinnerStart: CSSTransformFunction = "var(--transform-progress-indicator-spinner-start)"
public let transformProgressIndicatorSpinnerEnd: CSSTransformFunction = "var(--transform-progress-indicator-spinner-end)"
public let transitionDurationBase: CSSTime = "var(--transition-duration-base)"
public let transitionDurationMedium: CSSTime = "var(--transition-duration-medium)"
public let transitionPropertyBase: CSSSingleTransitionProperty = "var(--transition-property-base)"
public let transitionPropertyFade: CSSSingleTransitionProperty = "var(--transition-property-fade)"
public let transitionPropertyIcon: CSSSingleTransitionProperty = "var(--transition-property-icon)"
public let transitionPropertyIconCssOnly: CSSSingleTransitionProperty = "var(--transition-property-icon-css-only)"
public let transitionPropertyToggleSwitchGrip: CSSSingleTransitionProperty = "var(--transition-property-toggle-switch-grip)"
public let transitionTimingFunctionSystem: CSSEasingFunction = "var(--transition-timing-function-system)"
public let transitionTimingFunctionUser: CSSEasingFunction = "var(--transition-timing-function-user)"

// MARK: - Applied: Animations
public let animationDelayNone: CSSTime = "var(--animation-delay-none)"
public let animationDelayMedium: CSSTime = "var(--animation-delay-medium)"
public let animationDelaySlow: CSSTime = "var(--animation-delay-slow)"
public let animationDurationFast: CSSTime = "var(--animation-duration-fast)"
public let animationDurationMedium: CSSTime = "var(--animation-duration-medium)"
public let animationDurationSlow: CSSTime = "var(--animation-duration-slow)"
public let animationTimingFunctionBase: CSSEasingFunction = "var(--animation-timing-function-base)"
public let animationTimingFunctionBouncing: CSSEasingFunction = "var(--animation-timing-function-bouncing)"
public let animationIterationCountBase: CSSNumber = "var(--animation-iteration-count-base)"

// MARK: - Applied: Cursors & Blend Modes
public let cursorBase: CSSCursor = "var(--cursor-base)"
public let cursorBaseDisabled: CSSCursor = "var(--cursor-base-disabled)"
public let cursorBaseHover: CSSCursor = "var(--cursor-base-hover)"
public let cursorGrab: CSSCursor = "var(--cursor-grab)"
public let cursorGrabbing: CSSCursor = "var(--cursor-grabbing)"
public let cursorHelp: CSSCursor = "var(--cursor-help)"
public let cursorMove: CSSCursor = "var(--cursor-move)"
public let cursorNotAllowed: CSSCursor = "var(--cursor-not-allowed)"
public let cursorResizeNesw: CSSCursor = "var(--cursor-resize-nesw)"
public let cursorResizeNwse: CSSCursor = "var(--cursor-resize-nwse)"
public let cursorText: CSSCursor = "var(--cursor-text)"
public let cursorZoomIn: CSSCursor = "var(--cursor-zoom-in)"
public let cursorZoomOut: CSSCursor = "var(--cursor-zoom-out)"
public let mixBlendModeBase: CSSBlendMode = "var(--mix-blend-mode-base)"
public let mixBlendModeBlend: CSSBlendMode = "var(--mix-blend-mode-blend)"

// MARK: - Applied: Background Colors
public let backgroundColorBase: CSSColor = "var(--background-color-base)"
public let backgroundColorBaseFixed: CSSColor = "var(--background-color-base-fixed)"
public let backgroundColorNeutral: CSSColor = "var(--background-color-neutral)"
public let backgroundColorNeutralSubtle: CSSColor = "var(--background-color-neutral-subtle)"
public let backgroundColorInteractive: CSSColor = "var(--background-color-interactive)"
public let backgroundColorInteractiveHover: CSSColor = "var(--background-color-interactive-hover)"
public let backgroundColorInteractiveActive: CSSColor = "var(--background-color-interactive-active)"
public let backgroundColorInteractiveSubtle: CSSColor = "var(--background-color-interactive-subtle)"
public let backgroundColorInteractiveSubtleHover: CSSColor = "var(--background-color-interactive-subtle-hover)"
public let backgroundColorInteractiveSubtleActive: CSSColor = "var(--background-color-interactive-subtle-active)"
public let backgroundColorDisabled: CSSColor = "var(--background-color-disabled)"
public let backgroundColorDisabledSubtle: CSSColor = "var(--background-color-disabled-subtle)"
public let backgroundColorInverted: CSSColor = "var(--background-color-inverted)"
public let backgroundColorContentAdded: CSSColor = "var(--background-color-content-added)"
public let backgroundColorContentRemoved: CSSColor = "var(--background-color-content-removed)"
public let backgroundColorTransparent: CSSColor = "var(--background-color-transparent)"
public let backgroundColorBackdropLight: CSSColor = "var(--background-color-backdrop-light)"
public let backgroundColorBackdropDark: CSSColor = "var(--background-color-backdrop-dark)"
public let backgroundColorButtonQuietHover: CSSColor = "var(--background-color-button-quiet-hover)"
public let backgroundColorButtonQuietActive: CSSColor = "var(--background-color-button-quiet-active)"
public let backgroundColorInputBinaryChecked: CSSColor = "var(--background-color-input-binary-checked)"
public let backgroundColorTabListItemFramedHover: CSSColor = "var(--background-color-tab-list-item-framed-hover)"
public let backgroundColorTabListItemFramedActive: CSSColor = "var(--background-color-tab-list-item-framed-active)"

// MARK: - Applied: HIG Background Colors
// Red
public let backgroundColorRed: CSSColor = "var(--background-color-red)"
public let backgroundColorRedHover: CSSColor = "var(--background-color-red-hover)"
public let backgroundColorRedActive: CSSColor = "var(--background-color-red-active)"
public let backgroundColorRedFocus: CSSColor = "var(--background-color-red-focus)"
public let backgroundColorRedSubtle: CSSColor = "var(--background-color-red-subtle)"
public let backgroundColorRedSubtleHover: CSSColor = "var(--background-color-red-subtle-hover)"
public let backgroundColorRedSubtleActive: CSSColor = "var(--background-color-red-subtle-active)"
// Orange
public let backgroundColorOrange: CSSColor = "var(--background-color-orange)"
public let backgroundColorOrangeHover: CSSColor = "var(--background-color-orange-hover)"
public let backgroundColorOrangeActive: CSSColor = "var(--background-color-orange-active)"
public let backgroundColorOrangeFocus: CSSColor = "var(--background-color-orange-focus)"
public let backgroundColorOrangeSubtle: CSSColor = "var(--background-color-orange-subtle)"
public let backgroundColorOrangeSubtleHover: CSSColor = "var(--background-color-orange-subtle-hover)"
public let backgroundColorOrangeSubtleActive: CSSColor = "var(--background-color-orange-subtle-active)"
// Yellow
public let backgroundColorYellow: CSSColor = "var(--background-color-yellow)"
public let backgroundColorYellowHover: CSSColor = "var(--background-color-yellow-hover)"
public let backgroundColorYellowActive: CSSColor = "var(--background-color-yellow-active)"
public let backgroundColorYellowFocus: CSSColor = "var(--background-color-yellow-focus)"
public let backgroundColorYellowSubtle: CSSColor = "var(--background-color-yellow-subtle)"
public let backgroundColorYellowSubtleHover: CSSColor = "var(--background-color-yellow-subtle-hover)"
public let backgroundColorYellowSubtleActive: CSSColor = "var(--background-color-yellow-subtle-active)"
// Green
public let backgroundColorGreen: CSSColor = "var(--background-color-green)"
public let backgroundColorGreenHover: CSSColor = "var(--background-color-green-hover)"
public let backgroundColorGreenActive: CSSColor = "var(--background-color-green-active)"
public let backgroundColorGreenFocus: CSSColor = "var(--background-color-green-focus)"
public let backgroundColorGreenSubtle: CSSColor = "var(--background-color-green-subtle)"
public let backgroundColorGreenSubtleHover: CSSColor = "var(--background-color-green-subtle-hover)"
public let backgroundColorGreenSubtleActive: CSSColor = "var(--background-color-green-subtle-active)"
// Mint
public let backgroundColorMint: CSSColor = "var(--background-color-mint)"
public let backgroundColorMintHover: CSSColor = "var(--background-color-mint-hover)"
public let backgroundColorMintActive: CSSColor = "var(--background-color-mint-active)"
public let backgroundColorMintFocus: CSSColor = "var(--background-color-mint-focus)"
public let backgroundColorMintSubtle: CSSColor = "var(--background-color-mint-subtle)"
public let backgroundColorMintSubtleHover: CSSColor = "var(--background-color-mint-subtle-hover)"
public let backgroundColorMintSubtleActive: CSSColor = "var(--background-color-mint-subtle-active)"
// Teal
public let backgroundColorTeal: CSSColor = "var(--background-color-teal)"
public let backgroundColorTealHover: CSSColor = "var(--background-color-teal-hover)"
public let backgroundColorTealActive: CSSColor = "var(--background-color-teal-active)"
public let backgroundColorTealFocus: CSSColor = "var(--background-color-teal-focus)"
public let backgroundColorTealSubtle: CSSColor = "var(--background-color-teal-subtle)"
public let backgroundColorTealSubtleHover: CSSColor = "var(--background-color-teal-subtle-hover)"
public let backgroundColorTealSubtleActive: CSSColor = "var(--background-color-teal-subtle-active)"
// Cyan
public let backgroundColorCyan: CSSColor = "var(--background-color-cyan)"
public let backgroundColorCyanHover: CSSColor = "var(--background-color-cyan-hover)"
public let backgroundColorCyanActive: CSSColor = "var(--background-color-cyan-active)"
public let backgroundColorCyanFocus: CSSColor = "var(--background-color-cyan-focus)"
public let backgroundColorCyanSubtle: CSSColor = "var(--background-color-cyan-subtle)"
public let backgroundColorCyanSubtleHover: CSSColor = "var(--background-color-cyan-subtle-hover)"
public let backgroundColorCyanSubtleActive: CSSColor = "var(--background-color-cyan-subtle-active)"
// Blue
public let backgroundColorBlue: CSSColor = "var(--background-color-blue)"
public let backgroundColorBlueHover: CSSColor = "var(--background-color-blue-hover)"
public let backgroundColorBlueActive: CSSColor = "var(--background-color-blue-active)"
public let backgroundColorBlueFocus: CSSColor = "var(--background-color-blue-focus)"
public let backgroundColorBlueSubtle: CSSColor = "var(--background-color-blue-subtle)"
public let backgroundColorBlueSubtleHover: CSSColor = "var(--background-color-blue-subtle-hover)"
public let backgroundColorBlueSubtleActive: CSSColor = "var(--background-color-blue-subtle-active)"
// Indigo
public let backgroundColorIndigo: CSSColor = "var(--background-color-indigo)"
public let backgroundColorIndigoHover: CSSColor = "var(--background-color-indigo-hover)"
public let backgroundColorIndigoActive: CSSColor = "var(--background-color-indigo-active)"
public let backgroundColorIndigoFocus: CSSColor = "var(--background-color-indigo-focus)"
public let backgroundColorIndigoSubtle: CSSColor = "var(--background-color-indigo-subtle)"
public let backgroundColorIndigoSubtleHover: CSSColor = "var(--background-color-indigo-subtle-hover)"
public let backgroundColorIndigoSubtleActive: CSSColor = "var(--background-color-indigo-subtle-active)"
// Purple
public let backgroundColorPurple: CSSColor = "var(--background-color-purple)"
public let backgroundColorPurpleHover: CSSColor = "var(--background-color-purple-hover)"
public let backgroundColorPurpleActive: CSSColor = "var(--background-color-purple-active)"
public let backgroundColorPurpleFocus: CSSColor = "var(--background-color-purple-focus)"
public let backgroundColorPurpleSubtle: CSSColor = "var(--background-color-purple-subtle)"
public let backgroundColorPurpleSubtleHover: CSSColor = "var(--background-color-purple-subtle-hover)"
public let backgroundColorPurpleSubtleActive: CSSColor = "var(--background-color-purple-subtle-active)"
// Pink
public let backgroundColorPink: CSSColor = "var(--background-color-pink)"
public let backgroundColorPinkHover: CSSColor = "var(--background-color-pink-hover)"
public let backgroundColorPinkActive: CSSColor = "var(--background-color-pink-active)"
public let backgroundColorPinkFocus: CSSColor = "var(--background-color-pink-focus)"
public let backgroundColorPinkSubtle: CSSColor = "var(--background-color-pink-subtle)"
public let backgroundColorPinkSubtleHover: CSSColor = "var(--background-color-pink-subtle-hover)"
public let backgroundColorPinkSubtleActive: CSSColor = "var(--background-color-pink-subtle-active)"
// Brown
public let backgroundColorBrown: CSSColor = "var(--background-color-brown)"
public let backgroundColorBrownHover: CSSColor = "var(--background-color-brown-hover)"
public let backgroundColorBrownActive: CSSColor = "var(--background-color-brown-active)"
public let backgroundColorBrownFocus: CSSColor = "var(--background-color-brown-focus)"
public let backgroundColorBrownSubtle: CSSColor = "var(--background-color-brown-subtle)"
public let backgroundColorBrownSubtleHover: CSSColor = "var(--background-color-brown-subtle-hover)"
public let backgroundColorBrownSubtleActive: CSSColor = "var(--background-color-brown-subtle-active)"
// Gray
public let backgroundColorGray: CSSColor = "var(--background-color-gray)"
public let backgroundColorGrayHover: CSSColor = "var(--background-color-gray-hover)"
public let backgroundColorGrayActive: CSSColor = "var(--background-color-gray-active)"
public let backgroundColorGrayFocus: CSSColor = "var(--background-color-gray-focus)"
public let backgroundColorGraySubtle: CSSColor = "var(--background-color-gray-subtle)"
public let backgroundColorGraySubtleHover: CSSColor = "var(--background-color-gray-subtle-hover)"
public let backgroundColorGraySubtleActive: CSSColor = "var(--background-color-gray-subtle-active)"
// MARK: - Applied: Icon Opacity
public let opacityIconBase: CSSNumber = "var(--opacity-icon-base)"
public let opacityIconBaseHover: CSSNumber = "var(--opacity-icon-base-hover)"
public let opacityIconBaseSelected: CSSNumber = "var(--opacity-icon-base-selected)"
public let opacityIconBaseDisabled: CSSNumber = "var(--opacity-icon-base-disabled)"
public let opacityIconPlaceholder: CSSNumber = "var(--opacity-icon-placeholder)"
public let opacityIconSubtle: CSSNumber = "var(--opacity-icon-subtle)"

// MARK: - Applied: Min Sizes
public let minSizeInteractivePointer: Length = "var(--min-size-interactive-pointer)"
public let minSizeInteractiveTouch: Length = "var(--min-size-interactive-touch)"
public let minSizeSearchFigure: Length = "var(--min-size-search-figure)"
public let minSizeIconXSmall: Length = "var(--min-size-icon-x-small)"
public let minSizeIconSmall: Length = "var(--min-size-icon-small)"
public let minSizeIconMedium: Length = "var(--min-size-icon-medium)"
public let minSizeInputBinary: Length = "var(--min-size-input-binary)"
public let minSizeInputChipClearButton: Length = "var(--min-size-input-chip-clear-button)"
public let minSizeToggleSwitchGrip: Length = "var(--min-size-toggle-switch-grip)"
public let minWidthMedium: Length = "var(--min-width-medium)"
// Breakpoints use raw px() values, not CSSProtocol variables — media queries don't support var()
public let minWidthBreakpointMobile: Length = px(480)
public let minWidthBreakpointTablet: Length = px(769)
public let minWidthBreakpointDesktop: Length = px(1025)
public let minWidthBreakpointDesktopWide: Length = px(1280)
public let minWidthToggleSwitch: Length = "var(--min-width-toggle-switch)"

// MARK: - Applied: Spacing
public let spacing0: Length = "var(--spacing-0)"
public let spacing1: Length = "var(--spacing-1)"
public let spacing2: Length = "var(--spacing-2)"
public let spacing4: Length = "var(--spacing-4)"
public let spacing5: Length = "var(--spacing-5)"
public let spacing6: Length = "var(--spacing-6)"
public let spacing8: Length = "var(--spacing-8)"
public let spacing10: Length = "var(--spacing-10)"
public let spacing12: Length = "var(--spacing-12)"
public let spacing16: Length = "var(--spacing-16)"
public let spacing20: Length = "var(--spacing-20)"
public let spacing24: Length = "var(--spacing-24)"
public let spacing32: Length = "var(--spacing-32)"
public let spacing40: Length = "var(--spacing-40)"
public let spacing48: Length = "var(--spacing-48)"
public let spacing64: Length = "var(--spacing-64)"
public let spacingHalf: Percentage = "var(--spacing-half)"
public let spacingFull: Percentage = "var(--spacing-full)"

// MARK: - Applied: Border Width & Color
public let borderWidthBase: Length = "var(--border-width-base)"
public let borderWidthThick: Length = "var(--border-width-thick)"
public let borderWidthInputRadioChecked: Length = "var(--border-width-input-radio-checked)"
public let borderColorBase: CSSColor = "var(--border-color-base)"
public let borderColorEmphasized: CSSColor = "var(--border-color-emphasized)"
public let borderColorSubtle: CSSColor = "var(--border-color-subtle)"
public let borderColorMuted: CSSColor = "var(--border-color-muted)"
public let borderColorInteractive: CSSColor = "var(--border-color-interactive)"
public let borderColorInteractiveHover: CSSColor = "var(--border-color-interactive-hover)"
public let borderColorInteractiveActive: CSSColor = "var(--border-color-interactive-active)"
public let borderColorDisabled: CSSColor = "var(--border-color-disabled)"
public let borderColorInverted: CSSColor = "var(--border-color-inverted)"
public let borderColorInvertedFixed: CSSColor = "var(--border-color-inverted-fixed)"
public let borderColorContentAdded: CSSColor = "var(--border-color-content-added)"
public let borderColorContentRemoved: CSSColor = "var(--border-color-content-removed)"
public let borderColorTransparent: CSSColor = "var(--border-color-transparent)"
public let borderColorDivider: CSSColor = "var(--border-color-divider)"

// MARK: - Applied: HIG Border Colors
// Hue order: red, orange, yellow, green, mint, teal, cyan, blue, indigo, purple, pink, brown, gray
public let borderColorRed: CSSColor = "var(--border-color-red)"
public let borderColorRedHover: CSSColor = "var(--border-color-red-hover)"
public let borderColorRedActive: CSSColor = "var(--border-color-red-active)"
public let borderColorRedFocus: CSSColor = "var(--border-color-red-focus)"
public let borderColorOrange: CSSColor = "var(--border-color-orange)"
public let borderColorOrangeHover: CSSColor = "var(--border-color-orange-hover)"
public let borderColorOrangeActive: CSSColor = "var(--border-color-orange-active)"
public let borderColorOrangeFocus: CSSColor = "var(--border-color-orange-focus)"
public let borderColorYellow: CSSColor = "var(--border-color-yellow)"
public let borderColorYellowHover: CSSColor = "var(--border-color-yellow-hover)"
public let borderColorYellowActive: CSSColor = "var(--border-color-yellow-active)"
public let borderColorYellowFocus: CSSColor = "var(--border-color-yellow-focus)"
public let borderColorGreen: CSSColor = "var(--border-color-green)"
public let borderColorGreenHover: CSSColor = "var(--border-color-green-hover)"
public let borderColorGreenActive: CSSColor = "var(--border-color-green-active)"
public let borderColorGreenFocus: CSSColor = "var(--border-color-green-focus)"
public let borderColorMint: CSSColor = "var(--border-color-mint)"
public let borderColorMintHover: CSSColor = "var(--border-color-mint-hover)"
public let borderColorMintActive: CSSColor = "var(--border-color-mint-active)"
public let borderColorMintFocus: CSSColor = "var(--border-color-mint-focus)"
public let borderColorTeal: CSSColor = "var(--border-color-teal)"
public let borderColorTealHover: CSSColor = "var(--border-color-teal-hover)"
public let borderColorTealActive: CSSColor = "var(--border-color-teal-active)"
public let borderColorTealFocus: CSSColor = "var(--border-color-teal-focus)"
public let borderColorCyan: CSSColor = "var(--border-color-cyan)"
public let borderColorCyanHover: CSSColor = "var(--border-color-cyan-hover)"
public let borderColorCyanActive: CSSColor = "var(--border-color-cyan-active)"
public let borderColorCyanFocus: CSSColor = "var(--border-color-cyan-focus)"
public let borderColorBlue: CSSColor = "var(--border-color-blue)"
public let borderColorBlueHover: CSSColor = "var(--border-color-blue-hover)"
public let borderColorBlueActive: CSSColor = "var(--border-color-blue-active)"
public let borderColorBlueFocus: CSSColor = "var(--border-color-blue-focus)"
public let borderColorIndigo: CSSColor = "var(--border-color-indigo)"
public let borderColorIndigoHover: CSSColor = "var(--border-color-indigo-hover)"
public let borderColorIndigoActive: CSSColor = "var(--border-color-indigo-active)"
public let borderColorIndigoFocus: CSSColor = "var(--border-color-indigo-focus)"
public let borderColorPurple: CSSColor = "var(--border-color-purple)"
public let borderColorPurpleHover: CSSColor = "var(--border-color-purple-hover)"
public let borderColorPurpleActive: CSSColor = "var(--border-color-purple-active)"
public let borderColorPurpleFocus: CSSColor = "var(--border-color-purple-focus)"
public let borderColorPink: CSSColor = "var(--border-color-pink)"
public let borderColorPinkHover: CSSColor = "var(--border-color-pink-hover)"
public let borderColorPinkActive: CSSColor = "var(--border-color-pink-active)"
public let borderColorPinkFocus: CSSColor = "var(--border-color-pink-focus)"
public let borderColorBrown: CSSColor = "var(--border-color-brown)"
public let borderColorBrownHover: CSSColor = "var(--border-color-brown-hover)"
public let borderColorBrownActive: CSSColor = "var(--border-color-brown-active)"
public let borderColorBrownFocus: CSSColor = "var(--border-color-brown-focus)"
public let borderColorGray: CSSColor = "var(--border-color-gray)"
public let borderColorGrayHover: CSSColor = "var(--border-color-gray-hover)"
public let borderColorGrayActive: CSSColor = "var(--border-color-gray-active)"
public let borderColorGrayFocus: CSSColor = "var(--border-color-gray-focus)"
// MARK: - Applied: Border Radius
public let borderRadiusMinimal: Length = "var(--border-radius-minimal)"
public let borderRadiusBase: Length = "var(--border-radius-base)"
public let borderRadiusSharp: Length = "var(--border-radius-sharp)"
public let borderRadiusPill: Length = "var(--border-radius-pill)"
public let borderRadiusCircle: Percentage = "var(--border-radius-circle)"
// MARK: - Applied: HIG Box Shadows & Outline
// Hue order: red, orange, yellow, green, mint, teal, cyan, blue, indigo, purple, pink, brown, gray
public let boxShadowColorRedActive: CSSColor = "var(--box-shadow-color-red-active)"
public let boxShadowColorRedFocus: CSSColor = "var(--box-shadow-color-red-focus)"
public let boxShadowColorOrangeActive: CSSColor = "var(--box-shadow-color-orange-active)"
public let boxShadowColorOrangeFocus: CSSColor = "var(--box-shadow-color-orange-focus)"
public let boxShadowColorYellowActive: CSSColor = "var(--box-shadow-color-yellow-active)"
public let boxShadowColorYellowFocus: CSSColor = "var(--box-shadow-color-yellow-focus)"
public let boxShadowColorGreenActive: CSSColor = "var(--box-shadow-color-green-active)"
public let boxShadowColorGreenFocus: CSSColor = "var(--box-shadow-color-green-focus)"
public let boxShadowColorMintActive: CSSColor = "var(--box-shadow-color-mint-active)"
public let boxShadowColorMintFocus: CSSColor = "var(--box-shadow-color-mint-focus)"
public let boxShadowColorTealActive: CSSColor = "var(--box-shadow-color-teal-active)"
public let boxShadowColorTealFocus: CSSColor = "var(--box-shadow-color-teal-focus)"
public let boxShadowColorCyanActive: CSSColor = "var(--box-shadow-color-cyan-active)"
public let boxShadowColorCyanFocus: CSSColor = "var(--box-shadow-color-cyan-focus)"
public let boxShadowColorBlueActive: CSSColor = "var(--box-shadow-color-blue-active)"
public let boxShadowColorBlueFocus: CSSColor = "var(--box-shadow-color-blue-focus)"
public let boxShadowColorIndigoActive: CSSColor = "var(--box-shadow-color-indigo-active)"
public let boxShadowColorIndigoFocus: CSSColor = "var(--box-shadow-color-indigo-focus)"
public let boxShadowColorIndigoSelected: CSSColor = "var(--box-shadow-color-indigo-selected)"
public let boxShadowColorIndigoSelectedHover: CSSColor = "var(--box-shadow-color-indigo-selected-hover)"
public let boxShadowColorIndigoSelectedActive: CSSColor = "var(--box-shadow-color-indigo-selected-active)"
public let boxShadowColorPurpleActive: CSSColor = "var(--box-shadow-color-purple-active)"
public let boxShadowColorPurpleFocus: CSSColor = "var(--box-shadow-color-purple-focus)"
public let boxShadowColorPinkActive: CSSColor = "var(--box-shadow-color-pink-active)"
public let boxShadowColorPinkFocus: CSSColor = "var(--box-shadow-color-pink-focus)"
public let boxShadowColorBrownActive: CSSColor = "var(--box-shadow-color-brown-active)"
public let boxShadowColorBrownFocus: CSSColor = "var(--box-shadow-color-brown-focus)"
public let boxShadowColorGrayActive: CSSColor = "var(--box-shadow-color-gray-active)"
public let boxShadowColorGrayFocus: CSSColor = "var(--box-shadow-color-gray-focus)"
public let outlineColorRedFocus: CSSColor = "var(--outline-color-red-focus)"
public let outlineColorOrangeFocus: CSSColor = "var(--outline-color-orange-focus)"
public let outlineColorYellowFocus: CSSColor = "var(--outline-color-yellow-focus)"
public let outlineColorGreenFocus: CSSColor = "var(--outline-color-green-focus)"
public let outlineColorMintFocus: CSSColor = "var(--outline-color-mint-focus)"
public let outlineColorTealFocus: CSSColor = "var(--outline-color-teal-focus)"
public let outlineColorCyanFocus: CSSColor = "var(--outline-color-cyan-focus)"
public let outlineColorBlueFocus: CSSColor = "var(--outline-color-blue-focus)"
public let outlineColorIndigoFocus: CSSColor = "var(--outline-color-indigo-focus)"
public let outlineColorPurpleFocus: CSSColor = "var(--outline-color-purple-focus)"
public let outlineColorPinkFocus: CSSColor = "var(--outline-color-pink-focus)"
public let outlineColorBrownFocus: CSSColor = "var(--outline-color-brown-focus)"
public let outlineColorGrayFocus: CSSColor = "var(--outline-color-gray-focus)"
// MARK: - Applied: Heights
public let minHeightTextArea: Length = "var(--min-height-text-area)"
public let minHeightTableHeader: Length = "var(--min-height-table-header)"
public let minHeightTableFooter: Length = "var(--min-height-table-footer)"
public let minHeightToggleSwitch: Length = "var(--min-height-toggle-switch)"
public let maxHeightChip: Length = "var(--max-height-chip)"

// MARK: - Applied: Links
public let colorLink: CSSColor = "var(--color-link)"
public let colorLinkHover: CSSColor = "var(--color-link-hover)"
public let colorLinkActive: CSSColor = "var(--color-link-active)"
public let colorLinkFocus: CSSColor = "var(--color-link-focus)"
public let colorLinkVisited: CSSColor = "var(--color-link-visited)"
public let colorLinkVisitedHover: CSSColor = "var(--color-link-visited-hover)"
public let colorLinkVisitedActive: CSSColor = "var(--color-link-visited-active)"
public let colorLinkRed: CSSColor = "var(--color-link-red)"
public let colorLinkRedHover: CSSColor = "var(--color-link-red-hover)"
public let colorLinkRedActive: CSSColor = "var(--color-link-red-active)"
public let colorLinkRedFocus: CSSColor = "var(--color-link-red-focus)"
public let colorLinkRedVisited: CSSColor = "var(--color-link-red-visited)"
public let colorLinkRedVisitedHover: CSSColor = "var(--color-link-red-visited-hover)"
public let colorLinkRedVisitedActive: CSSColor = "var(--color-link-red-visited-active)"

// MARK: - Applied: Icon Sizes
public let sizeIconXSmall: Length = "var(--size-icon-x-small)"
public let sizeIconSmall: Length = "var(--size-icon-small)"
public let sizeIconMedium: Length = "var(--size-icon-medium)"
public let sizeToggleSwitchGrip: Length = "var(--size-toggle-switch-grip)"

// MARK: - Applied: Box Shadows
public let boxShadowSmall: CSSSpreadShadow = "var(--box-shadow-small)"
public let boxShadowSmallTop: CSSSpreadShadow = "var(--box-shadow-small-top)"
public let boxShadowSmallBottom: CSSSpreadShadow = "var(--box-shadow-small-bottom)"
public let boxShadowMedium: CSSSpreadShadow = "var(--box-shadow-medium)"
public let boxShadowLarge: CSSSpreadShadow = "var(--box-shadow-large)"
public let accentColorBase: CSSColor = "var(--accent-color-base)"
public let positionOffsetBorderWidthBase: Length = "var(--position-offset-border-width-base)"

// MARK: - Applied: Button Spacing
public let spacingHorizontalButton: Length = "var(--spacing-horizontal-button)"
public let spacingHorizontalButtonIconOnly: Length = "var(--spacing-horizontal-button-icon-only)"
public let spacingHorizontalButtonSmallIconOnly: Length = "var(--spacing-horizontal-button-small-icon-only)"
public let spacingHorizontalButtonSmall: Length = "var(--spacing-horizontal-button-small)"
public let spacingHorizontalButtonLarge: Length = "var(--spacing-horizontal-button-large)"
public let spacingHorizontalInputTextTwoEndIcons: Length = "var(--spacing-horizontal-input-text-two-end-icons)"
public let spacingStartTypeaheadSearchFigure: Length = "var(--spacing-start-typeahead-search-figure)"
public let spacingToggleSwitchGripStart: Length = "var(--spacing-toggle-switch-grip-start)"
public let spacingToggleSwitchGripEnd: Length = "var(--spacing-toggle-switch-grip-end)"

// MARK: - Applied: Input Borders
public let borderColorInputHover: CSSColor = "var(--border-color-input-hover)"
public let borderColorInputBinary: CSSColor = "var(--border-color-input-binary)"
public let borderColorInputBinaryHover: CSSColor = "var(--border-color-input-binary-hover)"
public let borderColorInputBinaryActive: CSSColor = "var(--border-color-input-binary-active)"
public let borderColorInputBinaryFocus: CSSColor = "var(--border-color-input-binary-focus)"
public let borderColorInputBinaryChecked: CSSColor = "var(--border-color-input-binary-checked)"
public let borderBase: CSSBorder = "var(--border-base)"
public let borderSubtle: CSSBorder = "var(--border-subtle)"
public let borderTransparent: CSSBorder = "var(--border-transparent)"
public let borderRed: CSSBorder = "var(--border-red)"
public let borderOrange: CSSBorder = "var(--border-orange)"
public let borderYellow: CSSBorder = "var(--border-yellow)"
public let borderGreen: CSSBorder = "var(--border-green)"
public let borderMint: CSSBorder = "var(--border-mint)"
public let borderTeal: CSSBorder = "var(--border-teal)"
public let borderCyan: CSSBorder = "var(--border-cyan)"
public let borderBlue: CSSBorder = "var(--border-blue)"
public let borderIndigo: CSSBorder = "var(--border-indigo)"
public let borderPurple: CSSBorder = "var(--border-purple)"
public let borderPink: CSSBorder = "var(--border-pink)"
public let borderBrown: CSSBorder = "var(--border-brown)"
public let borderGray: CSSBorder = "var(--border-gray)"
public let outlineBaseFocus: CSSBorder = "var(--outline-base-focus)"

// MARK: - Applied: Toggle Switch
public let widthToggleSwitch: Length = "var(--width-toggle-switch)"
public let heightToggleSwitch: Length = "var(--height-toggle-switch)"
public let spacingStartTypeaheadSearchIcon: Length = "var(--spacing-start-typeahead-search-icon)"
public let spacingTypeaheadSearchFocusAddition: Length = "var(--spacing-typeahead-search-focus-addition)"
