#if !os(WASI)

import CSSBuilder
import WebTypes

// https://developer.apple.com/design/human-interface-guidelines/color
// https://doc.wikimedia.org/codex/latest/design-tokens/color.html
// https://doc.wikimedia.org/codex/latest/style-guide/colors.html
// https://meta.wikimedia.org/wiki/Brand/colours

// MARK: - Typography Tokens
@CSSBuilder
public func TypographyTokensCSS(config: TypographyConfig) -> [any CSS] {
	customProperty("--typography-font-sans", config.fontSans)
	customProperty("--typography-font-sans-italic", config.fontSansItalic)
	customProperty("--typography-font-serif", config.fontSerif)
	customProperty("--typography-font-serif-italic", config.fontSerifItalic)
	customProperty("--typography-font-mono", config.fontMono)
}

// MARK: - Color Tokens - Light Mode
@CSSBuilder
public func ColorTokensLightModeCSS() -> [any CSS] {
	colorScheme(.light).important()
	
	customProperty("--extreme", .black) // hex(0x000000)
	customProperty("--extreme-inverted", .white) // hex(0xFFFFFF)
}

// MARK: - Color Tokens - Dark Mode
@CSSBuilder
public func ColorTokensDarkModeCSS() -> [any CSS] {
	colorScheme(.dark).important()
	
	customProperty("--extreme", .white) // hex(0xFFFFFF)
	customProperty("--extreme-inverted", .black) // hex(0x000000)
}

// MARK: - Apple Human Interface Guidelines (HIG) - Design Tokens

@CSSBuilder
public func SourceTokensLightModeLessContrastCSS() -> [any CSS] {
	customProperty("--red-light-less", rgb(255, 56, 60)) // hex(0xFF383C)
	customProperty("--orange-light-less", rgb(255, 141, 40)) // hex(0xFF8D28)
	customProperty("--yellow-light-less", rgb(255, 204, 0)) // hex(0xFFCC00)
	customProperty("--green-light-less", rgb(52, 199, 89)) // hex(0x34C759)
	customProperty("--mint-light-less", rgb(0, 200, 179)) // hex(0x00C8B3)
	customProperty("--teal-light-less", rgb(0, 195, 208)) // hex(0x00C3D0)
	customProperty("--cyan-light-less", rgb(0, 192, 232)) // hex(0x00C0E8)
	customProperty("--blue-light-less", rgb(0, 136, 255)) // hex(0x0088FF)
	customProperty("--indigo-light-less", rgb(97, 85, 245)) // hex(0x6155F5)
	customProperty("--purple-light-less", rgb(203, 48, 224)) // hex(0xCB30E0)
	customProperty("--pink-light-less", rgb(255, 45, 85)) // hex(0xFF2D55)
	customProperty("--brown-light-less", rgb(172, 127, 94)) // hex(0xAC7F5E)

	customProperty("--gray-light-less", rgb(142, 142, 147)) // hex(0x8E8E93)
	customProperty("--gray2-light-less", rgb(174, 174, 178)) // hex(0xAEAEB2)
	customProperty("--gray3-light-less", rgb(199, 199, 204)) // hex(0xC7C7CC)
	customProperty("--gray4-light-less", rgb(209, 209, 214)) // hex(0xD1D1D6)
	customProperty("--gray5-light-less", rgb(229, 229, 234)) // hex(0xE5E5EA)
	customProperty("--gray6-light-less", rgb(242, 242, 247)) // hex(0xF2F2F7)
	
	// System Colors
	customProperty("--system-red", rgb(227, 0, 0)) // hex(0xE30000)
	customProperty("--system-orange", rgb(255, 149, 0)) // hex(0xFF9500)
	customProperty("--system-yellow", rgb(255, 204, 0)) // hex(0xFFCC00)
	customProperty("--system-green", rgb(52, 199, 89)) // hex(0x34C759)
	customProperty("--system-mint", rgb(0, 199, 190)) // hex(0x00C7BE)
	customProperty("--system-teal", rgb(48, 176, 199)) // hex(0x30B0C7)
	customProperty("--system-cyan", rgb(50, 173, 230)) // hex(0x32ADE6)
	customProperty("--system-blue", rgb(0, 122, 255)) // hex(0x007AFF)
	customProperty("--system-indigo", rgb(88, 86, 214)) // hex(0x5856D6)
	customProperty("--system-purple", rgb(175, 82, 222)) // hex(0xAF52DE)
	customProperty("--system-pink", rgb(255, 45, 85)) // hex(0xFF2D55)
	customProperty("--system-brown", rgb(162, 132, 94)) // hex(0xA2845E)

	// Fill
	customProperty("--fill", .white) // hex(0xFFFFFF)
	customProperty("--fill-alpha", rgba(120, 120, 128, 0.2))
	customProperty("--fill-secondary", rgb(250, 250, 252)) // hex(0xFAFAFC)
	customProperty("--fill-tertiary", rgb(245, 245, 247)) // hex(0xF5F5F7)
	customProperty("--fill-tertiary-alpha", rgba(118, 118, 128, 0.12))
	customProperty("--fill-gray", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--fill-gray-alpha", rgba(0, 0, 0, 0.88))
	customProperty("--fill-gray-hover", rgb(39, 39, 41)) // hex(0x272729)
	customProperty("--fill-gray-active", rgb(24, 24, 26)) // hex(0x18181A)
	customProperty("--fill-gray-secondary", rgb(134, 134, 139)) // hex(0x86868B)
	customProperty("--fill-gray-secondary-alpha", rgba(0, 0, 0, 0.48))
	customProperty("--fill-gray-tertiary", rgb(210, 210, 215)) // hex(0xD2D2D7)
	customProperty("--fill-gray-tertiary-alpha", rgba(0, 0, 0, 0.16))
	customProperty("--fill-gray-quaternary", rgb(232, 232, 237)) // hex(0xE8E8ED)
	customProperty("--fill-gray-quaternary-alpha", rgba(0, 0, 0, 0.08))
	customProperty("--fill-blue", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--fill-blue-hover", rgb(0, 118, 223)) // hex(0x0076DF)
	customProperty("--fill-blue-active", rgb(0, 110, 219)) // hex(0x006EDB)
	customProperty("--fill-blue-secondary", rgb(246, 251, 255)) // hex(0xF6FBFF)
	customProperty("--fill-red", rgb(227, 0, 0)) // hex(0xE30000)
	customProperty("--fill-red-secondary", rgb(255, 242, 244)) // hex(0xFFF2F4)
	customProperty("--fill-orange", rgb(245, 99, 0)) // hex(0xF56300)
	customProperty("--fill-orange-secondary", rgb(255, 249, 244)) // hex(0xFFF9F4)
	customProperty("--fill-yellow", rgb(255, 224, 69)) // hex(0xFFE045)
	customProperty("--fill-yellow-secondary", rgb(255, 254, 242)) // hex(0xFFFEF2)
	customProperty("--fill-green", rgb(3, 161, 14)) // hex(0x03A10E)
	customProperty("--fill-green-secondary", rgb(245, 255, 246)) // hex(0xF5FFF6)
	customProperty("--fill-purple-secondary", rgb(252, 248, 255)) // hex(0xFCF8FF)
	customProperty("--fill-teal-secondary", rgb(250, 255, 255)) // hex(0xFAFFFF)
	customProperty("--fill-light-blue-secondary", rgb(234, 243, 255)) // hex(0xEAF3FF)
	customProperty("--fill-light-gray-secondary", rgb(251, 251, 253)) // hex(0xFBFBFD)

	// Glyph
	customProperty("--glyph", .black) // hex(0x000000)
    customProperty("--glyph-fixed", .black) // hex(0x000000)
	customProperty("--glyph-gray", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--glyph-gray-alpha", rgba(0, 0, 0, 0.88))
    customProperty("--glyph-gray-fixed", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--glyph-gray-secondary", rgb(110, 110, 115)) // hex(0x6E6E73)
	customProperty("--glyph-gray-secondary-alpha", rgba(0, 0, 0, 0.56))
	customProperty("--glyph-gray-secondary-alt", rgb(66, 66, 69)) // hex(0x424245)
	customProperty("--glyph-gray-secondary-alt-alpha", rgba(0, 0, 0, 0.72))
	customProperty("--glyph-gray-tertiary", rgb(134, 134, 139)) // hex(0x86868B)
	customProperty("--glyph-gray-tertiary-alpha", rgba(0, 0, 0, 0.48))
	customProperty("--glyph-blue", rgb(0, 102, 204)) // hex(0x0066CC)
	customProperty("--glyph-orange", rgb(182, 68, 0)) // hex(0xB64400)
	customProperty("--glyph-green", rgb(0, 128, 9)) // hex(0x008009)
	customProperty("--glyph-red", rgb(227, 0, 0)) // hex(0xE30000)
	customProperty("--glyph-light-blue", rgb(76, 169, 255)) // hex(0x4CA9FF)
	customProperty("--glyph-light-gray", rgb(105, 105, 105)) // hex(0x696969)
	customProperty("--glyph-pink", rgb(187, 0, 187)) // hex(0xBB00BB)
	customProperty("--glyph-purple", rgb(140, 40, 194)) // hex(0x8C28C2)
	customProperty("--glyph-teal", rgb(61, 119, 125)) // hex(0x3D777D)
	customProperty("--glyph-yellow", rgb(158, 103, 0)) // hex(0x9E6700)

	// Links & Focus
	customProperty("--body-link-color", rgb(0, 102, 204)) // hex(0x0066CC)
	customProperty("--focus-color", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--focus-color-alpha", rgba(0, 125, 250, 0.6))
	customProperty("--opacity-disabled", 0.36)
	
	// Tint
	customProperty("--tint-cyan", rgba(50, 173, 230, 0.1))
	customProperty("--tint-cyan-opaque", rgb(234, 247, 252)) // hex(0xEAF7FC)
	customProperty("--tint-blue-opaque", rgb(75, 155, 235)) // hex(0x4B9BEB)
	customProperty("--tint-red-opaque", rgb(246, 173, 173)) // hex(0xF6ADAD)
	customProperty("--tint-blue-secondary-opaque", rgb(184, 215, 247)) // hex(0xB8D7F7)
	customProperty("--tint-blue-tertiary-opaque", rgb(225, 238, 252)) // hex(0xE1EEFC)
	customProperty("--tint-yellow", rgb(235, 184, 0)) // hex(0xEBB800)
	
	// Highlight
	customProperty("--highlight-green", rgb(228, 254, 230)) // hex(0xE4FEE6)
	customProperty("--highlight-red", rgb(248, 221, 221)) // hex(0xF8DDDD)
	
	// Standard
	customProperty("--standard-red", rgb(255, 194, 194)) // hex(0xFFC2C2)
	customProperty("--standard-orange", rgb(255, 204, 153)) // hex(0xFFCC99)
	customProperty("--standard-yellow", rgb(255, 224, 163)) // hex(0xFFE0A3)
	customProperty("--standard-green", rgb(153, 204, 204)) // hex(0x99CCCC)
	customProperty("--standard-blue", rgb(153, 204, 255)) // hex(0x99CCFF)
	customProperty("--standard-purple", rgb(204, 204, 255)) // hex(0xCCCCFF)
	customProperty("--standard-gray", rgb(175, 175, 175)) // hex(0xAFAFAF)
	
	// Syntax
	customProperty("--syntax-attributes", rgb(148, 113, 0)) // hex(0x947100)
	customProperty("--syntax-characters", rgb(39, 42, 216)) // hex(0x272AD8)
	customProperty("--syntax-comments", rgb(112, 127, 140)) // hex(0x707F8C)
	customProperty("--syntax-documentation-markup", rgb(80, 99, 117)) // hex(0x506375)
	customProperty("--syntax-heading", rgb(186, 45, 162)) // hex(0xBA2DA2)
	customProperty("--syntax-keywords", rgb(173, 61, 164)) // hex(0xAD3DA4)
	customProperty("--syntax-other-class-names", rgb(112, 61, 170)) // hex(0x703DAA)
	customProperty("--syntax-other-constants", rgb(75, 33, 176)) // hex(0x4B21B0)
	customProperty("--syntax-other-declarations", rgb(4, 124, 176)) // hex(0x047CB0)
	customProperty("--syntax-other-preprocessor-macros", rgb(120, 73, 42)) // hex(0x78492A)
	customProperty("--syntax-param-internal-name", rgb(64, 64, 64)) // hex(0x404040)
	customProperty("--syntax-project-class-names", rgb(62, 128, 135)) // hex(0x3E8087)
	customProperty("--syntax-project-constants", rgb(45, 100, 105)) // hex(0x2D6469)
	customProperty("--syntax-strings", rgb(209, 47, 27)) // hex(0xD12F1B)
	customProperty("--syntax-type-declarations", rgb(3, 99, 140)) // hex(0x03638C)
	customProperty("--syntax-urls", rgb(19, 55, 255)) // hex(0x1337FF)
	
	// Scrim
	customProperty("--scrim-hover", rgba(222.9661016949, 222.9661016949, 226.5254237288, 0.6976))
	customProperty("--scrim-active", rgba(192.9186602871, 192.9186602871, 197.5119617225, 0.6544))
	customProperty("--scrim-solid-hover", rgb(235.68, 235.68, 239.88))
	customProperty("--scrim-solid-active", rgb(222.72, 222.72, 227.52))
}

@CSSBuilder
public func SourceTokensLightModeMoreContrastCSS() -> [any CSS] {
	customProperty("--red-light-more", rgb(233, 21, 45)) // hex(0xE9152D)
	customProperty("--orange-light-more", rgb(197, 83, 0)) // hex(0xC55300)
	customProperty("--yellow-light-more", rgb(161, 106, 0)) // hex(0xA16A00)
	customProperty("--green-light-more", rgb(0, 137, 50)) // hex(0x008932)
	customProperty("--mint-light-more", rgb(0, 133, 117)) // hex(0x008575)
	customProperty("--teal-light-more", rgb(0, 129, 152)) // hex(0x008198)
	customProperty("--cyan-light-more", rgb(0, 126, 174)) // hex(0x007EAE)
	customProperty("--blue-light-more", rgb(30, 110, 244)) // hex(0x1E6EF4)
	customProperty("--indigo-light-more", rgb(86, 74, 222)) // hex(0x564ADE)
	customProperty("--purple-light-more", rgb(176, 47, 194)) // hex(0xB02FC2)
	customProperty("--pink-light-more", rgb(231, 18, 77)) // hex(0xE7124D)
	customProperty("--brown-light-more", rgb(149, 109, 81)) // hex(0x956D51)

	customProperty("--gray-light-more", rgb(108, 108, 112)) // hex(0x6C6C70)
	customProperty("--gray2-light-more", rgb(142, 142, 147)) // hex(0x8E8E93)
	customProperty("--gray3-light-more", rgb(174, 174, 178)) // hex(0xAEAEB2)
	customProperty("--gray4-light-more", rgb(188, 188, 192)) // hex(0xBCBCC0)
	customProperty("--gray5-light-more", rgb(216, 216, 220)) // hex(0xD8D8DC)
	customProperty("--gray6-light-more", rgb(235, 235, 240)) // hex(0xEBEBF0)
	
	// System Colors
	customProperty("--system-red", rgb(227, 0, 0)) // hex(0xE30000)
	customProperty("--system-orange", rgb(255, 149, 0)) // hex(0xFF9500)
	customProperty("--system-yellow", rgb(255, 204, 0)) // hex(0xFFCC00)
	customProperty("--system-green", rgb(52, 199, 89)) // hex(0x34C759)
	customProperty("--system-mint", rgb(0, 199, 190)) // hex(0x00C7BE)
	customProperty("--system-teal", rgb(48, 176, 199)) // hex(0x30B0C7)
	customProperty("--system-cyan", rgb(50, 173, 230)) // hex(0x32ADE6)
	customProperty("--system-blue", rgb(0, 122, 255)) // hex(0x007AFF)
	customProperty("--system-indigo", rgb(88, 86, 214)) // hex(0x5856D6)
	customProperty("--system-purple", rgb(175, 82, 222)) // hex(0xAF52DE)
	customProperty("--system-pink", rgb(255, 45, 85)) // hex(0xFF2D55)
	customProperty("--system-brown", rgb(162, 132, 94)) // hex(0xA2845E)

	// Fill
	customProperty("--fill", .white) // hex(0xFFFFFF)
	customProperty("--fill-alpha", rgba(120, 120, 128, 0.2))
	customProperty("--fill-secondary", rgb(250, 250, 252)) // hex(0xFAFAFC)
	customProperty("--fill-tertiary", rgb(245, 245, 247)) // hex(0xF5F5F7)
	customProperty("--fill-tertiary-alpha", rgba(118, 118, 128, 0.12))
	customProperty("--fill-gray", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--fill-gray-alpha", rgba(0, 0, 0, 0.88))
	customProperty("--fill-gray-hover", rgb(39, 39, 41)) // hex(0x272729)
	customProperty("--fill-gray-active", rgb(24, 24, 26)) // hex(0x18181A)
	customProperty("--fill-gray-secondary", rgb(134, 134, 139)) // hex(0x86868B)
	customProperty("--fill-gray-secondary-alpha", rgba(0, 0, 0, 0.48))
	customProperty("--fill-gray-tertiary", rgb(210, 210, 215)) // hex(0xD2D2D7)
	customProperty("--fill-gray-tertiary-alpha", rgba(0, 0, 0, 0.16))
	customProperty("--fill-gray-quaternary", rgb(232, 232, 237)) // hex(0xE8E8ED)
	customProperty("--fill-gray-quaternary-alpha", rgba(0, 0, 0, 0.08))
	customProperty("--fill-blue", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--fill-blue-hover", rgb(0, 118, 223)) // hex(0x0076DF)
	customProperty("--fill-blue-active", rgb(0, 110, 219)) // hex(0x006EDB)
	customProperty("--fill-blue-secondary", rgb(246, 251, 255)) // hex(0xF6FBFF)
	customProperty("--fill-red", rgb(227, 0, 0)) // hex(0xE30000)
	customProperty("--fill-red-secondary", rgb(255, 242, 244)) // hex(0xFFF2F4)
	customProperty("--fill-orange", rgb(245, 99, 0)) // hex(0xF56300)
	customProperty("--fill-orange-secondary", rgb(255, 249, 244)) // hex(0xFFF9F4)
	customProperty("--fill-yellow", rgb(255, 224, 69)) // hex(0xFFE045)
	customProperty("--fill-yellow-secondary", rgb(255, 254, 242)) // hex(0xFFFEF2)
	customProperty("--fill-green", rgb(3, 161, 14)) // hex(0x03A10E)
	customProperty("--fill-green-secondary", rgb(245, 255, 246)) // hex(0xF5FFF6)
	customProperty("--fill-purple-secondary", rgb(252, 248, 255)) // hex(0xFCF8FF)
	customProperty("--fill-teal-secondary", rgb(250, 255, 255)) // hex(0xFAFFFF)
	customProperty("--fill-light-blue-secondary", rgb(234, 243, 255)) // hex(0xEAF3FF)
	customProperty("--fill-light-gray-secondary", rgb(251, 251, 253)) // hex(0xFBFBFD)
	
	// Glyph
	customProperty("--glyph", .black) // hex(0x000000)
    customProperty("--glyph-fixed", .black) // hex(0x000000)
	customProperty("--glyph-gray", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--glyph-gray-fixed", rgb(29, 29, 31)) // hex(0x1D1D1F)
    customProperty("--glyph-gray-alpha", rgba(0, 0, 0, 0.88))
	customProperty("--glyph-gray-secondary", rgb(110, 110, 115)) // hex(0x6E6E73)
	customProperty("--glyph-gray-secondary-alpha", rgba(0, 0, 0, 0.56))
	customProperty("--glyph-gray-secondary-alt", rgb(66, 66, 69)) // hex(0x424245)
	customProperty("--glyph-gray-secondary-alt-alpha", rgba(0, 0, 0, 0.72))
	customProperty("--glyph-gray-tertiary", rgb(134, 134, 139)) // hex(0x86868B)
	customProperty("--glyph-gray-tertiary-alpha", rgba(0, 0, 0, 0.48))
	customProperty("--glyph-blue", rgb(0, 102, 204)) // hex(0x0066CC)
	customProperty("--glyph-orange", rgb(182, 68, 0)) // hex(0xB64400)
	customProperty("--glyph-green", rgb(0, 128, 9)) // hex(0x008009)
	customProperty("--glyph-red", rgb(227, 0, 0)) // hex(0xE30000)
	customProperty("--glyph-light-blue", rgb(76, 169, 255)) // hex(0x4CA9FF)
	customProperty("--glyph-light-gray", rgb(105, 105, 105)) // hex(0x696969)
	customProperty("--glyph-pink", rgb(187, 0, 187)) // hex(0xBB00BB)
	customProperty("--glyph-purple", rgb(140, 40, 194)) // hex(0x8C28C2)
	customProperty("--glyph-teal", rgb(61, 119, 125)) // hex(0x3D777D)
	customProperty("--glyph-yellow", rgb(158, 103, 0)) // hex(0x9E6700)

	// Links & Focus
	customProperty("--body-link-color", rgb(0, 102, 204)) // hex(0x0066CC)
	customProperty("--focus-color", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--focus-color-alpha", rgba(0, 125, 250, 0.6))
	customProperty("--opacity-disabled", 0.36)
	
	// Tint
	customProperty("--tint-cyan", rgba(50, 173, 230, 0.1))
	customProperty("--tint-cyan-opaque", rgb(234, 247, 252)) // hex(0xEAF7FC)
	customProperty("--tint-blue-opaque", rgb(75, 155, 235)) // hex(0x4B9BEB)
	customProperty("--tint-red-opaque", rgb(246, 173, 173)) // hex(0xF6ADAD)
	customProperty("--tint-blue-secondary-opaque", rgb(184, 215, 247)) // hex(0xB8D7F7)
	customProperty("--tint-blue-tertiary-opaque", rgb(225, 238, 252)) // hex(0xE1EEFC)
	customProperty("--tint-yellow", rgb(235, 184, 0)) // hex(0xEBB800)
	
	// Highlight
	customProperty("--highlight-green", rgb(228, 254, 230)) // hex(0xE4FEE6)
	customProperty("--highlight-red", rgb(248, 221, 221)) // hex(0xF8DDDD)
	
	// Standard
	customProperty("--standard-red", rgb(255, 194, 194)) // hex(0xFFC2C2)
	customProperty("--standard-orange", rgb(255, 204, 153)) // hex(0xFFCC99)
	customProperty("--standard-yellow", rgb(255, 224, 163)) // hex(0xFFE0A3)
	customProperty("--standard-green", rgb(153, 204, 204)) // hex(0x99CCCC)
	customProperty("--standard-blue", rgb(153, 204, 255)) // hex(0x99CCFF)
	customProperty("--standard-purple", rgb(204, 204, 255)) // hex(0xCCCCFF)
	customProperty("--standard-gray", rgb(175, 175, 175)) // hex(0xAFAFAF)
	
	// Syntax
	customProperty("--syntax-attributes", rgb(148, 113, 0)) // hex(0x947100)
	customProperty("--syntax-characters", rgb(39, 42, 216)) // hex(0x272AD8)
	customProperty("--syntax-comments", rgb(112, 127, 140)) // hex(0x707F8C)
	customProperty("--syntax-documentation-markup", rgb(80, 99, 117)) // hex(0x506375)
	customProperty("--syntax-heading", rgb(186, 45, 162)) // hex(0xBA2DA2)
	customProperty("--syntax-keywords", rgb(173, 61, 164)) // hex(0xAD3DA4)
	customProperty("--syntax-other-class-names", rgb(112, 61, 170)) // hex(0x703DAA)
	customProperty("--syntax-other-constants", rgb(75, 33, 176)) // hex(0x4B21B0)
	customProperty("--syntax-other-declarations", rgb(4, 124, 176)) // hex(0x047CB0)
	customProperty("--syntax-other-preprocessor-macros", rgb(120, 73, 42)) // hex(0x78492A)
	customProperty("--syntax-param-internal-name", rgb(64, 64, 64)) // hex(0x404040)
	customProperty("--syntax-project-class-names", rgb(62, 128, 135)) // hex(0x3E8087)
	customProperty("--syntax-project-constants", rgb(45, 100, 105)) // hex(0x2D6469)
	customProperty("--syntax-strings", rgb(209, 47, 27)) // hex(0xD12F1B)
	customProperty("--syntax-type-declarations", rgb(3, 99, 140)) // hex(0x03638C)
	customProperty("--syntax-urls", rgb(19, 55, 255)) // hex(0x1337FF)
	
	// Scrim
	customProperty("--scrim-hover", rgba(222.9661016949, 222.9661016949, 226.5254237288, 0.6976))
	customProperty("--scrim-active", rgba(192.9186602871, 192.9186602871, 197.5119617225, 0.6544))
	customProperty("--scrim-solid-hover", rgb(235.68, 235.68, 239.88))
	customProperty("--scrim-solid-active", rgb(222.72, 222.72, 227.52))
}

@CSSBuilder
public func SourceTokensDarkModeLessContrastCSS() -> [any CSS] {
	customProperty("--red-dark-less", rgb(255, 66, 69)) // hex(0xFF4245)
	customProperty("--orange-dark-less", rgb(255, 146, 48)) // hex(0xFF9230)
	customProperty("--yellow-dark-less", rgb(255, 214, 0)) // hex(0xFFD600)
	customProperty("--green-dark-less", rgb(48, 209, 88)) // hex(0x30D158)
	customProperty("--mint-dark-less", rgb(0, 218, 195)) // hex(0x00DAC3)
	customProperty("--teal-dark-less", rgb(0, 210, 224)) // hex(0x00D2E0)
	customProperty("--cyan-dark-less", rgb(60, 211, 254)) // hex(0x3CD3FE)
	customProperty("--blue-dark-less", rgb(0, 145, 255)) // hex(0x0091FF)
	customProperty("--indigo-dark-less", rgb(109, 124, 255)) // hex(0x6D7CFF)
	customProperty("--purple-dark-less", rgb(219, 52, 242)) // hex(0xDB34F2)
	customProperty("--pink-dark-less", rgb(255, 55, 95)) // hex(0xFF375F)
	customProperty("--brown-dark-less", rgb(183, 138, 102)) // hex(0xB78A66)

	customProperty("--gray-dark-less", rgb(142, 142, 147)) // hex(0x8E8E93)
	customProperty("--gray2-dark-less", rgb(99, 99, 102)) // hex(0x636366)
	customProperty("--gray3-dark-less", rgb(72, 72, 74)) // hex(0x48484A)
	customProperty("--gray4-dark-less", rgb(58, 58, 60)) // hex(0x3A3A3C)
	customProperty("--gray5-dark-less", rgb(44, 44, 46)) // hex(0x2C2C2E)
	customProperty("--gray6-dark-less", rgb(28, 28, 30)) // hex(0x1C1C1E)
	
	// System Colors
	customProperty("--system-red", rgb(255, 48, 55)) // hex(0xFF3037)
	customProperty("--system-orange", rgb(255, 159, 10)) // hex(0xFF9F0A)
	customProperty("--system-yellow", rgb(255, 214, 10)) // hex(0xFFD60A)
	customProperty("--system-green", rgb(50, 209, 88)) // hex(0x32D158)
	customProperty("--system-mint", rgb(99, 230, 226)) // hex(0x63E6E2)
	customProperty("--system-teal", rgb(64, 200, 224)) // hex(0x40C8E0)
	customProperty("--system-cyan", rgb(100, 210, 255)) // hex(0x64D2FF)
	customProperty("--system-blue", rgb(0, 154, 255)) // hex(0x009AFF)
	customProperty("--system-indigo", rgb(94, 92, 230)) // hex(0x5E5CE6)
	customProperty("--system-purple", rgb(191, 90, 242)) // hex(0xBF5AF2)
	customProperty("--system-pink", rgb(255, 55, 95)) // hex(0xFF375F)
	customProperty("--system-brown", rgb(172, 142, 104)) // hex(0xAC8E68)
	
	// Fill
	customProperty("--fill", .black) // hex(0x000000)
	customProperty("--fill-alpha", rgba(182, 182, 182, 0.3)) // hex(0xB6B6B6)
	customProperty("--fill-secondary", rgb(22, 22, 23)) // hex(0x161617)
	customProperty("--fill-tertiary", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--fill-tertiary-alpha", rgba(118, 118, 128, 0.24))
	customProperty("--fill-quaternary-alpha", rgba(116, 116, 128, 0.25))
	customProperty("--fill-gray", rgb(245, 245, 247)) // hex(0xF5F5F7)
	customProperty("--fill-gray-alpha", rgba(255, 255, 255, 0.92))
	customProperty("--fill-gray-secondary", rgb(110, 110, 115)) // hex(0x6E6E73)
	customProperty("--fill-gray-secondary-alpha", rgba(255, 255, 255, 0.4))
	customProperty("--fill-gray-tertiary", rgb(66, 66, 69)) // hex(0x424245)
	customProperty("--fill-gray-tertiary-alpha", rgba(255, 255, 255, 0.24))
	customProperty("--fill-gray-quaternary", rgb(51, 51, 54)) // hex(0x333336)
	customProperty("--fill-gray-quaternary-alpha", rgba(255, 255, 255, 0.2))
	customProperty("--fill-blue", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--fill-blue-hover", rgb(0, 118, 223)) // hex(0x0076DF)
	customProperty("--fill-blue-active", rgb(0, 110, 219)) // hex(0x006EDB)
	customProperty("--fill-blue-secondary", rgb(0, 25, 49)) // hex(0x001931)
	customProperty("--fill-red", rgb(255, 48, 55)) // hex(0xFF3037)
	customProperty("--fill-red-secondary", rgb(51, 0, 0)) // hex(0x330000)
	customProperty("--fill-orange-secondary", rgb(41, 13, 0)) // hex(0x290D00)
	customProperty("--fill-yellow", rgb(173, 130, 0)) // hex(0xAD8200)
	customProperty("--fill-yellow-secondary", rgb(43, 32, 0)) // hex(0x2B2000)
	customProperty("--fill-green-secondary", rgb(0, 43, 3)) // hex(0x002B03)
	customProperty("--fill-purple-secondary", rgb(25, 3, 37)) // hex(0x190325)
	customProperty("--fill-teal-secondary", rgb(0, 45, 43)) // hex(0x002D2B)
	customProperty("--fill-light-blue-secondary", rgb(0, 42, 81)) // hex(0x002A51)
	customProperty("--fill-light-gray-secondary", rgb(50, 50, 50)) // hex(0x323232)

	// Glyph
	customProperty("--glyph", .white) // hex(0xFFFFFF)
	customProperty("--glyph-gray", rgb(245, 245, 247)) // hex(0xF5F5F7)
	customProperty("--glyph-gray-alpha", rgba(255, 255, 255, 0.92))
	customProperty("--glyph-gray-secondary", rgb(134, 134, 139)) // hex(0x86868B)
	customProperty("--glyph-gray-secondary-alpha", rgba(255, 255, 255, 0.56))
	customProperty("--glyph-gray-secondary-alt", rgb(210, 210, 215)) // hex(0xD2D2D7)
	customProperty("--glyph-gray-secondary-alt-alpha", rgba(255, 255, 255, 0.8))
	customProperty("--glyph-gray-tertiary", rgb(110, 110, 115)) // hex(0x6E6E73)
	customProperty("--glyph-gray-tertiary-alpha", rgba(255, 255, 255, 0.4))
	customProperty("--glyph-blue", rgb(41, 151, 255)) // hex(0x2997FF)
	customProperty("--glyph-orange", rgb(255, 121, 27)) // hex(0xFF791B)
	customProperty("--glyph-green", rgb(3, 161, 14)) // hex(0x03A10E)
	customProperty("--glyph-red", rgb(255, 48, 55)) // hex(0xFF3037)
	customProperty("--glyph-light-blue", rgb(125, 193, 255)) // hex(0x7DC1FF)
	customProperty("--glyph-light-gray", rgb(154, 154, 158)) // hex(0x9A9A9E)
	customProperty("--glyph-pink", rgb(255, 55, 95)) // hex(0xFF375F)
	customProperty("--glyph-purple", rgb(169, 94, 210)) // hex(0xA95ED2)
	customProperty("--glyph-teal", rgb(64, 200, 224)) // hex(0x40C8E0)
	customProperty("--glyph-yellow", rgb(255, 181, 15)) // hex(0xFFB50F)

	// Links & Focus
	customProperty("--body-link-color", rgb(41, 151, 255)) // hex(0x2997FF)
	customProperty("--focus-color", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--focus-color-alt", .white) // hex(0xFFFFFF)
	customProperty("--opacity-disabled", 0.36)
	
	// Tint
	customProperty("--tint-cyan", rgba(100, 210, 255, 0.14))
	customProperty("--tint-cyan-opaque", rgb(38, 53, 62)) // hex(0x26353E)
	customProperty("--tint-blue", rgba(10, 132, 255, 0.7))
	customProperty("--tint-blue-opaque", rgb(15, 100, 187)) // hex(0x0F64BB)
	customProperty("--tint-red", rgba(244, 10, 10, 0.48))
	customProperty("--tint-red-opaque", rgb(78, 3, 3)) // hex(0x4E0303)
	customProperty("--tint-blue-secondary-opaque", rgb(22, 57, 93)) // hex(0x16395D)
	customProperty("--tint-blue-tertiary-opaque", rgb(27, 41, 57)) // hex(0x1B2939)
	
	// Highlight
	customProperty("--highlight-green", rgb(3, 38, 3)) // hex(0x032603)
	customProperty("--highlight-red", rgb(65, 6, 6)) // hex(0x410606)
	
	// Standard
	customProperty("--standard-orange", rgb(139, 64, 0)) // hex(0x8B4000)
	customProperty("--standard-yellow", rgb(143, 114, 0)) // hex(0x8F7200)
	customProperty("--standard-blue", rgb(0, 45, 117)) // hex(0x002D75)
	customProperty("--standard-green", rgb(2, 59, 45)) // hex(0x023B2D)
	customProperty("--standard-purple", rgb(81, 43, 85)) // hex(0x512B55)
	
	// Syntax
	customProperty("--syntax-attributes", rgb(204, 151, 104)) // hex(0xCC9768)
	customProperty("--syntax-characters", rgb(217, 201, 124)) // hex(0xD9C97C)
	customProperty("--syntax-comments", rgb(127, 140, 152)) // hex(0x7F8C98)
	customProperty("--syntax-documentation-markup-keywords", rgb(163, 177, 191)) // hex(0xA3B1BF)
	customProperty("--syntax-keywords", rgb(255, 122, 178)) // hex(0xFF7AB2)
	customProperty("--syntax-other-class-names", rgb(218, 186, 255)) // hex(0xDABAFF)
	customProperty("--syntax-other-constants", rgb(167, 235, 221)) // hex(0xA7EBDD)
	customProperty("--syntax-other-declarations", rgb(78, 176, 204)) // hex(0x4EB0CC)
	customProperty("--syntax-other-function-and-method-names", rgb(178, 129, 235)) // hex(0xB281EB)
	customProperty("--syntax-other-preprocessor-macros", rgb(255, 161, 79)) // hex(0xFFA14F)
	customProperty("--syntax-param-internal-name", rgb(191, 191, 191)) // hex(0xBFBFBF)
	customProperty("--syntax-project-class-names", rgb(172, 242, 228)) // hex(0xACF2E4)
	customProperty("--syntax-project-constants", rgb(120, 194, 179)) // hex(0x78C2B3)
	customProperty("--syntax-strings", rgb(255, 129, 112)) // hex(0xFF8170)
	customProperty("--syntax-type-declarations", rgb(107, 223, 255)) // hex(0x6BDFFF)
	customProperty("--syntax-urls", rgb(102, 153, 255)) // hex(0x6699FF)
	
	// Scrim
	customProperty("--scrim-hover", rgba(72.6170678337, 72.6170678337, 75.5120350109, 0.7256))
	customProperty("--scrim-active", rgba(57.1631799163, 57.1631799163, 59.7615062762, 0.7424))
	customProperty("--scrim-solid-hover", rgb(55.08, 55.08, 58.02))
	customProperty("--scrim-solid-active", rgb(46.92, 46.92, 49.68))
	
	// Background Layers
	customProperty("--background-primary", rgb(28, 28, 30)) // hex(0x1C1C1E)
	customProperty("--background-layer1", rgb(50, 50, 54)) // hex(0x323236)
	customProperty("--background-layer2", rgb(67, 67, 73)) // hex(0x434349)
	customProperty("--backdrop", rgba(10, 10, 10, 0.8))
	customProperty("--sidebar", rgb(32, 32, 35)) // hex(0x202023)
	customProperty("--separator", rgb(52, 52, 54)) // hex(0x343436)
}

@CSSBuilder
public func SourceTokensDarkModeMoreContrastCSS() -> [any CSS] {
	customProperty("--red-dark-more", rgb(255, 97, 101)) // hex(0xFF6165)
	customProperty("--orange-dark-more", rgb(255, 160, 86)) // hex(0xFFA056)
	customProperty("--yellow-dark-more", rgb(254, 223, 67)) // hex(0xFEDF43)
	customProperty("--green-dark-more", rgb(74, 217, 104)) // hex(0x4AD968)
	customProperty("--mint-dark-more", rgb(84, 223, 203)) // hex(0x54DFCB)
	customProperty("--teal-dark-more", rgb(59, 221, 236)) // hex(0x3BDDEC)
	customProperty("--cyan-dark-more", rgb(109, 217, 255)) // hex(0x6DD9FF)
	customProperty("--blue-dark-more", rgb(92, 184, 255)) // hex(0x5CB8FF)
	customProperty("--indigo-dark-more", rgb(167, 170, 255)) // hex(0xA7AAFF)
	customProperty("--purple-dark-more", rgb(234, 141, 255)) // hex(0xEA8DFF)
	customProperty("--pink-dark-more", rgb(255, 138, 196)) // hex(0xFF8AC4)
	customProperty("--brown-dark-more", rgb(219, 166, 121)) // hex(0xDBA679)

	customProperty("--gray-dark-more", rgb(174, 174, 178)) // hex(0xAEAEB2)
	customProperty("--gray2-dark-more", rgb(124, 124, 128)) // hex(0x7C7C80)
	customProperty("--gray3-dark-more", rgb(84, 84, 86)) // hex(0x545456)
	customProperty("--gray4-dark-more", rgb(68, 68, 70)) // hex(0x444446)
	customProperty("--gray5-dark-more", rgb(54, 54, 56)) // hex(0x363638)
	customProperty("--gray6-dark-more", rgb(36, 36, 38)) // hex(0x242426)
	
	// System Colors
	customProperty("--system-red", rgb(255, 48, 55)) // hex(0xFF3037)
	customProperty("--system-orange", rgb(255, 159, 10)) // hex(0xFF9F0A)
	customProperty("--system-yellow", rgb(255, 214, 10)) // hex(0xFFD60A)
	customProperty("--system-green", rgb(50, 209, 88)) // hex(0x32D158)
	customProperty("--system-mint", rgb(99, 230, 226)) // hex(0x63E6E2)
	customProperty("--system-teal", rgb(64, 200, 224)) // hex(0x40C8E0)
	customProperty("--system-cyan", rgb(100, 210, 255)) // hex(0x64D2FF)
	customProperty("--system-blue", rgb(0, 154, 255)) // hex(0x009AFF)
	customProperty("--system-indigo", rgb(94, 92, 230)) // hex(0x5E5CE6)
	customProperty("--system-purple", rgb(191, 90, 242)) // hex(0xBF5AF2)
	customProperty("--system-pink", rgb(255, 55, 95)) // hex(0xFF375F)
	customProperty("--system-brown", rgb(172, 142, 104)) // hex(0xAC8E68)

	// Fill
	customProperty("--fill", .black) // hex(0x000000)
	customProperty("--fill-alpha", rgba(182, 182, 182, 0.3)) // hex(0xB6B6B6)
	customProperty("--fill-secondary", rgb(22, 22, 23)) // hex(0x161617)
	customProperty("--fill-tertiary", rgb(29, 29, 31)) // hex(0x1D1D1F)
	customProperty("--fill-tertiary-alpha", rgba(118, 118, 128, 0.24))
	customProperty("--fill-quaternary-alpha", rgba(116, 116, 128, 0.25))
	customProperty("--fill-gray", rgb(245, 245, 247)) // hex(0xF5F5F7)
	customProperty("--fill-gray-alpha", rgba(255, 255, 255, 0.92))
	customProperty("--fill-gray-secondary", rgb(110, 110, 115)) // hex(0x6E6E73)
	customProperty("--fill-gray-secondary-alpha", rgba(255, 255, 255, 0.4))
	customProperty("--fill-gray-tertiary", rgb(66, 66, 69)) // hex(0x424245)
	customProperty("--fill-gray-tertiary-alpha", rgba(255, 255, 255, 0.24))
	customProperty("--fill-gray-quaternary", rgb(51, 51, 54)) // hex(0x333336)
	customProperty("--fill-gray-quaternary-alpha", rgba(255, 255, 255, 0.2))
	customProperty("--fill-blue", rgb(0, 113, 227)) // hex(0x0071E3)
	customProperty("--fill-blue-hover", rgb(0, 118, 223)) // hex(0x0076DF)
	customProperty("--fill-blue-active", rgb(0, 110, 219)) // hex(0x006EDB)
	customProperty("--fill-blue-secondary", rgb(0, 25, 49)) // hex(0x001931)
	customProperty("--fill-red", rgb(255, 48, 55)) // hex(0xFF3037)
	customProperty("--fill-red-secondary", rgb(51, 0, 0)) // hex(0x330000)
	customProperty("--fill-orange-secondary", rgb(41, 13, 0)) // hex(0x290D00)
	customProperty("--fill-yellow", rgb(173, 130, 0)) // hex(0xAD8200)
	customProperty("--fill-yellow-secondary", rgb(43, 32, 0)) // hex(0x2B2000)
	customProperty("--fill-green-secondary", rgb(0, 43, 3)) // hex(0x002B03)
	customProperty("--fill-purple-secondary", rgb(25, 3, 37)) // hex(0x190325)
	customProperty("--fill-teal-secondary", rgb(0, 45, 43)) // hex(0x002D2B)
	customProperty("--fill-light-blue-secondary", rgb(0, 42, 81)) // hex(0x002A51)
	customProperty("--fill-light-gray-secondary", rgb(50, 50, 50)) // hex(0x323232)

	// Glyph
	customProperty("--glyph", .white) // hex(0xFFFFFF)
	customProperty("--glyph-gray", rgb(245, 245, 247)) // hex(0xF5F5F7)
	customProperty("--glyph-gray-alpha", rgba(255, 255, 255, 0.92))
	customProperty("--glyph-gray-secondary", rgb(134, 134, 139)) // hex(0x86868B)
	customProperty("--glyph-gray-secondary-alpha", rgba(255, 255, 255, 0.56))
	customProperty("--glyph-gray-secondary-alt", rgb(210, 210, 215)) // hex(0xD2D2D7)
	customProperty("--glyph-gray-secondary-alt-alpha", rgba(255, 255, 255, 0.8))
	customProperty("--glyph-gray-tertiary", rgb(110, 110, 115)) // hex(0x6E6E73)
	customProperty("--glyph-gray-tertiary-alpha", rgba(255, 255, 255, 0.4))
	customProperty("--glyph-blue", rgb(41, 151, 255)) // hex(0x2997FF)
	customProperty("--glyph-orange", rgb(255, 121, 27)) // hex(0xFF791B)
	customProperty("--glyph-green", rgb(3, 161, 14)) // hex(0x03A10E)
	customProperty("--glyph-red", rgb(255, 48, 55)) // hex(0xFF3037)
	customProperty("--glyph-light-blue", rgb(125, 193, 255)) // hex(0x7DC1FF)
	customProperty("--glyph-light-gray", rgb(154, 154, 158)) // hex(0x9A9A9E)
	customProperty("--glyph-pink", rgb(255, 55, 95)) // hex(0xFF375F)
	customProperty("--glyph-purple", rgb(169, 94, 210)) // hex(0xA95ED2)
	customProperty("--glyph-teal", rgb(64, 200, 224)) // hex(0x40C8E0)
	customProperty("--glyph-yellow", rgb(255, 181, 15)) // hex(0xFFB50F)
	
	// Links & Focus
	customProperty("--body-link-color", rgb(41, 151, 255)) // hex(0x2997FF)
	customProperty("--focus-color", .white) // hex(0xFFFFFF)
	customProperty("--focus-color-alt", .white) // hex(0xFFFFFF)
	customProperty("--opacity-disabled", 0.36)
	
	// Tint
	customProperty("--tint-cyan", rgba(100, 210, 255, 0.14))
	customProperty("--tint-cyan-opaque", rgb(38, 53, 62)) // hex(0x26353E)
	customProperty("--tint-blue", rgba(10, 132, 255, 0.7))
	customProperty("--tint-blue-opaque", rgb(15, 100, 187)) // hex(0x0F64BB)
	customProperty("--tint-red", rgba(244, 10, 10, 0.48))
	customProperty("--tint-red-opaque", rgb(78, 3, 3)) // hex(0x4E0303)
	customProperty("--tint-blue-secondary-opaque", rgb(22, 57, 93)) // hex(0x16395D)
	customProperty("--tint-blue-tertiary-opaque", rgb(27, 41, 57)) // hex(0x1B2939)
	
	// Highlight
	customProperty("--highlight-green", rgb(3, 38, 3)) // hex(0x032603)
	customProperty("--highlight-red", rgb(65, 6, 6)) // hex(0x410606)
	
	// Standard
	customProperty("--standard-red", rgb(139, 0, 0)) // hex(0x8B0000)
	customProperty("--standard-orange", rgb(139, 64, 0)) // hex(0x8B4000)
	customProperty("--standard-yellow", rgb(143, 114, 0)) // hex(0x8F7200)
	customProperty("--standard-green", rgb(2, 59, 45)) // hex(0x023B2D)
	customProperty("--standard-blue", rgb(0, 45, 117)) // hex(0x002D75)
	customProperty("--standard-purple", rgb(81, 43, 85)) // hex(0x512B55)
	customProperty("--standard-gray", rgb(85, 85, 85)) // hex(0x555555)
	
	// Syntax
	customProperty("--syntax-attributes", rgb(204, 151, 104)) // hex(0xCC9768)
	customProperty("--syntax-characters", rgb(217, 201, 124)) // hex(0xD9C97C)
	customProperty("--syntax-comments", rgb(127, 140, 152)) // hex(0x7F8C98)
	customProperty("--syntax-documentation-markup-keywords", rgb(163, 177, 191)) // hex(0xA3B1BF)
	customProperty("--syntax-keywords", rgb(255, 122, 178)) // hex(0xFF7AB2)
	customProperty("--syntax-other-class-names", rgb(218, 186, 255)) // hex(0xDABAFF)
	customProperty("--syntax-other-constants", rgb(167, 235, 221)) // hex(0xA7EBDD)
	customProperty("--syntax-other-declarations", rgb(78, 176, 204)) // hex(0x4EB0CC)
	customProperty("--syntax-other-function-and-method-names", rgb(178, 129, 235)) // hex(0xB281EB)
	customProperty("--syntax-other-preprocessor-macros", rgb(255, 161, 79)) // hex(0xFFA14F)
	customProperty("--syntax-param-internal-name", rgb(191, 191, 191)) // hex(0xBFBFBF)
	customProperty("--syntax-project-class-names", rgb(172, 242, 228)) // hex(0xACF2E4)
	customProperty("--syntax-project-constants", rgb(120, 194, 179)) // hex(0x78C2B3)
	customProperty("--syntax-strings", rgb(255, 129, 112)) // hex(0xFF8170)
	customProperty("--syntax-type-declarations", rgb(107, 223, 255)) // hex(0x6BDFFF)
	customProperty("--syntax-urls", rgb(102, 153, 255)) // hex(0x6699FF)
	
	// Scrim
	customProperty("--scrim-hover", rgba(72.6170678337, 72.6170678337, 75.5120350109, 0.7256))
	customProperty("--scrim-active", rgba(57.1631799163, 57.1631799163, 59.7615062762, 0.7424))
	customProperty("--scrim-solid-hover", rgb(55.08, 55.08, 58.02))
	customProperty("--scrim-solid-active", rgb(46.92, 46.92, 49.68))
	
	// Background Layers
	customProperty("--background-primary", rgb(28, 28, 30)) // hex(0x1C1C1E)
	customProperty("--background-layer1", rgb(50, 50, 54)) // hex(0x323236)
	customProperty("--background-layer2", rgb(67, 67, 73)) // hex(0x434349)
	customProperty("--backdrop", rgba(10, 10, 10, 0.8))
	customProperty("--sidebar", rgb(32, 32, 35)) // hex(0x202023)
	customProperty("--separator", rgb(52, 52, 54)) // hex(0x343436)
}

@CSSBuilder
public func AppliedTokensLightModeLessContrastCSS() -> [any CSS] {
	colorScheme(.light).important()
	
	customProperty("--color-base", glyphGray) // was hex(0x202122)
	customProperty("--color-base-fixed", glyphGrayFixed) // was hex(0x202122)
	customProperty("--color-base-hover", glyphGraySecondary) // was hex(0x404244)
	customProperty("--color-emphasized", glyph) // was hex(0x101418)
	customProperty("--color-subtle", glyphGraySecondary) // was hex(0x54595D)
	customProperty("--color-placeholder", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--color-disabled", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--color-disabled-emphasized", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--color-inverted", fill) // was hex(0xFFFFFF)
	customProperty("--color-inverted-fixed", .white) // was hex(0xFFFFFF)
	customProperty("--color-progressive", glyphBlue) // was hex(0x3366CC)
	customProperty("--color-progressive-hover", colorMix(in: .srgb, glyphBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--color-progressive-active", colorMix(in: .srgb, glyphBlue, (.black, perc(30)))) // was hex(0x233566)
	customProperty("--color-progressive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--color-destructive", glyphRed) // was hex(0xBF3C2C)
	customProperty("--color-destructive-hover", colorMix(in: .srgb, glyphRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--color-destructive-active", colorMix(in: .srgb, glyphRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--color-destructive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--color-visited", purpleLightLess) // was hex(0x6A60B0)
	customProperty("--color-visited-hover", colorMix(in: .srgb, purpleLightLess, (.black, perc(10)))) // was hex(0x534FA3)
	customProperty("--color-visited-active", colorMix(in: .srgb, purpleLightLess, (.black, perc(30)))) // was hex(0x353262)
	customProperty("--color-destructive-visited", colorMix(in: .srgb, glyphRed, (.black, perc(10)))) // was hex(0x9F5555)
	customProperty("--color-destructive-visited-hover", colorMix(in: .srgb, glyphRed, (.black, perc(20)))) // was hex(0x854848)
	customProperty("--color-destructive-visited-active", colorMix(in: .srgb, glyphRed, (.black, perc(40)))) // was hex(0x512E2E)
	customProperty("--color-error", fillRed) // was hex(0xBF3C2C)
	customProperty("--color-error-hover", colorMix(in: .srgb, fillRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--color-error-active", colorMix(in: .srgb, fillRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--color-warning", glyphOrange) // was hex(0x886425)
	customProperty("--color-success", glyphGreen) // was hex(0x177860)
	customProperty("--color-notice", glyphGraySecondary) // was hex(0x404244)
	customProperty("--color-icon-error", fillRed) // was hex(0xF54739)
	customProperty("--color-icon-warning", glyphOrange) // was hex(0xAB7F2A)
	customProperty("--color-icon-success", glyphGreen) // was hex(0x099979)
	customProperty("--color-icon-notice", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--color-content-added", glyphGreen) // was hex(0x006400)
	customProperty("--color-content-removed", glyphRed) // was hex(0x8B0000)
	customProperty("--opacity-base", 1)
	customProperty("--opacity-medium", 0.65)
	customProperty("--opacity-low", 0.3)
	customProperty("--opacity-transparent", 0)
	customProperty("--filter-invert-icon", 0)
	customProperty("--filter-invert-primary-button-icon", 1)
	customProperty("--background-position-base", .center)
	customProperty("--background-size-search-figure", .cover)
	customProperty("--z-index-bottom", -100)
	customProperty("--z-index-base", 0)
	customProperty("--z-index-above-content", 1)
	customProperty("--z-index-toolbar", 2)
	customProperty("--z-index-dropdown", 50)
	customProperty("--z-index-sticky", 100)
	customProperty("--z-index-fixed", 200)
	customProperty("--z-index-off-canvas-backdrop", 300)
	customProperty("--z-index-off-canvas", 350)
	customProperty("--z-index-overlay-backdrop", 400)
	customProperty("--z-index-overlay", 450)
	customProperty("--z-index-popover", 700)
	customProperty("--z-index-tooltip", 800)
	customProperty("--z-index-toast-notification", 900)
	customProperty("--z-index-top", 9999)
	customProperty("--z-index-stacking-0", 0)
	customProperty("--z-index-stacking-1", 1)
	customProperty("--z-index-stacking-2", 2)
	customProperty("--z-index-stacking-3", 3)
	customProperty("--box-sizing-base", .borderBox)
	customProperty("--size-0", rem(0))
	customProperty("--size-1", rem(0.0625))
	customProperty("--size-2", rem(0.125))
	customProperty("--size-4", rem(0.25))
	customProperty("--size-8", rem(0.5))
	customProperty("--size-12", rem(0.75))
	customProperty("--size-16", rem(1))
	customProperty("--size-20", rem(1.25))
	customProperty("--size-24", rem(1.5))
	customProperty("--size-32", rem(2))
	customProperty("--size-40", rem(2.5))
	customProperty("--size-44", rem(2.75))
	customProperty("--size-48", rem(3))
	customProperty("--size-64", rem(4))
	customProperty("--size-128", rem(8))
	customProperty("--size-192", rem(12))
	customProperty("--size-256", rem(16))
	customProperty("--size-384", rem(24))
	customProperty("--size-448", rem(28))
	customProperty("--size-512", rem(32))
	customProperty("--size-640", rem(40))
	customProperty("--size-896", rem(56))
	customProperty("--size-viewport-width-full", vw(100))
	customProperty("--size-viewport-height-full", vh(100))
	customProperty("--size-absolute-1", px(1))
	customProperty("--size-absolute-9999", px(9999))
	customProperty("--size-content-min", .minContent)
	customProperty("--size-content-fit", .fitContent)
	customProperty("--size-content-max", .maxContent)
	customProperty("--size-third", perc(33.33))
	customProperty("--size-half", perc(50))
	customProperty("--size-full", perc(100))
	customProperty("--size-double", perc(200))
	customProperty("--size-search-figure", rem(2.5))
	customProperty("--max-width-base", CSSKeyword.None.none)
	customProperty("--max-width-breakpoint-mobile", calc(px(640) - sizeAbsolute1))
	customProperty("--max-width-breakpoint-tablet", calc(px(1120) - sizeAbsolute1))
	customProperty("--max-width-breakpoint-desktop", calc(px(1680) - sizeAbsolute1))
	customProperty("--max-width-button", rem(28))
	customProperty("--border-style-base", .solid)
	customProperty("--border-style-dashed", .dashed)
	customProperty("--box-shadow-inset-small", (.inset, 0, 0, 0, px(1)))
	customProperty("--box-shadow-inset-medium", (.inset, 0, 0, 0, px(2)))
	customProperty("--box-shadow-inset-medium-vertical", (.inset, 0, -2, 0, 0))
	customProperty("--box-shadow-outset-small", (0, 0, 0, px(1)))
	customProperty("--box-shadow-outset-small-top", (0, px(-1), 0, 0))
	customProperty("--box-shadow-outset-small-bottom", (0, px(1), 0, 0))
	customProperty("--box-shadow-outset-small-start", (px(-1), 0, 0, 0))
	customProperty("--box-shadow-outset-medium-below", (0, px(4), px(4), 0))
	customProperty("--box-shadow-outset-medium-around", (0, 0, px(8), 0))
	customProperty("--box-shadow-outset-large-below", (0, px(4), px(8), 0))
	customProperty("--box-shadow-outset-large-around", (0, 0, px(16), 0))
	customProperty("--box-shadow-color-base", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--box-shadow-color-progressive-active", colorMix(in: .srgb, glyphBlue, (.black, perc(30)))) // was hex(0x233566)
	customProperty("--box-shadow-color-progressive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--box-shadow-color-progressive-selected", glyphBlue) // was hex(0x3366CC)
	customProperty("--box-shadow-color-progressive-selected-hover", colorMix(in: .srgb, glyphBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--box-shadow-color-progressive-selected-active", colorMix(in: .srgb, glyphBlue, (.black, perc(30)))) // was hex(0x233566)
	customProperty("--box-shadow-color-destructive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--box-shadow-color-inverted", .white) // was hex(0xFFFFFF)
	customProperty("--box-shadow-color-alpha-base", rgba(0, 0, 0, 0.06))
	customProperty("--box-shadow-color-transparent", .transparent)
	customProperty("--font-family-base", CSSFontFamily.GenericFamily.GenericComplete.sansSerif)
	customProperty("--font-family-system-sans", ("\"-apple-system\"", "\"BlinkMacSystemFont\"", "\"Segoe UI\"", "\"Roboto\"", "\"Inter\"", "\"Helvetica\"", "\"Arial\"", CSSFontFamily.GenericFamily.GenericComplete.sansSerif))
	customProperty("--font-family-sans--fallback", CSSFontFamily.GenericFamily.GenericComplete.sansSerif)
	customProperty("--font-family-serif", ("\"Linux Libertine\"", "\"Georgia\"", "\"Times\"", "\"Source Serif 4\"", CSSFontFamily.GenericFamily.GenericComplete.serif))
	customProperty("--font-family-serif--fallback", CSSFontFamily.GenericFamily.GenericComplete.serif)
	customProperty("--font-family-monospace", ("\"Menlo\"", "\"Consolas\"", "\"Liberation Mono\"", "\"Fira Code\"", "\"Courier New\"", CSSFontFamily.GenericFamily.GenericComplete.monospace))
	customProperty("--font-family-monospace--fallback", CSSFontFamily.GenericFamily.GenericComplete.monospace)
	customProperty("--font-family-heading-main", ("\"Linux Libertine\"", "\"Georgia\"", "\"Times\"", "\"Source Serif 4\"", CSSFontFamily.GenericFamily.GenericComplete.monospace))
	customProperty("--font-size-x-small-12", rem(0.75))
	customProperty("--font-size-small-14", rem(0.875))
	customProperty("--font-size-medium-16", rem(1))
	customProperty("--font-size-large-18", rem(1.125))
	customProperty("--font-size-x-large-20", rem(1.25))
	customProperty("--font-size-xx-large-24", rem(1.5))
	customProperty("--font-size-xxx-large-28", rem(1.75))
	customProperty("--font-weight-hairline", 100)
	customProperty("--font-weight-light", 300)
	customProperty("--font-weight-normal", 400)
	customProperty("--font-weight-semi-bold", 600)
	customProperty("--font-weight-bold", 700)
	customProperty("--line-height-x-small-20", rem(1.25))
	customProperty("--line-height-small-22", rem(1.375))
	customProperty("--line-height-medium-26", rem(1.625))
	customProperty("--line-height-large-28", rem(1.75))
	customProperty("--line-height-x-large-30", rem(1.875))
	customProperty("--line-height-xx-large-34", rem(2.125))
	customProperty("--line-height-xxx-large-38", rem(2.375))
	customProperty("--line-height-content", 1.625)
	customProperty("--text-decoration-none", CSSKeyword.None.none)
	customProperty("--text-decoration-line-through", .lineThrough)
	customProperty("--text-decoration-underline", .underline)
	customProperty("--text-overflow-clip", .clip)
	customProperty("--text-overflow-ellipsis", .ellipsis)
	customProperty("--tab-size-base", 4)
	customProperty("--transform-checkbox-tick--checked", rotate(deg(45)))
	customProperty("--transform-progress-indicator-spinner-start", rotate(deg(-45)))
	customProperty("--transform-progress-indicator-spinner-end", rotate(deg(315)))
	customProperty("--transition-duration-base", ms(100))
	customProperty("--transition-duration-medium", ms(250))
	customProperty("--transition-property-base", (.backgroundColor, .color, .borderColor, .boxShadow))
	customProperty("--transition-property-fade", .opacity)
	customProperty("--transition-property-icon", CSSSingleTransitionProperty.color)
	customProperty("--transition-property-icon-css-only", .backgroundColor)
	customProperty("--transition-property-toggle-switch-grip", (.backgroundColor, .borderColor, .transform))
	customProperty("--transition-timing-function-system", .ease)
	customProperty("--transition-timing-function-user", .easeOut)
	customProperty("--animation-delay-none", ms(0))
	customProperty("--animation-delay-medium", ms(-160))
	customProperty("--animation-delay-slow", ms(-320))
	customProperty("--animation-duration-fast", ms(1000))
	customProperty("--animation-duration-medium", ms(1600))
	customProperty("--animation-duration-slow", ms(2000))
	customProperty("--animation-timing-function-base", .linear)
	customProperty("--animation-timing-function-bouncing", .easeInOut)
	customProperty("--animation-iteration-count-base", .infinite)
	customProperty("--cursor-base", .default)
	customProperty("--cursor-base--disabled", .default)
	customProperty("--cursor-base-hover", .pointer)
	customProperty("--cursor-grab", .grab)
	customProperty("--cursor-grabbing", .grabbing)
	customProperty("--cursor-help", .help)
	customProperty("--cursor-move", .move)
	customProperty("--cursor-not-allowed", .notAllowed)
	customProperty("--cursor-resize-nesw", .neswResize)
	customProperty("--cursor-resize-nwse", .nwseResize)
	customProperty("--cursor-text", .text)
	customProperty("--cursor-zoom-in", .zoomIn)
	customProperty("--cursor-zoom-out", .zoomOut)
	customProperty("--mix-blend-mode-base", .normal)
	customProperty("--mix-blend-mode-blend", .multiply)

	customProperty("--background-color-base", fill) // was hex(0xFFFFFF)
	customProperty("--background-color-base-fixed", .white) // was hex(0xFFFFFF)
	customProperty("--background-color-neutral", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-neutral-subtle", fillSecondary) // was hex(0xF8F9FA)
	customProperty("--background-color-interactive", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-interactive-hover", fillGrayTertiary) // was hex(0xDADDE3)
	customProperty("--background-color-interactive-active", fillGraySecondary) // was hex(0xC8CCD1)
	customProperty("--background-color-interactive-subtle", fillSecondary) // was hex(0xF8F9FA)
	customProperty("--background-color-interactive-subtle-hover", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-interactive-subtle-active", fillGrayTertiary) // was hex(0xDADDE3)
	customProperty("--background-color-disabled", fillGrayTertiary) // was hex(0xDADDE3)
	customProperty("--background-color-disabled-subtle", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-inverted", glyph) // was hex(0x101418)
	customProperty("--background-color-progressive", fillBlue) // was hex(0x3366CC)
	customProperty("--background-color-progressive-hover", colorMix(in: .srgb, fillBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--background-color-progressive-active", colorMix(in: .srgb, fillBlue, (.black, perc(20)))) // was hex(0x233566)
	customProperty("--background-color-progressive-focus", fillBlue) // was hex(0x3366CC)
	customProperty("--background-color-progressive-subtle", fillBlueSecondary) // was hex(0xF1F4FD)
	customProperty("--background-color-progressive-subtle-hover", colorMix(in: .srgb, fillBlueSecondary, (fillBlue, perc(5)))) // was hex(0xD9E2FF)
	customProperty("--background-color-progressive-subtle-active", colorMix(in: .srgb, fillBlueSecondary, (fillBlue, perc(10)))) // was hex(0xB6D4FB)
	customProperty("--background-color-destructive", glyphRed) // was hex(0xBF3C2C) - solid bg uses fg
	customProperty("--background-color-destructive-hover", colorMix(in: .srgb, glyphRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--background-color-destructive-active", colorMix(in: .srgb, glyphRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--background-color-destructive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--background-color-destructive-subtle", fillRedSecondary) // was hex(0xFFE9E5)
	customProperty("--background-color-destructive-subtle-hover", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(5)))) // was hex(0xFFDAD3)
	customProperty("--background-color-destructive-subtle-active", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(10)))) // was hex(0xFFC8BD)
	customProperty("--background-color-error", fillRed) // was hex(0xF54739) - solid bg uses fg
	customProperty("--background-color-error-hover", colorMix(in: .srgb, fillRed, (.black, perc(10)))) // was hex(0xD74032)
	customProperty("--background-color-error-active", colorMix(in: .srgb, fillRed, (.black, perc(30)))) // was hex(0xBF3C2C)
	customProperty("--background-color-error-subtle", fillRedSecondary) // was hex(0xFFE9E5)
	customProperty("--background-color-error-subtle-hover", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(5)))) // was hex(0xFFDAD3)
	customProperty("--background-color-error-subtle-active", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(10)))) // was hex(0xFFC8BD)
	customProperty("--background-color-warning-subtle", fillYellowSecondary) // was hex(0xFDF2D5)
	customProperty("--background-color-success-subtle", fillGreenSecondary) // was hex(0xDFF2EB)
	customProperty("--background-color-notice-subtle", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-content-added", fillBlueSecondary) // was hex(0xA3D3FF)
	customProperty("--background-color-content-removed", fillYellowSecondary) // was hex(0xFFE49C)
	customProperty("--background-color-transparent", .transparent)
	customProperty("--background-color-backdrop-light", rgba(255, 255, 255, 0.65))
	customProperty("--background-color-backdrop-dark", rgba(0, 0, 0, 0.65))
	customProperty("--background-color-button-quiet-hover", rgba(0, 24, 73, 0.027))
	customProperty("--background-color-button-quiet-active", rgba(0, 24, 73, 0.082))
	customProperty("--background-color-input-binary--checked", glyphBlue) // was hex(0x3366CC)
	customProperty("--background-color-tab-list-item-framed-hover", rgba(255, 255, 255, 0.3))
	customProperty("--background-color-tab-list-item-framed-active", rgba(255, 255, 255, 0.65))
	customProperty("--opacity-icon-base", 0.87)
	customProperty("--opacity-icon-base-hover", 0.74)
	customProperty("--opacity-icon-base--selected", 1)
	customProperty("--opacity-icon-base--disabled", 0.51)
	customProperty("--opacity-icon-placeholder", 0.51)
	customProperty("--opacity-icon-subtle", 0.67)
	customProperty("--min-size-interactive-pointer", px(32))
	customProperty("--min-size-interactive-touch", px(44))
	customProperty("--min-size-search-figure", px(40))
	customProperty("--min-size-icon-x-small", px(10))
	customProperty("--min-size-icon-small", px(14))
	customProperty("--min-size-icon-medium", px(18))
	customProperty("--min-size-input-binary", px(20))
	customProperty("--min-size-input-chip-clear-button", px(20))
	customProperty("--min-size-toggle-switch-grip", px(18))
	customProperty("--min-width-medium", px(256))
	customProperty("--min-width-breakpoint-mobile", px(320))
	customProperty("--min-width-breakpoint-tablet", px(640))
	customProperty("--min-width-breakpoint-desktop", px(1120))
	customProperty("--min-width-breakpoint-desktop-wide", px(1680))
	customProperty("--min-width-toggle-switch", px(42))
	customProperty("--spacing-0", 0)
	customProperty("--spacing-1", px(1))
	customProperty("--spacing-2", px(2))
	customProperty("--spacing-4", px(4))
	customProperty("--spacing-5", px(5))
	customProperty("--spacing-6", px(6))
	customProperty("--spacing-8", px(8))
	customProperty("--spacing-10", px(10))
	customProperty("--spacing-12", px(12))
	customProperty("--spacing-16", px(16))
	customProperty("--spacing-20", px(20))
	customProperty("--spacing-24", px(24))
	customProperty("--spacing-32", px(32))
	customProperty("--spacing-40", px(40))
	customProperty("--spacing-48", px(48))
	customProperty("--spacing-64", px(64))
	customProperty("--spacing-half", perc(50))
	customProperty("--spacing-full", perc(100))
	customProperty("--border-width-base", px(1))
	customProperty("--border-width-thick", px(2))
	customProperty("--border-width-input-radio--checked", px(6))
	customProperty("--border-color-base", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--border-color-emphasized", glyphGray) // was hex(0x202122)
	customProperty("--border-color-subtle", fillGrayTertiary) // was hex(0xC8CCD1)
	customProperty("--border-color-muted", fillGrayTertiary) // was hex(0xDADDE3)
	customProperty("--border-color-interactive", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--border-color-interactive-hover", glyphGray) // was hex(0x27292D)
	customProperty("--border-color-interactive-active", glyphGray) // was hex(0x202122)
	customProperty("--border-color-disabled", fillGrayTertiary) // was hex(0xC8CCD1)
	customProperty("--border-color-inverted", fill) // was hex(0xFFFFFF)
	customProperty("--border-color-inverted-fixed", .white) // was hex(0xFFFFFF)
	customProperty("--border-color-progressive", glyphBlue) // was hex(0x6485D1)
	customProperty("--border-color-progressive-hover", colorMix(in: .srgb, glyphBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--border-color-progressive-active", colorMix(in: .srgb, glyphBlue, (.black, perc(30)))) // was hex(0x233566)
	customProperty("--border-color-progressive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--border-color-destructive", fillRed) // was hex(0xF54739)
	customProperty("--border-color-destructive-hover", colorMix(in: .srgb, fillRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--border-color-destructive-active", colorMix(in: .srgb, fillRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--border-color-destructive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--border-color-error", fillRed) // was hex(0xF54739)
	customProperty("--border-color-error-hover", colorMix(in: .srgb, fillRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--border-color-error-active", colorMix(in: .srgb, fillRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--border-color-warning", glyphOrange) // was hex(0xAB7F2A)
	customProperty("--border-color-warning-hover", colorMix(in: .srgb, glyphOrange, (.black, perc(10)))) // was hex(0x735421)
	customProperty("--border-color-warning-active", colorMix(in: .srgb, glyphOrange, (.black, perc(30)))) // was hex(0x453217)
	customProperty("--border-color-success", glyphGreen) // was hex(0x099979)
	customProperty("--border-color-notice", glyphGraySecondary) // was hex(0x72777D)
	customProperty("--border-color-content-added", fillBlueSecondary) // was hex(0xA3D3FF)
	customProperty("--border-color-content-removed", fillYellowSecondary) // was hex(0xFFE49C)
	customProperty("--border-color-transparent", .transparent)
	customProperty("--border-color-divider", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--border-radius-minimal", px(2))
	customProperty("--border-radius-base", px(8))
	customProperty("--border-radius-sharp", 0)
	customProperty("--border-radius-pill", px(9999))
	customProperty("--border-radius-circle", perc(50))
	customProperty("--outline-color-progressive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--min-height-text-area", px(64))
	customProperty("--min-height-table-header", px(40))
	customProperty("--min-height-table-footer", px(40))
	customProperty("--min-height-toggle-switch", px(28))
	customProperty("--max-height-chip", rem(1.375))
	customProperty("--color-link", colorProgressive)
	customProperty("--color-link-hover", colorProgressiveHover)
	customProperty("--color-link-active", colorProgressiveActive)
	customProperty("--color-link-focus", colorProgressiveFocus)
	customProperty("--color-link-visited", colorVisited)
	customProperty("--color-link-visited-hover", colorVisitedHover)
	customProperty("--color-link-visited-active", colorVisitedActive)
	customProperty("--color-link-red", colorDestructive)
	customProperty("--color-link-red-hover", colorDestructiveHover)
	customProperty("--color-link-red-active", colorDestructiveActive)
	customProperty("--color-link-red-focus", colorDestructiveFocus)
	customProperty("--color-link-red-visited", colorDestructiveVisited)
	customProperty("--color-link-red-visited-hover", colorDestructiveVisitedHover)
	customProperty("--color-link-red-visited-active", colorDestructiveVisitedActive)
	customProperty("--size-icon-x-small", calc(fontSizeMedium16 - px(4)))
	customProperty("--size-icon-small", fontSizeMedium16)
	customProperty("--size-icon-medium", calc(fontSizeMedium16 + px(4)))
	customProperty("--size-toggle-switch-grip", calc(fontSizeMedium16 * 1.25))
	customProperty("--box-shadow-small", (boxShadowOutsetSmall, boxShadowColorBase))
	customProperty("--box-shadow-small-top", (boxShadowOutsetSmallTop, boxShadowColorBase))
	customProperty("--box-shadow-small-bottom", (boxShadowOutsetSmallBottom, boxShadowColorBase))
	customProperty("--box-shadow-medium", ((boxShadowOutsetMediumBelow, boxShadowColorAlphaBase), (boxShadowOutsetMediumAround, boxShadowColorAlphaBase)))
	customProperty("--box-shadow-large", ((boxShadowOutsetLargeBelow, boxShadowColorAlphaBase), (boxShadowOutsetLargeAround, boxShadowColorAlphaBase)))
	customProperty("--accent-color-base", glyphBlue) // was hex(0x3366CC)
	customProperty("--position-offset-border-width-base", "-\(borderWidthBase)")
	customProperty("--spacing-horizontal-button", calc(spacing12 - borderWidthBase))
	customProperty("--spacing-horizontal-button-icon-only", calc(spacing6 - borderWidthBase))
	customProperty("--spacing-horizontal-button-small-icon-only", calc(spacing2 - borderWidthBase))
	customProperty("--spacing-horizontal-button-small", calc(spacing6 - borderWidthBase))
	customProperty("--spacing-horizontal-button-large", calc(spacing16 - borderWidthBase))
	customProperty("--spacing-horizontal-input-text-two-end-icons", calc(spacing8 * 2 + sizeIconSmall))
	customProperty("--spacing-start-typeahead-search-figure", spacing12)
	customProperty("--spacing-toggle-switch-grip-start", calc(fontSizeMedium16 * 0.375))
	customProperty("--spacing-toggle-switch-grip-end", calc(fontSizeMedium16 * 1.25))
	customProperty("--border-color-input-hover", borderColorInteractive)
	customProperty("--border-color-input-binary", borderColorInteractive)
	customProperty("--border-color-input-binary-hover", borderColorProgressiveHover)
	customProperty("--border-color-input-binary-active", borderColorProgressiveActive)
	customProperty("--border-color-input-binary-focus", borderColorProgressiveFocus)
	customProperty("--border-color-input-binary--checked", borderColorProgressive)
	customProperty("--border-base", (borderWidthBase, borderStyleBase, borderColorBase))
	customProperty("--border-subtle", (borderWidthBase, borderStyleBase, borderColorSubtle))
	customProperty("--border-progressive", (borderWidthBase, borderStyleBase, borderColorProgressive))
	customProperty("--border-destructive", (borderWidthBase, borderStyleBase, borderColorDestructive))
	customProperty("--border-transparent", (borderWidthBase, borderStyleBase, borderColorTransparent))
	customProperty("--outline-base-focus", (borderWidthBase, .solid, .transparent))
	customProperty("--width-toggle-switch", calc(fontSizeMedium16 * 3))
	customProperty("--height-toggle-switch", calc(fontSizeMedium16 * 2))
	customProperty("--spacing-start-typeahead-search-icon", calc(spacingStartTypeaheadSearchFigure + (minSizeSearchFigure - minSizeIconMedium) / 2))
	customProperty("--spacing-typeahead-search-focus-addition", calc((spacingStartTypeaheadSearchFigure + minSizeSearchFigure) - (minSizeIconMedium + spacing8)))
}

@CSSBuilder
public func AppliedTokensLightModeMoreContrastCSS() -> [any CSS] {
	customProperty("--color-base", glyph) // was hex(0x202122)
	customProperty("--color-base-fixed", glyphFixed) // was hex(0x202122)
	customProperty("--color-base-hover", glyphGraySecondary) // was hex(0x404244)
	customProperty("--color-emphasized", glyph) // was hex(0x101418)
	customProperty("--color-subtle", glyphGraySecondary) // was hex(0x54595D)
	customProperty("--color-placeholder", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--color-disabled", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--color-progressive", glyphBlue) // was hex(0x3366CC)
	customProperty("--color-progressive-hover", colorMix(in: .srgb, glyphBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--color-progressive-active", colorMix(in: .srgb, glyphBlue, (.black, perc(30)))) // was hex(0x233566)
	customProperty("--color-progressive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--color-destructive", glyphRed) // was hex(0xBF3C2C)
	customProperty("--color-destructive-hover", colorMix(in: .srgb, glyphRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--color-destructive-active", colorMix(in: .srgb, glyphRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--color-destructive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--color-visited", purpleLightLess) // was hex(0x6A60B0)
	customProperty("--color-visited-hover", colorMix(in: .srgb, purpleLightLess, (.black, perc(10)))) // was hex(0x534FA3)
	customProperty("--color-visited-active", colorMix(in: .srgb, purpleLightLess, (.black, perc(30)))) // was hex(0x353262)
	customProperty("--color-error", fillRed) // was hex(0xBF3C2C)
	customProperty("--color-error-hover", colorMix(in: .srgb, fillRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--color-error-active", colorMix(in: .srgb, fillRed, (.black, perc(30)))) // was hex(0x612419)
	customProperty("--color-warning", glyphOrange) // was hex(0x886425)
	customProperty("--color-success", glyphGreen) // was hex(0x177860)
	customProperty("--color-notice", glyphGraySecondary) // was hex(0x404244)

	customProperty("--background-color-base", fill) // was hex(0xFFFFFF)
	customProperty("--background-color-base-fixed", .white) // was hex(0xFFFFFF)
	customProperty("--background-color-neutral", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-neutral-subtle", fillSecondary) // was hex(0xF8F9FA)
	customProperty("--background-color-interactive", fillTertiary) // was hex(0xEAECF0)
	customProperty("--background-color-interactive-hover", fillGrayTertiary) // was hex(0xDADDE3)
	customProperty("--background-color-interactive-active", fillGraySecondary) // was hex(0xC8CCD1)
	customProperty("--background-color-inverted", glyph) // was hex(0x101418)
	customProperty("--background-color-progressive", fillBlue) // was hex(0x3366CC)
	customProperty("--background-color-progressive-hover", colorMix(in: .srgb, fillBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--background-color-progressive-active", colorMix(in: .srgb, fillBlue, (.black, perc(20)))) // was hex(0x233566)
	customProperty("--background-color-destructive", glyphRed) // was hex(0xBF3C2C)
	customProperty("--background-color-destructive-hover", colorMix(in: .srgb, glyphRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--background-color-destructive-active", colorMix(in: .srgb, glyphRed, (.black, perc(20)))) // was hex(0x612419)

	customProperty("--border-color-base", fillGrayTertiary) // was hex(0xA2A9B1)
	customProperty("--border-color-emphasized", glyphGray) // was hex(0x202122)
	customProperty("--border-color-subtle", fillGrayTertiary) // was hex(0xC8CCD1)
	customProperty("--border-color-interactive", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--border-color-interactive-hover", glyphGray) // was hex(0x27292D)
	customProperty("--border-color-interactive-active", glyphGray) // was hex(0x202122)
	customProperty("--border-color-progressive", glyphBlue) // was hex(0x6485D1)
	customProperty("--border-color-progressive-hover", colorMix(in: .srgb, glyphBlue, (.black, perc(10)))) // was hex(0x3056A9)
	customProperty("--border-color-progressive-active", colorMix(in: .srgb, glyphBlue, (.black, perc(20)))) // was hex(0x233566)
	customProperty("--border-color-progressive-focus", glyphBlue) // was hex(0x3366CC)
	customProperty("--border-color-destructive", fillRed) // was hex(0xF54739)
	customProperty("--border-color-destructive-hover", colorMix(in: .srgb, fillRed, (.black, perc(10)))) // was hex(0x9F3526)
	customProperty("--border-color-destructive-active", colorMix(in: .srgb, fillRed, (.black, perc(20)))) // was hex(0x612419)
}

// MARK: - Wikimedia Codex - Design Tokens - Dark Mode - Adapted for Apple HIG
@CSSBuilder
public func AppliedTokensDarkModeLessContrastCSS() -> [any CSS] {
	colorScheme(.dark).important()

	customProperty("--color-base", glyphGray) // was hex(0xEAECF0)
	customProperty("--color-base-hover", glyphGraySecondary) // was hex(0xF8F9FA)
	customProperty("--color-emphasized", glyph) // was hex(0xF8F9FA)
	customProperty("--color-subtle", glyphGraySecondary) // was hex(0xA2A9B1)
	customProperty("--color-disabled", glyphGrayTertiary) // was hex(0x54595D)
	customProperty("--color-disabled-emphasized", glyphGraySecondary) // was hex(0x72777D)
	customProperty("--color-inverted", fill) // was hex(0x101418)
	customProperty("--color-progressive", glyphBlue) // was hex(0x88A3E8)
	customProperty("--color-progressive-hover", colorMix(in: .srgb, glyphBlue, (.white, perc(10)))) // was hex(0xA6BBF5)
	customProperty("--color-progressive-active", colorMix(in: .srgb, glyphBlue, (.white, perc(30)))) // was hex(0xB6D4FB)
	customProperty("--color-destructive", glyphRed) // was hex(0xFD7865)
	customProperty("--color-destructive-hover", colorMix(in: .srgb, glyphRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--color-destructive-active", colorMix(in: .srgb, glyphRed, (.white, perc(30)))) // was hex(0xFFC8BD)
	customProperty("--color-visited", purpleLightLess) // was hex(0xA799CD)
	customProperty("--color-visited-hover", colorMix(in: .srgb, purpleLightLess, (.white, perc(10)))) // was hex(0xC5B9DD)
	customProperty("--color-visited-active", colorMix(in: .srgb, purpleLightLess, (.white, perc(30)))) // was hex(0xD9D0E9)
	customProperty("--color-destructive-visited", colorMix(in: .srgb, glyphRed, (.white, perc(10)))) // was hex(0xC99391)
	customProperty("--color-destructive-visited-hover", colorMix(in: .srgb, glyphRed, (.white, perc(20)))) // was hex(0xDCB5B3)
	customProperty("--color-destructive-visited-active", colorMix(in: .srgb, glyphRed, (.white, perc(40)))) // was hex(0xE8CECD)
	customProperty("--color-error", fillRed) // was hex(0xFD7865)
	customProperty("--color-error-hover", colorMix(in: .srgb, fillRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--color-error-active", colorMix(in: .srgb, fillRed, (.white, perc(30)))) // was hex(0xFFC8BD)
	customProperty("--color-warning", glyphOrange) // was hex(0xCA982E)
	customProperty("--color-success", glyphGreen) // was hex(0x2CB491)
	customProperty("--color-notice", glyphGraySecondary) // was hex(0xA2A9B1)
	customProperty("--color-content-added", glyphGreen) // was hex(0x80CDB3)
	customProperty("--color-content-removed", glyphRed) // was hex(0xFD7865)
	customProperty("--box-shadow-color-base", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--box-shadow-color-progressive-focus", glyphBlue) // was hex(0x6485D1)
	customProperty("--box-shadow-color-progressive-selected", glyphBlue) // was hex(0x88A3E8)
	customProperty("--box-shadow-color-progressive-selected-hover", colorMix(in: .srgb, glyphBlue, (.white, perc(10)))) // was hex(0xA6BBF5)
	customProperty("--box-shadow-color-progressive-selected-active", colorMix(in: .srgb, glyphBlue, (.white, perc(30)))) // was hex(0xB6D4FB)
	customProperty("--box-shadow-color-destructive-focus", glyphBlue) // was hex(0x6485D1)
	customProperty("--box-shadow-color-inverted", .black) // was hex(0x000000)
	customProperty("--box-shadow-color-alpha-base", rgba(0, 0, 0, 0.87))
	customProperty("--mix-blend-mode-blend", .screen)

	customProperty("--background-color-base", fill) // was hex(0x101418)
	customProperty("--background-color-neutral", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-neutral-subtle", fillSecondary) // was hex(0x202122)
	customProperty("--background-color-interactive", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-interactive-hover", fillGrayTertiary) // was hex(0x404244)
	customProperty("--background-color-interactive-active", fillGraySecondary) // was hex(0x54595D)
	customProperty("--background-color-interactive-subtle", fillSecondary) // was hex(0x202122)
	customProperty("--background-color-interactive-subtle-hover", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-interactive-subtle-active", fillGrayTertiary) // was hex(0x404244)
	customProperty("--background-color-disabled", fillGrayTertiary) // was hex(0x404244)
	customProperty("--background-color-disabled-subtle", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-inverted", glyph) // was hex(0xF8F9FA)
	customProperty("--background-color-progressive", fillBlue)
	customProperty("--background-color-progressive-hover", colorMix(in: .srgb, fillBlue, (.white, perc(10))))
	customProperty("--background-color-progressive-active", colorMix(in: .srgb, fillBlue, (.white, perc(20))))
	customProperty("--background-color-progressive-focus", fillBlue)
	customProperty("--background-color-progressive-subtle", fillBlueSecondary) // was hex(0x1B223D)
	customProperty("--background-color-progressive-subtle-hover", colorMix(in: .srgb, fillBlueSecondary, (fillBlue, perc(5)))) // was hex(0x233566)
	customProperty("--background-color-progressive-subtle-active", colorMix(in: .srgb, fillBlueSecondary, (fillBlue, perc(10)))) // was hex(0x3056A9)
	customProperty("--background-color-destructive", fillRed)
	customProperty("--background-color-destructive-hover", colorMix(in: .srgb, fillRed, (.white, perc(10))))
	customProperty("--background-color-destructive-active", colorMix(in: .srgb, fillRed, (.white, perc(20))))
	customProperty("--background-color-destructive-focus", fillBlue)
	customProperty("--background-color-destructive-subtle", fillRedSecondary) // was hex(0x3C1A13)
	customProperty("--background-color-destructive-subtle-hover", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(5)))) // was hex(0x612419)
	customProperty("--background-color-destructive-subtle-active", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(10)))) // was hex(0x9F3526)
	customProperty("--background-color-error-subtle", fillRedSecondary) // was hex(0x3C1A13)
	customProperty("--background-color-error-subtle-hover", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(5)))) // was hex(0x612419)
	customProperty("--background-color-error-subtle-active", colorMix(in: .srgb, fillRedSecondary, (fillRed, perc(10)))) // was hex(0x9F3526)
	customProperty("--background-color-warning-subtle", fillYellowSecondary) // was hex(0x2D2212)
	customProperty("--background-color-success-subtle", fillGreenSecondary) // was hex(0x132821)
	customProperty("--background-color-notice-subtle", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-content-added", fillGreenSecondary) // was hex(0x233566)
	customProperty("--background-color-content-removed", fillRedSecondary) // was hex(0x453217)
	customProperty("--background-color-backdrop-light", rgba(0, 0, 0, 0.65))
	customProperty("--background-color-backdrop-dark", rgba(255, 255, 255, 0.65))
	customProperty("--border-color-base", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--border-color-emphasized", glyph) // was hex(0xEAECF0)
	customProperty("--border-color-subtle", glyphGrayTertiary) // was hex(0x54595D)
	customProperty("--border-color-muted", fillGrayTertiary) // was hex(0x404244)
	customProperty("--border-color-interactive-hover", glyphGraySecondary) // was hex(0xA2A9B1)
	customProperty("--border-color-interactive-active", glyphGraySecondary) // was hex(0xC8CCD1)
	customProperty("--border-color-disabled", glyphGrayTertiary) // was hex(0x54595D)
	customProperty("--border-color-inverted", fill) // was hex(0x101418)
	customProperty("--border-color-progressive-hover", glyphBlue) // was hex(0x88A3E8)
	customProperty("--border-color-progressive-active", colorMix(in: .srgb, glyphBlue, (.white, perc(10)))) // was hex(0xA6BBF5)
	customProperty("--border-color-progressive-focus", glyphBlue) // was hex(0x6485D1)
	customProperty("--border-color-destructive-hover", glyphRed) // was hex(0xFD7865)
	customProperty("--border-color-destructive-active", colorMix(in: .srgb, glyphRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--border-color-destructive-focus", glyphBlue) // was hex(0x6485D1)
	customProperty("--border-color-error-hover", fillRed) // was hex(0xFD7865)
	customProperty("--border-color-error-active", colorMix(in: .srgb, fillRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--border-color-warning-hover", glyphOrange) // was hex(0xCA982E)
	customProperty("--border-color-warning-active", colorMix(in: .srgb, glyphOrange, (.white, perc(10)))) // was hex(0xEDB537)
	customProperty("--border-color-content-added", glyphGreen) // was hex(0x233566)
	customProperty("--border-color-content-removed", glyphRed) // was hex(0x987027)
}

@CSSBuilder
public func AppliedTokensDarkModeMoreContrastCSS() -> [any CSS] {
	customProperty("--color-base", glyph) // was hex(0xEAECF0)
	customProperty("--color-base-hover", glyphGraySecondary) // was hex(0xF8F9FA)
	customProperty("--color-emphasized", glyph) // was hex(0xF8F9FA)
	customProperty("--color-subtle", glyphGraySecondary) // was hex(0xA2A9B1)
	customProperty("--color-disabled", glyphGrayTertiary) // was hex(0x54595D)
	customProperty("--color-progressive", glyphBlue) // was hex(0x88A3E8)
	customProperty("--color-progressive-hover", colorMix(in: .srgb, glyphBlue, (.white, perc(10)))) // was hex(0xA6BBF5)
	customProperty("--color-progressive-active", colorMix(in: .srgb, glyphBlue, (.white, perc(30)))) // was hex(0xB6D4FB)
	customProperty("--color-destructive", glyphRed) // was hex(0xFD7865)
	customProperty("--color-destructive-hover", colorMix(in: .srgb, glyphRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--color-destructive-active", colorMix(in: .srgb, glyphRed, (.white, perc(30)))) // was hex(0xFFC8BD)
	customProperty("--color-visited", purpleLightLess) // was hex(0xA799CD)
	customProperty("--color-visited-hover", colorMix(in: .srgb, purpleLightLess, (.white, perc(10)))) // was hex(0xC5B9DD)
	customProperty("--color-visited-active", colorMix(in: .srgb, purpleLightLess, (.white, perc(30)))) // was hex(0xD9D0E9)
	customProperty("--color-error", fillRed) // was hex(0xFD7865)
	customProperty("--color-error-hover", colorMix(in: .srgb, fillRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--color-error-active", colorMix(in: .srgb, fillRed, (.white, perc(30)))) // was hex(0xFFC8BD)
	customProperty("--color-warning", glyphOrange) // was hex(0xCA982E)
	customProperty("--color-success", glyphGreen) // was hex(0x2CB491)
	customProperty("--color-notice", glyphGraySecondary) // was hex(0xA2A9B1)
	customProperty("--color-inverted", fill) // was hex(0x101418)

	customProperty("--background-color-base", fill) // was hex(0x101418)
	customProperty("--background-color-neutral", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-neutral-subtle", fillSecondary) // was hex(0x202122)
	customProperty("--background-color-interactive", fillTertiary) // was hex(0x27292D)
	customProperty("--background-color-interactive-hover", fillGrayTertiary) // was hex(0x404244)
	customProperty("--background-color-interactive-active", fillGraySecondary) // was hex(0x54595D)
	customProperty("--background-color-inverted", glyph) // was hex(0xF8F9FA)
	customProperty("--background-color-progressive", fillBlue) // was hex(0x6485D1)
	customProperty("--background-color-progressive-hover", colorMix(in: .srgb, fillBlue, (.white, perc(10)))) // was hex(0x88A3E8)
	customProperty("--background-color-progressive-active", colorMix(in: .srgb, fillBlue, (.white, perc(20)))) // was hex(0xA6BBF5)
	customProperty("--background-color-progressive-focus", fillBlue) // was hex(0x6485D1)
	customProperty("--background-color-destructive", fillRed) // was hex(0xF54739)
	customProperty("--background-color-destructive-hover", colorMix(in: .srgb, fillRed, (.white, perc(10)))) // was hex(0xFD7865)
	customProperty("--background-color-destructive-active", colorMix(in: .srgb, fillRed, (.white, perc(20)))) // was hex(0xFEA898)
	customProperty("--background-color-destructive-focus", fillBlue) // was hex(0x6485D1)

	customProperty("--border-color-base", glyphGrayTertiary) // was hex(0x72777D)
	customProperty("--border-color-emphasized", glyph) // was hex(0xEAECF0)
	customProperty("--border-color-subtle", glyphGrayTertiary) // was hex(0x54595D)
	customProperty("--border-color-interactive-hover", glyphGraySecondary) // was hex(0xA2A9B1)
	customProperty("--border-color-interactive-active", glyphGraySecondary) // was hex(0xC8CCD1)
	customProperty("--border-color-progressive-hover", glyphBlue) // was hex(0x88A3E8)
	customProperty("--border-color-progressive-active", colorMix(in: .srgb, glyphBlue, (.white, perc(10)))) // was hex(0xA6BBF5)
	customProperty("--border-color-progressive-focus", glyphBlue) // was hex(0x6485D1)
	customProperty("--border-color-destructive-hover", glyphRed) // was hex(0xFD7865)
	customProperty("--border-color-destructive-active", colorMix(in: .srgb, glyphRed, (.white, perc(10)))) // was hex(0xFEA898)
	customProperty("--border-color-destructive-focus", glyphBlue) // was hex(0x6485D1)
}

#endif
