import WebTypes

// MARK: - Typography
public let typographyFontSans: CSS.FontFamily = `var`("--typography-font-sans")
public let typographyFontSansItalic: CSS.FontFamily = `var`("--typography-font-sans-italic")
public let typographyFontSerif: CSS.FontFamily = `var`("--typography-font-serif")
public let typographyFontSerifItalic: CSS.FontFamily = `var`("--typography-font-serif-italic")
public let typographyFontMono: CSS.FontFamily = `var`("--typography-font-mono")

// MARK: - Extreme Colors
public let extreme: CSS.Color = `var`("--extreme")
public let extremeInverted: CSS.Color = `var`("--extreme-inverted")

// MARK: - OKLCH Lightness Values (Apple HIG)
public let lightnessRed: CSS.Value = `var`("--lightness-red")
public let lightnessOrange: CSS.Value = `var`("--lightness-orange")
public let lightnessYellow: CSS.Value = `var`("--lightness-yellow")
public let lightnessGreen: CSS.Value = `var`("--lightness-green")
public let lightnessMint: CSS.Value = `var`("--lightness-mint")
public let lightnessTeal: CSS.Value = `var`("--lightness-teal")
public let lightnessCyan: CSS.Value = `var`("--lightness-cyan")
public let lightnessBlue: CSS.Value = `var`("--lightness-blue")
public let lightnessIndigo: CSS.Value = `var`("--lightness-indigo")
public let lightnessPurple: CSS.Value = `var`("--lightness-purple")
public let lightnessPink: CSS.Value = `var`("--lightness-pink")
public let lightnessBrown: CSS.Value = `var`("--lightness-brown")
public let lightnessGray: CSS.Value = `var`("--lightness-gray")

public let chromaRed: CSS.Value = `var`("--chroma-red")
public let chromaOrange: CSS.Value = `var`("--chroma-orange")
public let chromaYellow: CSS.Value = `var`("--chroma-yellow")
public let chromaGreen: CSS.Value = `var`("--chroma-green")
public let chromaMint: CSS.Value = `var`("--chroma-mint")
public let chromaTeal: CSS.Value = `var`("--chroma-teal")
public let chromaCyan: CSS.Value = `var`("--chroma-cyan")
public let chromaBlue: CSS.Value = `var`("--chroma-blue")
public let chromaIndigo: CSS.Value = `var`("--chroma-indigo")
public let chromaPurple: CSS.Value = `var`("--chroma-purple")
public let chromaPink: CSS.Value = `var`("--chroma-pink")
public let chromaBrown: CSS.Value = `var`("--chroma-brown")
public let chromaGray: CSS.Value = `var`("--chroma-gray")

// MARK: - OKLCH Hue Angles (Apple HIG)
// Each hue's glyph/fill tokens are set to the absolute sRGB gamut peak.
// Mode functions can override --glyph-{hue}/--fill-{hue} with srgbMaxChroma(l:h:).
public let hueRed: CSS.Value = `var`("--hue-red")
public let hueOrange: CSS.Value = `var`("--hue-orange")
public let hueYellow: CSS.Value = `var`("--hue-yellow")
public let hueGreen: CSS.Value = `var`("--hue-green")
public let hueMint: CSS.Value = `var`("--hue-mint")
public let hueTeal: CSS.Value = `var`("--hue-teal")
public let hueCyan: CSS.Value = `var`("--hue-cyan")
public let hueBlue: CSS.Value = `var`("--hue-blue")
public let hueIndigo: CSS.Value = `var`("--hue-indigo")
public let huePurple: CSS.Value = `var`("--hue-purple")
public let huePink: CSS.Value = `var`("--hue-pink")
public let hueBrown: CSS.Value = `var`("--hue-brown")
public let hueGray: CSS.Value = `var`("--hue-gray")

// MARK: - Source: Hue Colors (glyph = foreground, fill = background)
// Pattern: {tier}{Hue} — e.g. glyphRed, fillIndigo (gray remains grayGlyph/grayFill to avoid collision)
public let glyphRed: CSS.Color = `var`("--glyph-red")
public let fillRed: CSS.Color = `var`("--fill-red")
public let glyphOrange: CSS.Color = `var`("--glyph-orange")
public let fillOrange: CSS.Color = `var`("--fill-orange")
public let glyphYellow: CSS.Color = `var`("--glyph-yellow")
public let fillYellow: CSS.Color = `var`("--fill-yellow")
public let glyphGreen: CSS.Color = `var`("--glyph-green")
public let fillGreen: CSS.Color = `var`("--fill-green")
public let glyphMint: CSS.Color = `var`("--glyph-mint")
public let fillMint: CSS.Color = `var`("--fill-mint")
public let glyphTeal: CSS.Color = `var`("--glyph-teal")
public let fillTeal: CSS.Color = `var`("--fill-teal")
public let glyphCyan: CSS.Color = `var`("--glyph-cyan")
public let fillCyan: CSS.Color = `var`("--fill-cyan")
public let glyphBlue: CSS.Color = `var`("--glyph-blue")
public let fillBlue: CSS.Color = `var`("--fill-blue")
public let glyphIndigo: CSS.Color = `var`("--glyph-indigo")
public let fillIndigo: CSS.Color = `var`("--fill-indigo")
public let glyphPurple: CSS.Color = `var`("--glyph-purple")
public let fillPurple: CSS.Color = `var`("--fill-purple")
public let glyphPink: CSS.Color = `var`("--glyph-pink")
public let fillPink: CSS.Color = `var`("--fill-pink")
public let glyphBrown: CSS.Color = `var`("--glyph-brown")
public let fillBrown: CSS.Color = `var`("--fill-brown")
public let grayGlyph: CSS.Color = `var`("--gray-glyph")
public let grayFill: CSS.Color = `var`("--gray-fill")
public let trafficLightRed: CSS.Color = `var`("--traffic-light-red")
public let trafficLightYellow: CSS.Color = `var`("--traffic-light-yellow")
public let trafficLightGreen: CSS.Color = `var`("--traffic-light-green")

// MARK: - Source: Fill
public let fill: CSS.Color = `var`("--fill")
public let fillAlpha: CSS.Color = `var`("--fill-alpha")
public let fillSecondary: CSS.Color = `var`("--fill-secondary")
public let fillTertiary: CSS.Color = `var`("--fill-tertiary")
public let fillTertiaryAlpha: CSS.Color = `var`("--fill-tertiary-alpha")
public let fillQuaternaryAlpha: CSS.Color = `var`("--fill-quaternary-alpha")
public let fillGray: CSS.Color = `var`("--fill-gray")
public let fillGrayAlpha: CSS.Color = `var`("--fill-gray-alpha")
public let fillGrayHover: CSS.Color = `var`("--fill-gray-hover")
public let fillGrayActive: CSS.Color = `var`("--fill-gray-active")
public let fillGraySecondary: CSS.Color = `var`("--fill-gray-secondary")
public let fillGraySecondaryAlpha: CSS.Color = `var`("--fill-gray-secondary-alpha")
public let fillGrayTertiary: CSS.Color = `var`("--fill-gray-tertiary")
public let fillGrayTertiaryAlpha: CSS.Color = `var`("--fill-gray-tertiary-alpha")
public let fillGrayQuaternary: CSS.Color = `var`("--fill-gray-quaternary")
public let fillGrayQuaternaryAlpha: CSS.Color = `var`("--fill-gray-quaternary-alpha")

// MARK: - Source: Glyph
public let glyph: CSS.Color = `var`("--glyph")
public let glyphFixed: CSS.Color = `var`("--glyph-fixed")
public let glyphGray: CSS.Color = `var`("--glyph-gray")
public let glyphGrayAlpha: CSS.Color = `var`("--glyph-gray-alpha")
public let glyphGrayFixed: CSS.Color = `var`("--glyph-gray-fixed")
public let glyphGraySecondary: CSS.Color = `var`("--glyph-gray-secondary")
public let glyphGraySecondaryAlpha: CSS.Color = `var`("--glyph-gray-secondary-alpha")
public let glyphGraySecondaryAlt: CSS.Color = `var`("--glyph-gray-secondary-alt")
public let glyphGraySecondaryAltAlpha: CSS.Color = `var`("--glyph-gray-secondary-alt-alpha")
public let glyphGrayTertiary: CSS.Color = `var`("--glyph-gray-tertiary")
public let glyphGrayTertiaryAlpha: CSS.Color = `var`("--glyph-gray-tertiary-alpha")
public let glyphGrayQuaternary: CSS.Color = `var`("--glyph-gray-quaternary")
public let glyphGrayQuaternaryAlpha: CSS.Color = `var`("--glyph-gray-quaternary-alpha")

// MARK: - Source: Semantic Bridge (unified applied function)
public let border: CSS.Color = `var`("--border")
public let borderSecondary: CSS.Color = `var`("--border-secondary")
public let borderMuted: CSS.Color = `var`("--border-muted")
public let borderEmphasis: CSS.Color = `var`("--border-emphasis")
public let borderInteractive: CSS.Color = `var`("--border-interactive")
public let shadowAlpha: CSS.Color = `var`("--shadow-alpha")
public let backdropLight: CSS.Color = `var`("--backdrop-light")
public let backdropDark: CSS.Color = `var`("--backdrop-dark")

// MARK: - Source: Background Layers (Dark Mode)
public let backgroundPrimary: CSS.Color = `var`("--background-primary")
public let backgroundLayer1: CSS.Color = `var`("--background-layer1")
public let backgroundLayer2: CSS.Color = `var`("--background-layer2")
public let backdrop: CSS.Color = `var`("--backdrop")
public let sidebar: CSS.Color = `var`("--sidebar")
public let separator: CSS.Color = `var`("--separator")

// MARK: - Applied: Text/Foreground
public let colorBase: CSS.Color = `var`("--color-base")
public let colorBaseFixed: CSS.Color = `var`("--color-base-fixed")
public let colorBaseHover: CSS.Color = `var`("--color-base-hover")
public let colorBaseActive: CSS.Color = `var`("--color-base-active")
public let colorEmphasized: CSS.Color = `var`("--color-emphasized")
public let colorSubtle: CSS.Color = `var`("--color-subtle")
public let colorDisabled: CSS.Color = `var`("--color-disabled")
public let colorDisabledEmphasized: CSS.Color = `var`("--color-disabled-emphasized")
public let colorPlaceholder: CSS.Color = `var`("--color-placeholder")
public let colorInverted: CSS.Color = `var`("--color-inverted")
public let colorInvertedFixed: CSS.Color = `var`("--color-inverted-fixed")

// MARK: - Applied: Content Diff
public let colorContentAdded: CSS.Color = `var`("--color-content-added")
public let colorContentRemoved: CSS.Color = `var`("--color-content-removed")

// MARK: - Applied: HIG Component Colors (Foreground)
// Hue order: red, orange, yellow, green, mint, teal, cyan, blue, indigo, purple, pink, brown, gray
public let colorRed: CSS.Color = `var`("--color-red")
public let colorRedHover: CSS.Color = `var`("--color-red-hover")
public let colorRedActive: CSS.Color = `var`("--color-red-active")
public let colorRedFocus: CSS.Color = `var`("--color-red-focus")
public let colorOrange: CSS.Color = `var`("--color-orange")
public let colorOrangeHover: CSS.Color = `var`("--color-orange-hover")
public let colorOrangeActive: CSS.Color = `var`("--color-orange-active")
public let colorOrangeFocus: CSS.Color = `var`("--color-orange-focus")
public let colorYellow: CSS.Color = `var`("--color-yellow")
public let colorYellowHover: CSS.Color = `var`("--color-yellow-hover")
public let colorYellowActive: CSS.Color = `var`("--color-yellow-active")
public let colorYellowFocus: CSS.Color = `var`("--color-yellow-focus")
public let colorGreen: CSS.Color = `var`("--color-green")
public let colorGreenHover: CSS.Color = `var`("--color-green-hover")
public let colorGreenActive: CSS.Color = `var`("--color-green-active")
public let colorGreenFocus: CSS.Color = `var`("--color-green-focus")
public let colorMint: CSS.Color = `var`("--color-mint")
public let colorMintHover: CSS.Color = `var`("--color-mint-hover")
public let colorMintActive: CSS.Color = `var`("--color-mint-active")
public let colorMintFocus: CSS.Color = `var`("--color-mint-focus")
public let colorTeal: CSS.Color = `var`("--color-teal")
public let colorTealHover: CSS.Color = `var`("--color-teal-hover")
public let colorTealActive: CSS.Color = `var`("--color-teal-active")
public let colorTealFocus: CSS.Color = `var`("--color-teal-focus")
public let colorCyan: CSS.Color = `var`("--color-cyan")
public let colorCyanHover: CSS.Color = `var`("--color-cyan-hover")
public let colorCyanActive: CSS.Color = `var`("--color-cyan-active")
public let colorCyanFocus: CSS.Color = `var`("--color-cyan-focus")
public let colorBlue: CSS.Color = `var`("--color-blue")
public let colorBlueHover: CSS.Color = `var`("--color-blue-hover")
public let colorBlueActive: CSS.Color = `var`("--color-blue-active")
public let colorBlueFocus: CSS.Color = `var`("--color-blue-focus")
public let colorIndigo: CSS.Color = `var`("--color-indigo")
public let colorIndigoHover: CSS.Color = `var`("--color-indigo-hover")
public let colorIndigoActive: CSS.Color = `var`("--color-indigo-active")
public let colorIndigoFocus: CSS.Color = `var`("--color-indigo-focus")
public let colorPurple: CSS.Color = `var`("--color-purple")
public let colorPurpleHover: CSS.Color = `var`("--color-purple-hover")
public let colorPurpleActive: CSS.Color = `var`("--color-purple-active")
public let colorPurpleFocus: CSS.Color = `var`("--color-purple-focus")
public let colorPink: CSS.Color = `var`("--color-pink")
public let colorPinkHover: CSS.Color = `var`("--color-pink-hover")
public let colorPinkActive: CSS.Color = `var`("--color-pink-active")
public let colorPinkFocus: CSS.Color = `var`("--color-pink-focus")
public let colorBrown: CSS.Color = `var`("--color-brown")
public let colorBrownHover: CSS.Color = `var`("--color-brown-hover")
public let colorBrownActive: CSS.Color = `var`("--color-brown-active")
public let colorBrownFocus: CSS.Color = `var`("--color-brown-focus")
public let colorGray: CSS.Color = `var`("--color-gray")
public let colorGrayHover: CSS.Color = `var`("--color-gray-hover")
public let colorGrayActive: CSS.Color = `var`("--color-gray-active")
public let colorGrayFocus: CSS.Color = `var`("--color-gray-focus")

// MARK: - Source: Fill Parametric Parameters
public let fillL: CSS.Value = `var`("--fill-l")
public let fillLOffset: CSS.Value = `var`("--fill-l-offset")
public let fillLHover: CSS.Value = `var`("--fill-l-hover")
public let fillLActive: CSS.Value = `var`("--fill-l-active")
public let fillCScale: CSS.Value = `var`("--fill-c-scale")
public let fillCMult: CSS.Value = `var`("--fill-c-mult")
public let glyphLHoverOffset: CSS.Value = `var`("--glyph-l-hover-offset")
public let glyphLActiveOffset: CSS.Value = `var`("--glyph-l-active-offset")

// MARK: - Applied: Opacity
public let opacityBase: CSS.Number = `var`("--opacity-base")
public let opacityMedium: CSS.Number = `var`("--opacity-medium")
public let opacityLow: CSS.Number = `var`("--opacity-low")
public let opacityTransparent: CSS.Number = `var`("--opacity-transparent")
public let filterInvertIcon: CSS.Number = `var`("--filter-invert-icon")
public let filterInvertPrimaryButtonIcon: CSS.Number = `var`("--filter-invert-primary-button-icon")

// MARK: - Applied: Layout
public let backgroundPositionBase: CSS.BackgroundPosition = `var`("--background-position-base")
public let backgroundSizeSearchFigure: CSS.BackgroundSize = `var`("--background-size-search-figure")
public let zIndexBottom: CSS.Number = `var`("--z-index-bottom")
public let zIndexBase: CSS.Number = `var`("--z-index-base")
public let zIndexAboveContent: CSS.Number = `var`("--z-index-above-content")
public let zIndexToolbar: CSS.Number = `var`("--z-index-toolbar")
public let zIndexDropdown: CSS.Number = `var`("--z-index-dropdown")
public let zIndexSticky: CSS.Number = `var`("--z-index-sticky")
public let zIndexFixed: CSS.Number = `var`("--z-index-fixed")
public let zIndexOffCanvasBackdrop: CSS.Number = `var`("--z-index-off-canvas-backdrop")
public let zIndexOffCanvas: CSS.Number = `var`("--z-index-off-canvas")
public let zIndexOverlayBackdrop: CSS.Number = `var`("--z-index-overlay-backdrop")
public let zIndexOverlay: CSS.Number = `var`("--z-index-overlay")
public let zIndexPopover: CSS.Number = `var`("--z-index-popover")
public let zIndexTooltip: CSS.Number = `var`("--z-index-tooltip")
public let zIndexToastNotification: CSS.Number = `var`("--z-index-toast-notification")
public let zIndexTop: CSS.Number = `var`("--z-index-top")
public let zIndexStacking0: CSS.Number = `var`("--z-index-stacking-0")
public let zIndexStacking1: CSS.Number = `var`("--z-index-stacking-1")
public let zIndexStacking2: CSS.Number = `var`("--z-index-stacking-2")
public let zIndexStacking3: CSS.Number = `var`("--z-index-stacking-3")
public let boxSizingBase: CSS.BoxSizing = `var`("--box-sizing-base")

// MARK: - Applied: Sizing
public let size0: CSS.Length = `var`("--size-0")
public let size1: CSS.Length = `var`("--size-1")
public let size2: CSS.Length = `var`("--size-2")
public let size4: CSS.Length = `var`("--size-4")
public let size8: CSS.Length = `var`("--size-8")
public let size12: CSS.Length = `var`("--size-12")
public let size16: CSS.Length = `var`("--size-16")
public let size20: CSS.Length = `var`("--size-20")
public let size24: CSS.Length = `var`("--size-24")
public let size32: CSS.Length = `var`("--size-32")
public let size40: CSS.Length = `var`("--size-40")
public let size44: CSS.Length = `var`("--size-44")
public let size48: CSS.Length = `var`("--size-48")
public let size64: CSS.Length = `var`("--size-64")
public let size128: CSS.Length = `var`("--size-128")
public let size192: CSS.Length = `var`("--size-192")
public let size256: CSS.Length = `var`("--size-256")
public let size384: CSS.Length = `var`("--size-384")
public let size448: CSS.Length = `var`("--size-448")
public let size512: CSS.Length = `var`("--size-512")
public let size640: CSS.Length = `var`("--size-640")
public let size896: CSS.Length = `var`("--size-896")
public let sizeViewportWidthFull: CSS.Length = `var`("--size-viewport-width-full")
public let sizeViewportHeightFull: CSS.Length = `var`("--size-viewport-height-full")
public let sizeAbsolute1: CSS.Length = `var`("--size-absolute-1")
public let sizeAbsolute9999: CSS.Length = `var`("--size-absolute-9999")
public let sizeContentMin: CSS.Length = `var`("--size-content-min")
public let sizeContentFit: CSS.Length = `var`("--size-content-fit")
public let sizeContentMax: CSS.Length = `var`("--size-content-max")
public let sizeThird: CSS.Percentage = `var`("--size-third")
public let sizeHalf: CSS.Percentage = `var`("--size-half")
public let sizeFull: CSS.Percentage = `var`("--size-full")
public let sizeDouble: CSS.Percentage = `var`("--size-double")
public let sizeSearchFigure: CSS.Length = `var`("--size-search-figure")
public let maxWidthBase: CSS.Length = `var`("--max-width-base")
// Breakpoints use raw px() values, not CSSContent variables — media queries don't support var()
public let maxWidthBreakpointPhoneNarrow: CSS.Length = px(479)  // NEW
public let maxWidthBreakpointMobile: CSS.Length = px(768)
public let maxWidthBreakpointTablet: CSS.Length = px(1024)
public let maxWidthBreakpointDesktop: CSS.Length = px(1279)
public let maxWidthButton: CSS.Length = `var`("--max-width-button")

// MARK: - Applied: Borders & Shadows
public let borderStyleBase: CSS.Border.LineStyle = `var`("--border-style-base")
public let borderStyleDashed: CSS.Border.LineStyle = `var`("--border-style-dashed")
public let boxShadowInsetSmall: CSS.SpreadShadow = `var`("--box-shadow-inset-small")
public let boxShadowInsetMedium: CSS.SpreadShadow = `var`("--box-shadow-inset-medium")
public let boxShadowInsetMediumVertical: CSS.SpreadShadow = `var`(
  "--box-shadow-inset-medium-vertical")
public let boxShadowOutsetSmall: CSS.SpreadShadow = `var`("--box-shadow-outset-small")
public let boxShadowOutsetSmallTop: CSS.SpreadShadow = `var`("--box-shadow-outset-small-top")
public let boxShadowOutsetSmallBottom: CSS.SpreadShadow = `var`("--box-shadow-outset-small-bottom")
public let boxShadowOutsetSmallStart: CSS.SpreadShadow = `var`("--box-shadow-outset-small-start")
public let boxShadowOutsetMediumBelow: CSS.SpreadShadow = `var`("--box-shadow-outset-medium-below")
public let boxShadowOutsetMediumAround: CSS.SpreadShadow = `var`("--box-shadow-outset-medium-around")
public let boxShadowOutsetLargeBelow: CSS.SpreadShadow = `var`("--box-shadow-outset-large-below")
public let boxShadowOutsetLargeAround: CSS.SpreadShadow = `var`("--box-shadow-outset-large-around")
public let boxShadowColorBase: CSS.Color = `var`("--box-shadow-color-base")
public let boxShadowColorInverted: CSS.Color = `var`("--box-shadow-color-inverted")
public let boxShadowColorAlphaBase: CSS.Color = `var`("--box-shadow-color-alpha-base")
public let boxShadowColorTransparent: CSS.Color = `var`("--box-shadow-color-transparent")

// MARK: - Applied: Typography
public let fontFamilyBase: CSS.FontFamily = `var`("--font-family-base")
public let fontFamilySystemSans: CSS.FontFamily = `var`("--font-family-system-sans")
public let fontFamilyEmoji: CSS.FontFamily = `var`("--font-family-emoji")
public let fontFamilySansFallback: CSS.FontFamily = `var`("--font-family-sans--fallback")
public let fontFamilySerif: CSS.FontFamily = `var`("--font-family-serif")
public let fontFamilySerifFallback: CSS.FontFamily = `var`("--font-family-serif--fallback")
public let fontFamilyMonospace: CSS.FontFamily = `var`("--font-family-monospace")
public let fontFamilyMonospaceFallback: CSS.FontFamily = `var`("--font-family-monospace--fallback")
public let fontFamilyHeadingMain: CSS.FontFamily = `var`("--font-family-heading-main")
public let fontSizeXSmall12: CSS.Length = `var`("--font-size-x-small-12")
public let fontSizeSmall14: CSS.Length = `var`("--font-size-small-14")
public let fontSizeMedium16: CSS.Length = `var`("--font-size-medium-16")
public let fontSizeLarge18: CSS.Length = `var`("--font-size-large-18")
public let fontSizeXLarge20: CSS.Length = `var`("--font-size-x-large-20")
public let fontSizeXXLarge24: CSS.Length = `var`("--font-size-xx-large-24")
public let fontSizeXXXLarge28: CSS.Length = `var`("--font-size-xxx-large-28")
public let fontWeightHairline: CSS.FontWeight = `var`("--font-weight-hairline")
public let fontWeightLight: CSS.FontWeight = `var`("--font-weight-light")
public let fontWeightNormal: CSS.FontWeight = `var`("--font-weight-normal")
public let fontWeightSemiBold: CSS.FontWeight = `var`("--font-weight-semi-bold")
public let fontWeightBold: CSS.FontWeight = `var`("--font-weight-bold")
public let lineHeightXSmall20: CSS.Length = `var`("--line-height-x-small-20")
public let lineHeightSmall22: CSS.Length = `var`("--line-height-small-22")
public let lineHeightMedium26: CSS.Length = `var`("--line-height-medium-26")
public let lineHeightLarge28: CSS.Length = `var`("--line-height-large-28")
public let lineHeightXLarge30: CSS.Length = `var`("--line-height-x-large-30")
public let lineHeightXXLarge34: CSS.Length = `var`("--line-height-xx-large-34")
public let lineHeightXXXLarge38: CSS.Length = `var`("--line-height-xxx-large-38")
public let lineHeightContent: CSS.Length = `var`("--line-height-content")
public let textDecorationNone: CSS.TextDecoration = `var`("--text-decoration-none")
public let textDecorationLineThrough: CSS.TextDecoration = `var`("--text-decoration-line-through")
public let textDecorationUnderline: CSS.TextDecoration = `var`("--text-decoration-underline")
public let textOverflowClip: CSS.TextOverflow = `var`("--text-overflow-clip")
public let textOverflowEllipsis: CSS.TextOverflow = `var`("--text-overflow-ellipsis")
public let tabSizeBase: CSS.Number = `var`("--tab-size-base")
public let transformCheckboxTickChecked: CSS.TransformFunction = `var`(
  "--transform-checkbox-tick-checked")
public let transformRotatingSectorStart: CSS.TransformFunction = `var`(
  "--transform-rotating-sector-start")
public let transformRotatingSectorEnd: CSS.TransformFunction = `var`(
  "--transform-rotating-sector-end")
public let transitionDurationBase: CSS.Time = `var`("--transition-duration-base")
public let transitionDurationMedium: CSS.Time = `var`("--transition-duration-medium")
public let transitionPropertyBase: CSS.SingleTransitionProperty = `var`("--transition-property-base")
public let transitionPropertyFade: CSS.SingleTransitionProperty = `var`("--transition-property-fade")
public let transitionPropertyIcon: CSS.SingleTransitionProperty = `var`("--transition-property-icon")
public let transitionPropertyIconCssOnly: CSS.SingleTransitionProperty = `var`(
  "--transition-property-icon-css-only")
public let transitionPropertyToggleSwitchGrip: CSS.SingleTransitionProperty = `var`(
  "--transition-property-toggle-switch-grip")
public let transitionTimingFunctionSystem: CSS.EasingFunction = `var`(
  "--transition-timing-function-system")
public let transitionTimingFunctionUser: CSS.EasingFunction = `var`(
  "--transition-timing-function-user")

// MARK: - Applied: Animations
public let animationDelayNone: CSS.Time = `var`("--animation-delay-none")
public let animationDelayMedium: CSS.Time = `var`("--animation-delay-medium")
public let animationDelaySlow: CSS.Time = `var`("--animation-delay-slow")
public let animationDurationFast: CSS.Time = `var`("--animation-duration-fast")
public let animationDurationMedium: CSS.Time = `var`("--animation-duration-medium")
public let animationDurationSlow: CSS.Time = `var`("--animation-duration-slow")
public let animationTimingFunctionBase: CSS.EasingFunction = `var`(
  "--animation-timing-function-base")
public let animationTimingFunctionBouncing: CSS.EasingFunction = `var`(
  "--animation-timing-function-bouncing")
public let animationIterationCountBase: CSS.Number = `var`("--animation-iteration-count-base")

// MARK: - Applied: Cursors & Blend Modes
public let cursorBase: CSS.Cursor = `var`("--cursor-base")
public let cursorBaseHover: CSS.Cursor = `var`("--cursor-base-hover")
public let cursorGrab: CSS.Cursor = `var`("--cursor-grab")
public let cursorGrabbing: CSS.Cursor = `var`("--cursor-grabbing")
public let cursorHelp: CSS.Cursor = `var`("--cursor-help")
public let cursorMove: CSS.Cursor = `var`("--cursor-move")
public let cursorNotAllowed: CSS.Cursor = `var`("--cursor-not-allowed")
public let cursorResizeNesw: CSS.Cursor = `var`("--cursor-resize-nesw")
public let cursorResizeNwse: CSS.Cursor = `var`("--cursor-resize-nwse")
public let cursorText: CSS.Cursor = `var`("--cursor-text")
public let cursorZoomIn: CSS.Cursor = `var`("--cursor-zoom-in")
public let cursorZoomOut: CSS.Cursor = `var`("--cursor-zoom-out")
public let mixBlendModeBase: CSS.BlendMode = `var`("--mix-blend-mode-base")
public let mixBlendModeBlend: CSS.BlendMode = `var`("--mix-blend-mode-blend")

// MARK: - Applied: Background Colors
public let backgroundColorBase: CSS.Color = `var`("--background-color-base")
public let backgroundColorBaseFixed: CSS.Color = `var`("--background-color-base-fixed")
public let backgroundColorBaseHover: CSS.Color = `var`("--background-color-base-hover")
public let backgroundColorBaseActive: CSS.Color = `var`("--background-color-base-active")
public let backgroundColorNeutral: CSS.Color = `var`("--background-color-neutral")
public let backgroundColorNeutralSubtle: CSS.Color = `var`("--background-color-neutral-subtle")
public let backgroundColorInteractive: CSS.Color = `var`("--background-color-interactive")
public let backgroundColorInteractiveHover: CSS.Color = `var`("--background-color-interactive-hover")
public let backgroundColorInteractiveActive: CSS.Color = `var`(
  "--background-color-interactive-active")
public let backgroundColorInteractiveSubtle: CSS.Color = `var`(
  "--background-color-interactive-subtle")
public let backgroundColorInteractiveSubtleHover: CSS.Color = `var`(
  "--background-color-interactive-subtle-hover")
public let backgroundColorInteractiveSubtleActive: CSS.Color = `var`(
  "--background-color-interactive-subtle-active")
public let backgroundColorDisabled: CSS.Color = `var`("--background-color-disabled")
public let backgroundColorDisabledSubtle: CSS.Color = `var`("--background-color-disabled-subtle")
public let backgroundColorInverted: CSS.Color = `var`("--background-color-inverted")
public let backgroundColorContentAdded: CSS.Color = `var`("--background-color-content-added")
public let backgroundColorContentRemoved: CSS.Color = `var`("--background-color-content-removed")
public let backgroundColorTransparent: CSS.Color = `var`("--background-color-transparent")
public let backgroundColorBackdropLight: CSS.Color = `var`("--background-color-backdrop-light")
public let backgroundColorBackdropDark: CSS.Color = `var`("--background-color-backdrop-dark")
public let backgroundColorButtonQuietHover: CSS.Color = `var`(
  "--background-color-button-quiet-hover")
public let backgroundColorButtonQuietActive: CSS.Color = `var`(
  "--background-color-button-quiet-active")
public let backgroundColorInputBinaryChecked: CSS.Color = `var`(
  "--background-color-input-binary-checked")
public let backgroundColorTabListItemFramedHover: CSS.Color = `var`(
  "--background-color-tab-list-item-framed-hover")
public let backgroundColorTabListItemFramedActive: CSS.Color = `var`(
  "--background-color-tab-list-item-framed-active")

// MARK: - Applied: HIG Background Colors
// Red
public let backgroundColorRed: CSS.Color = `var`("--background-color-red")
public let backgroundColorRedHover: CSS.Color = `var`("--background-color-red-hover")
public let backgroundColorRedActive: CSS.Color = `var`("--background-color-red-active")
public let backgroundColorRedFocus: CSS.Color = `var`("--background-color-red-focus")
public let backgroundColorRedSubtle: CSS.Color = `var`("--background-color-red-subtle")
public let backgroundColorRedSubtleHover: CSS.Color = `var`("--background-color-red-subtle-hover")
public let backgroundColorRedSubtleActive: CSS.Color = `var`("--background-color-red-subtle-active")
// Orange
public let backgroundColorOrange: CSS.Color = `var`("--background-color-orange")
public let backgroundColorOrangeHover: CSS.Color = `var`("--background-color-orange-hover")
public let backgroundColorOrangeActive: CSS.Color = `var`("--background-color-orange-active")
public let backgroundColorOrangeFocus: CSS.Color = `var`("--background-color-orange-focus")
public let backgroundColorOrangeSubtle: CSS.Color = `var`("--background-color-orange-subtle")
public let backgroundColorOrangeSubtleHover: CSS.Color = `var`(
  "--background-color-orange-subtle-hover")
public let backgroundColorOrangeSubtleActive: CSS.Color = `var`(
  "--background-color-orange-subtle-active")
// Yellow
public let backgroundColorYellow: CSS.Color = `var`("--background-color-yellow")
public let backgroundColorYellowHover: CSS.Color = `var`("--background-color-yellow-hover")
public let backgroundColorYellowActive: CSS.Color = `var`("--background-color-yellow-active")
public let backgroundColorYellowFocus: CSS.Color = `var`("--background-color-yellow-focus")
public let backgroundColorYellowSubtle: CSS.Color = `var`("--background-color-yellow-subtle")
public let backgroundColorYellowSubtleHover: CSS.Color = `var`(
  "--background-color-yellow-subtle-hover")
public let backgroundColorYellowSubtleActive: CSS.Color = `var`(
  "--background-color-yellow-subtle-active")
// Green
public let backgroundColorGreen: CSS.Color = `var`("--background-color-green")
public let backgroundColorGreenHover: CSS.Color = `var`("--background-color-green-hover")
public let backgroundColorGreenActive: CSS.Color = `var`("--background-color-green-active")
public let backgroundColorGreenFocus: CSS.Color = `var`("--background-color-green-focus")
public let backgroundColorGreenSubtle: CSS.Color = `var`("--background-color-green-subtle")
public let backgroundColorGreenSubtleHover: CSS.Color = `var`(
  "--background-color-green-subtle-hover")
public let backgroundColorGreenSubtleActive: CSS.Color = `var`(
  "--background-color-green-subtle-active")
// Mint
public let backgroundColorMint: CSS.Color = `var`("--background-color-mint")
public let backgroundColorMintHover: CSS.Color = `var`("--background-color-mint-hover")
public let backgroundColorMintActive: CSS.Color = `var`("--background-color-mint-active")
public let backgroundColorMintFocus: CSS.Color = `var`("--background-color-mint-focus")
public let backgroundColorMintSubtle: CSS.Color = `var`("--background-color-mint-subtle")
public let backgroundColorMintSubtleHover: CSS.Color = `var`("--background-color-mint-subtle-hover")
public let backgroundColorMintSubtleActive: CSS.Color = `var`(
  "--background-color-mint-subtle-active")
// Teal
public let backgroundColorTeal: CSS.Color = `var`("--background-color-teal")
public let backgroundColorTealHover: CSS.Color = `var`("--background-color-teal-hover")
public let backgroundColorTealActive: CSS.Color = `var`("--background-color-teal-active")
public let backgroundColorTealFocus: CSS.Color = `var`("--background-color-teal-focus")
public let backgroundColorTealSubtle: CSS.Color = `var`("--background-color-teal-subtle")
public let backgroundColorTealSubtleHover: CSS.Color = `var`("--background-color-teal-subtle-hover")
public let backgroundColorTealSubtleActive: CSS.Color = `var`(
  "--background-color-teal-subtle-active")
// Cyan
public let backgroundColorCyan: CSS.Color = `var`("--background-color-cyan")
public let backgroundColorCyanHover: CSS.Color = `var`("--background-color-cyan-hover")
public let backgroundColorCyanActive: CSS.Color = `var`("--background-color-cyan-active")
public let backgroundColorCyanFocus: CSS.Color = `var`("--background-color-cyan-focus")
public let backgroundColorCyanSubtle: CSS.Color = `var`("--background-color-cyan-subtle")
public let backgroundColorCyanSubtleHover: CSS.Color = `var`("--background-color-cyan-subtle-hover")
public let backgroundColorCyanSubtleActive: CSS.Color = `var`(
  "--background-color-cyan-subtle-active")
// Blue
public let backgroundColorBlue: CSS.Color = `var`("--background-color-blue")
public let backgroundColorBlueHover: CSS.Color = `var`("--background-color-blue-hover")
public let backgroundColorBlueActive: CSS.Color = `var`("--background-color-blue-active")
public let backgroundColorBlueFocus: CSS.Color = `var`("--background-color-blue-focus")
public let backgroundColorBlueSubtle: CSS.Color = `var`("--background-color-blue-subtle")
public let backgroundColorBlueSubtleHover: CSS.Color = `var`("--background-color-blue-subtle-hover")
public let backgroundColorBlueSubtleActive: CSS.Color = `var`(
  "--background-color-blue-subtle-active")
// Indigo
public let backgroundColorIndigo: CSS.Color = `var`("--background-color-indigo")
public let backgroundColorIndigoHover: CSS.Color = `var`("--background-color-indigo-hover")
public let backgroundColorIndigoActive: CSS.Color = `var`("--background-color-indigo-active")
public let backgroundColorIndigoFocus: CSS.Color = `var`("--background-color-indigo-focus")
public let backgroundColorIndigoSubtle: CSS.Color = `var`("--background-color-indigo-subtle")
public let backgroundColorIndigoSubtleHover: CSS.Color = `var`(
  "--background-color-indigo-subtle-hover")
public let backgroundColorIndigoSubtleActive: CSS.Color = `var`(
  "--background-color-indigo-subtle-active")
// Purple
public let backgroundColorPurple: CSS.Color = `var`("--background-color-purple")
public let backgroundColorPurpleHover: CSS.Color = `var`("--background-color-purple-hover")
public let backgroundColorPurpleActive: CSS.Color = `var`("--background-color-purple-active")
public let backgroundColorPurpleFocus: CSS.Color = `var`("--background-color-purple-focus")
public let backgroundColorPurpleSubtle: CSS.Color = `var`("--background-color-purple-subtle")
public let backgroundColorPurpleSubtleHover: CSS.Color = `var`(
  "--background-color-purple-subtle-hover")
public let backgroundColorPurpleSubtleActive: CSS.Color = `var`(
  "--background-color-purple-subtle-active")
// Pink
public let backgroundColorPink: CSS.Color = `var`("--background-color-pink")
public let backgroundColorPinkHover: CSS.Color = `var`("--background-color-pink-hover")
public let backgroundColorPinkActive: CSS.Color = `var`("--background-color-pink-active")
public let backgroundColorPinkFocus: CSS.Color = `var`("--background-color-pink-focus")
public let backgroundColorPinkSubtle: CSS.Color = `var`("--background-color-pink-subtle")
public let backgroundColorPinkSubtleHover: CSS.Color = `var`("--background-color-pink-subtle-hover")
public let backgroundColorPinkSubtleActive: CSS.Color = `var`(
  "--background-color-pink-subtle-active")
// Brown
public let backgroundColorBrown: CSS.Color = `var`("--background-color-brown")
public let backgroundColorBrownHover: CSS.Color = `var`("--background-color-brown-hover")
public let backgroundColorBrownActive: CSS.Color = `var`("--background-color-brown-active")
public let backgroundColorBrownFocus: CSS.Color = `var`("--background-color-brown-focus")
public let backgroundColorBrownSubtle: CSS.Color = `var`("--background-color-brown-subtle")
public let backgroundColorBrownSubtleHover: CSS.Color = `var`(
  "--background-color-brown-subtle-hover")
public let backgroundColorBrownSubtleActive: CSS.Color = `var`(
  "--background-color-brown-subtle-active")
// Gray
public let backgroundColorGray: CSS.Color = `var`("--background-color-gray")
public let backgroundColorGrayHover: CSS.Color = `var`("--background-color-gray-hover")
public let backgroundColorGrayActive: CSS.Color = `var`("--background-color-gray-active")
public let backgroundColorGrayFocus: CSS.Color = `var`("--background-color-gray-focus")
public let backgroundColorGraySubtle: CSS.Color = `var`("--background-color-gray-subtle")
public let backgroundColorGraySubtleHover: CSS.Color = `var`("--background-color-gray-subtle-hover")
public let backgroundColorGraySubtleActive: CSS.Color = `var`(
  "--background-color-gray-subtle-active")

// MARK: - Applied: Icon Opacity
public let opacityIconBase: CSS.Number = `var`("--opacity-icon-base")
public let opacityIconBaseHover: CSS.Number = `var`("--opacity-icon-base-hover")
public let opacityIconBaseSelected: CSS.Number = `var`("--opacity-icon-base-selected")
public let opacityIconBaseDisabled: CSS.Number = `var`("--opacity-icon-base-disabled")
public let opacityIconPlaceholder: CSS.Number = `var`("--opacity-icon-placeholder")
public let opacityIconSubtle: CSS.Number = `var`("--opacity-icon-subtle")

// MARK: - Applied: Min Sizes
public let minSizeInteractivePointer: CSS.Length = `var`("--min-size-interactive-pointer")
public let minSizeInteractiveTouch: CSS.Length = `var`("--min-size-interactive-touch")
public let minSizeSearchFigure: CSS.Length = `var`("--min-size-search-figure")
public let minSizeIconXSmall: CSS.Length = `var`("--min-size-icon-x-small")
public let minSizeIconSmall: CSS.Length = `var`("--min-size-icon-small")
public let minSizeIconMedium: CSS.Length = `var`("--min-size-icon-medium")
public let minSizeInputBinary: CSS.Length = `var`("--min-size-input-binary")
public let minSizeInputChipClearButton: CSS.Length = `var`("--min-size-input-chip-clear-button")
public let minSizeToggleSwitchGrip: CSS.Length = `var`("--min-size-toggle-switch-grip")
public let minWidthMedium: CSS.Length = `var`("--min-width-medium")
// Breakpoints use raw px() values, not CSSContent variables — media queries don't support var()
public let minWidthBreakpointMobile: CSS.Length = px(480)
public let minWidthBreakpointTablet: CSS.Length = px(769)
public let minWidthBreakpointDesktop: CSS.Length = px(1025)
public let minWidthBreakpointDesktopWide: CSS.Length = px(1280)
public let minWidthToggleSwitch: CSS.Length = `var`("--min-width-toggle-switch")

public let spacing0: CSS.Length = `var`("--spacing-0")
public let spacing1: CSS.Length = `var`("--spacing-1")
public let spacing2: CSS.Length = `var`("--spacing-2")
public let spacing4: CSS.Length = `var`("--spacing-4")
public let spacing5: CSS.Length = `var`("--spacing-5")
public let spacing6: CSS.Length = `var`("--spacing-6")
public let spacing8: CSS.Length = `var`("--spacing-8")
public let spacing10: CSS.Length = `var`("--spacing-10")
public let spacing12: CSS.Length = `var`("--spacing-12")
public let spacing16: CSS.Length = `var`("--spacing-16")
public let spacing20: CSS.Length = `var`("--spacing-20")
public let spacing24: CSS.Length = `var`("--spacing-24")
public let spacing32: CSS.Length = `var`("--spacing-32")
public let spacing40: CSS.Length = `var`("--spacing-40")
public let spacing48: CSS.Length = `var`("--spacing-48")
public let spacing64: CSS.Length = `var`("--spacing-64")
public let spacingHalf: CSS.Percentage = `var`("--spacing-half")
public let spacingFull: CSS.Percentage = `var`("--spacing-full")

// MARK: - Applied: Border Width & Color
public let borderWidthBase: CSS.Length = `var`("--border-width-base")
public let borderWidthThick: CSS.Length = `var`("--border-width-thick")
public let borderWidthInputRadioChecked: CSS.Length = `var`("--border-width-input-radio-checked")
public let borderColorBase: CSS.Color = `var`("--border-color-base")
public let borderColorBaseHover: CSS.Color = `var`("--border-color-base-hover")
public let borderColorBaseActive: CSS.Color = `var`("--border-color-base-active")
public let borderColorEmphasized: CSS.Color = `var`("--border-color-emphasized")
public let borderColorSubtle: CSS.Color = `var`("--border-color-subtle")
public let borderColorMuted: CSS.Color = `var`("--border-color-muted")
public let borderColorInteractive: CSS.Color = `var`("--border-color-interactive")
public let borderColorInteractiveHover: CSS.Color = `var`("--border-color-interactive-hover")
public let borderColorInteractiveActive: CSS.Color = `var`("--border-color-interactive-active")
public let borderColorDisabled: CSS.Color = `var`("--border-color-disabled")
public let borderColorInverted: CSS.Color = `var`("--border-color-inverted")
public let borderColorInvertedFixed: CSS.Color = `var`("--border-color-inverted-fixed")
public let borderColorContentAdded: CSS.Color = `var`("--border-color-content-added")
public let borderColorContentRemoved: CSS.Color = `var`("--border-color-content-removed")
public let borderColorTransparent: CSS.Color = `var`("--border-color-transparent")
public let borderColorDivider: CSS.Color = `var`("--border-color-divider")

// MARK: - Applied: HIG Border Colors
// Hue order: red, orange, yellow, green, mint, teal, cyan, blue, indigo, purple, pink, brown, gray
public let borderColorRed: CSS.Color = `var`("--border-color-red")
public let borderColorRedHover: CSS.Color = `var`("--border-color-red-hover")
public let borderColorRedActive: CSS.Color = `var`("--border-color-red-active")
public let borderColorRedFocus: CSS.Color = `var`("--border-color-red-focus")
public let borderColorOrange: CSS.Color = `var`("--border-color-orange")
public let borderColorOrangeHover: CSS.Color = `var`("--border-color-orange-hover")
public let borderColorOrangeActive: CSS.Color = `var`("--border-color-orange-active")
public let borderColorOrangeFocus: CSS.Color = `var`("--border-color-orange-focus")
public let borderColorYellow: CSS.Color = `var`("--border-color-yellow")
public let borderColorYellowHover: CSS.Color = `var`("--border-color-yellow-hover")
public let borderColorYellowActive: CSS.Color = `var`("--border-color-yellow-active")
public let borderColorYellowFocus: CSS.Color = `var`("--border-color-yellow-focus")
public let borderColorGreen: CSS.Color = `var`("--border-color-green")
public let borderColorGreenHover: CSS.Color = `var`("--border-color-green-hover")
public let borderColorGreenActive: CSS.Color = `var`("--border-color-green-active")
public let borderColorGreenFocus: CSS.Color = `var`("--border-color-green-focus")
public let borderColorMint: CSS.Color = `var`("--border-color-mint")
public let borderColorMintHover: CSS.Color = `var`("--border-color-mint-hover")
public let borderColorMintActive: CSS.Color = `var`("--border-color-mint-active")
public let borderColorMintFocus: CSS.Color = `var`("--border-color-mint-focus")
public let borderColorTeal: CSS.Color = `var`("--border-color-teal")
public let borderColorTealHover: CSS.Color = `var`("--border-color-teal-hover")
public let borderColorTealActive: CSS.Color = `var`("--border-color-teal-active")
public let borderColorTealFocus: CSS.Color = `var`("--border-color-teal-focus")
public let borderColorCyan: CSS.Color = `var`("--border-color-cyan")
public let borderColorCyanHover: CSS.Color = `var`("--border-color-cyan-hover")
public let borderColorCyanActive: CSS.Color = `var`("--border-color-cyan-active")
public let borderColorCyanFocus: CSS.Color = `var`("--border-color-cyan-focus")
public let borderColorBlue: CSS.Color = `var`("--border-color-blue")
public let borderColorBlueHover: CSS.Color = `var`("--border-color-blue-hover")
public let borderColorBlueActive: CSS.Color = `var`("--border-color-blue-active")
public let borderColorBlueFocus: CSS.Color = `var`("--border-color-blue-focus")
public let borderColorIndigo: CSS.Color = `var`("--border-color-indigo")
public let borderColorIndigoHover: CSS.Color = `var`("--border-color-indigo-hover")
public let borderColorIndigoActive: CSS.Color = `var`("--border-color-indigo-active")
public let borderColorIndigoFocus: CSS.Color = `var`("--border-color-indigo-focus")
public let borderColorPurple: CSS.Color = `var`("--border-color-purple")
public let borderColorPurpleHover: CSS.Color = `var`("--border-color-purple-hover")
public let borderColorPurpleActive: CSS.Color = `var`("--border-color-purple-active")
public let borderColorPurpleFocus: CSS.Color = `var`("--border-color-purple-focus")
public let borderColorPink: CSS.Color = `var`("--border-color-pink")
public let borderColorPinkHover: CSS.Color = `var`("--border-color-pink-hover")
public let borderColorPinkActive: CSS.Color = `var`("--border-color-pink-active")
public let borderColorPinkFocus: CSS.Color = `var`("--border-color-pink-focus")
public let borderColorBrown: CSS.Color = `var`("--border-color-brown")
public let borderColorBrownHover: CSS.Color = `var`("--border-color-brown-hover")
public let borderColorBrownActive: CSS.Color = `var`("--border-color-brown-active")
public let borderColorBrownFocus: CSS.Color = `var`("--border-color-brown-focus")
public let borderColorGray: CSS.Color = `var`("--border-color-gray")
public let borderColorGrayHover: CSS.Color = `var`("--border-color-gray-hover")
public let borderColorGrayActive: CSS.Color = `var`("--border-color-gray-active")
public let borderColorGrayFocus: CSS.Color = `var`("--border-color-gray-focus")
// MARK: - Applied: Border Radius
public let borderRadiusMinimal: CSS.Length = `var`("--border-radius-minimal")
public let borderRadiusBase: CSS.Length = `var`("--border-radius-base")
public let borderRadiusSharp: CSS.Length = `var`("--border-radius-sharp")
public let borderRadiusPill: CSS.Length = `var`("--border-radius-pill")
public let borderRadiusCircle: CSS.Percentage = `var`("--border-radius-circle")
// MARK: - Applied: HIG Box Shadows & Outline
// Hue order: red, orange, yellow, green, mint, teal, cyan, blue, indigo, purple, pink, brown, gray
public let boxShadowColorRedActive: CSS.Color = `var`("--box-shadow-color-red-active")
public let boxShadowColorRedFocus: CSS.Color = `var`("--box-shadow-color-red-focus")
public let boxShadowColorOrangeActive: CSS.Color = `var`("--box-shadow-color-orange-active")
public let boxShadowColorOrangeFocus: CSS.Color = `var`("--box-shadow-color-orange-focus")
public let boxShadowColorYellowActive: CSS.Color = `var`("--box-shadow-color-yellow-active")
public let boxShadowColorYellowFocus: CSS.Color = `var`("--box-shadow-color-yellow-focus")
public let boxShadowColorGreenActive: CSS.Color = `var`("--box-shadow-color-green-active")
public let boxShadowColorGreenFocus: CSS.Color = `var`("--box-shadow-color-green-focus")
public let boxShadowColorMintActive: CSS.Color = `var`("--box-shadow-color-mint-active")
public let boxShadowColorMintFocus: CSS.Color = `var`("--box-shadow-color-mint-focus")
public let boxShadowColorTealActive: CSS.Color = `var`("--box-shadow-color-teal-active")
public let boxShadowColorTealFocus: CSS.Color = `var`("--box-shadow-color-teal-focus")
public let boxShadowColorCyanActive: CSS.Color = `var`("--box-shadow-color-cyan-active")
public let boxShadowColorCyanFocus: CSS.Color = `var`("--box-shadow-color-cyan-focus")
public let boxShadowColorBlueActive: CSS.Color = `var`("--box-shadow-color-blue-active")
public let boxShadowColorBlueFocus: CSS.Color = `var`("--box-shadow-color-blue-focus")
public let boxShadowColorIndigoActive: CSS.Color = `var`("--box-shadow-color-indigo-active")
public let boxShadowColorIndigoFocus: CSS.Color = `var`("--box-shadow-color-indigo-focus")
public let boxShadowColorIndigoSelected: CSS.Color = `var`("--box-shadow-color-indigo-selected")
public let boxShadowColorIndigoSelectedHover: CSS.Color = `var`(
  "--box-shadow-color-indigo-selected-hover")
public let boxShadowColorIndigoSelectedActive: CSS.Color = `var`(
  "--box-shadow-color-indigo-selected-active")
public let boxShadowColorPurpleActive: CSS.Color = `var`("--box-shadow-color-purple-active")
public let boxShadowColorPurpleFocus: CSS.Color = `var`("--box-shadow-color-purple-focus")
public let boxShadowColorPinkActive: CSS.Color = `var`("--box-shadow-color-pink-active")
public let boxShadowColorPinkFocus: CSS.Color = `var`("--box-shadow-color-pink-focus")
public let boxShadowColorBrownActive: CSS.Color = `var`("--box-shadow-color-brown-active")
public let boxShadowColorBrownFocus: CSS.Color = `var`("--box-shadow-color-brown-focus")
public let boxShadowColorGrayActive: CSS.Color = `var`("--box-shadow-color-gray-active")
public let boxShadowColorGrayFocus: CSS.Color = `var`("--box-shadow-color-gray-focus")
public let outlineColorRedFocus: CSS.Color = `var`("--outline-color-red-focus")
public let outlineColorOrangeFocus: CSS.Color = `var`("--outline-color-orange-focus")
public let outlineColorYellowFocus: CSS.Color = `var`("--outline-color-yellow-focus")
public let outlineColorGreenFocus: CSS.Color = `var`("--outline-color-green-focus")
public let outlineColorMintFocus: CSS.Color = `var`("--outline-color-mint-focus")
public let outlineColorTealFocus: CSS.Color = `var`("--outline-color-teal-focus")
public let outlineColorCyanFocus: CSS.Color = `var`("--outline-color-cyan-focus")
public let outlineColorBlueFocus: CSS.Color = `var`("--outline-color-blue-focus")
public let outlineColorIndigoFocus: CSS.Color = `var`("--outline-color-indigo-focus")
public let outlineColorPurpleFocus: CSS.Color = `var`("--outline-color-purple-focus")
public let outlineColorPinkFocus: CSS.Color = `var`("--outline-color-pink-focus")
public let outlineColorBrownFocus: CSS.Color = `var`("--outline-color-brown-focus")
public let outlineColorGrayFocus: CSS.Color = `var`("--outline-color-gray-focus")
// MARK: - Applied: Heights
public let minHeightTextArea: CSS.Length = `var`("--min-height-text-area")
public let minHeightTableHeader: CSS.Length = `var`("--min-height-table-header")
public let minHeightTableFooter: CSS.Length = `var`("--min-height-table-footer")
public let minHeightToggleSwitch: CSS.Length = `var`("--min-height-toggle-switch")
public let maxHeightChip: CSS.Length = `var`("--max-height-chip")

// MARK: - Applied: Links
public let colorLink: CSS.Color = `var`("--color-link")
public let colorLinkHover: CSS.Color = `var`("--color-link-hover")
public let colorLinkActive: CSS.Color = `var`("--color-link-active")
public let colorLinkFocus: CSS.Color = `var`("--color-link-focus")
public let colorLinkVisited: CSS.Color = `var`("--color-link-visited")
public let colorLinkVisitedHover: CSS.Color = `var`("--color-link-visited-hover")
public let colorLinkVisitedActive: CSS.Color = `var`("--color-link-visited-active")
public let colorLinkRed: CSS.Color = `var`("--color-link-red")
public let colorLinkRedHover: CSS.Color = `var`("--color-link-red-hover")
public let colorLinkRedActive: CSS.Color = `var`("--color-link-red-active")
public let colorLinkRedFocus: CSS.Color = `var`("--color-link-red-focus")
public let colorLinkRedVisited: CSS.Color = `var`("--color-link-red-visited")
public let colorLinkRedVisitedHover: CSS.Color = `var`("--color-link-red-visited-hover")
public let colorLinkRedVisitedActive: CSS.Color = `var`("--color-link-red-visited-active")

// MARK: - Applied: Icon Sizes
public let sizeIconXSmall: CSS.Length = `var`("--size-icon-x-small")
public let sizeIconSmall: CSS.Length = `var`("--size-icon-small")
public let sizeIconMedium: CSS.Length = `var`("--size-icon-medium")
public let sizeToggleSwitchGrip: CSS.Length = `var`("--size-toggle-switch-grip")

// MARK: - Applied: Box Shadows
public let boxShadowSmall: CSS.SpreadShadow = `var`("--box-shadow-small")
public let boxShadowSmallTop: CSS.SpreadShadow = `var`("--box-shadow-small-top")
public let boxShadowSmallBottom: CSS.SpreadShadow = `var`("--box-shadow-small-bottom")
public let boxShadowMedium: CSS.SpreadShadow = `var`("--box-shadow-medium")
public let boxShadowLarge: CSS.SpreadShadow = `var`("--box-shadow-large")
public let accentColorBase: CSS.Color = `var`("--accent-color-base")
public let positionOffsetBorderWidthBase: CSS.Length = `var`("--position-offset-border-width-base")

// MARK: - Applied: Button Spacing
public let spacingHorizontalButton: CSS.Length = `var`("--spacing-horizontal-button")
public let spacingHorizontalButtonIconOnly: CSS.Length = `var`("--spacing-horizontal-button-icon-only")
public let spacingHorizontalButtonSmallIconOnly: CSS.Length = `var`(
  "--spacing-horizontal-button-small-icon-only")
public let spacingHorizontalButtonSmall: CSS.Length = `var`("--spacing-horizontal-button-small")
public let spacingHorizontalButtonLarge: CSS.Length = `var`("--spacing-horizontal-button-large")
public let spacingHorizontalInputTextTwoEndIcons: CSS.Length = `var`(
  "--spacing-horizontal-input-text-two-end-icons")
public let spacingStartTypeaheadSearchFigure: CSS.Length = `var`(
  "--spacing-start-typeahead-search-figure")
public let spacingToggleSwitchGripStart: CSS.Length = `var`("--spacing-toggle-switch-grip-start")
public let spacingToggleSwitchGripEnd: CSS.Length = `var`("--spacing-toggle-switch-grip-end")

// MARK: - Applied: Input Borders
public let borderColorInputHover: CSS.Color = `var`("--border-color-input-hover")
public let borderColorInputBinary: CSS.Color = `var`("--border-color-input-binary")
public let borderColorInputBinaryHover: CSS.Color = `var`("--border-color-input-binary-hover")
public let borderColorInputBinaryActive: CSS.Color = `var`("--border-color-input-binary-active")
public let borderColorInputBinaryFocus: CSS.Color = `var`("--border-color-input-binary-focus")
public let borderColorInputBinaryChecked: CSS.Color = `var`("--border-color-input-binary-checked")
public let borderColorInputBinaryCheckedHover: CSS.Color = `var`("--border-color-input-binary-checked-hover")
public let borderColorInputBinaryCheckedActive: CSS.Color = `var`("--border-color-input-binary-checked-active")
public let borderBase: CSS.Border = `var`("--border-base")
public let borderSubtle: CSS.Border = `var`("--border-subtle")
public let borderTransparent: CSS.Border = `var`("--border-transparent")
public let borderRed: CSS.Border = `var`("--border-red")
public let borderOrange: CSS.Border = `var`("--border-orange")
public let borderYellow: CSS.Border = `var`("--border-yellow")
public let borderGreen: CSS.Border = `var`("--border-green")
public let borderMint: CSS.Border = `var`("--border-mint")
public let borderTeal: CSS.Border = `var`("--border-teal")
public let borderCyan: CSS.Border = `var`("--border-cyan")
public let borderBlue: CSS.Border = `var`("--border-blue")
public let borderIndigo: CSS.Border = `var`("--border-indigo")
public let borderPurple: CSS.Border = `var`("--border-purple")
public let borderPink: CSS.Border = `var`("--border-pink")
public let borderBrown: CSS.Border = `var`("--border-brown")
public let borderGray: CSS.Border = `var`("--border-gray")
public let outlineBaseFocus: CSS.Border = `var`("--outline-base-focus")

// MARK: - Applied: Toggle Switch
public let widthToggleSwitch: CSS.Length = `var`("--width-toggle-switch")
public let heightToggleSwitch: CSS.Length = `var`("--height-toggle-switch")
public let spacingStartTypeaheadSearchIcon: CSS.Length = `var`("--spacing-start-typeahead-search-icon")
public let spacingTypeaheadSearchFocusAddition: CSS.Length = `var`(
  "--spacing-typeahead-search-focus-addition")

// MARK: - Source: Syntax Highlighting (Apple HIG)
public let syntaxAddition: CSS.Color = `var`("--color-syntax-addition")
public let syntaxAttributes: CSS.Color = `var`("--color-syntax-attributes")
public let syntaxCharacters: CSS.Color = `var`("--color-syntax-characters")
public let syntaxComments: CSS.Color = `var`("--color-syntax-comments")
public let syntaxDeletion: CSS.Color = `var`("--color-syntax-deletion")
public let syntaxDocumentationMarkup: CSS.Color = `var`("--color-syntax-documentation-markup")
public let syntaxDocumentationMarkupKeywords: CSS.Color = `var`(
  "--color-syntax-documentation-markup-keywords")
public let syntaxHeading: CSS.Color = `var`("--color-syntax-heading")
public let syntaxHighlighted: CSS.Color = `var`("--color-syntax-highlighted")
public let syntaxKeywords: CSS.Color = `var`("--color-syntax-keywords")
public let syntaxMarks: CSS.Color = `var`("--color-syntax-marks")
public let syntaxNumbers: CSS.Color = `var`("--color-syntax-numbers")
public let syntaxOtherClassNames: CSS.Color = `var`("--color-syntax-other-class-names")
public let syntaxOtherConstants: CSS.Color = `var`("--color-syntax-other-constants")
public let syntaxOtherDeclarations: CSS.Color = `var`("--color-syntax-other-declarations")
public let syntaxOtherFunctionAndMethodNames: CSS.Color = `var`(
  "--color-syntax-other-function-and-method-names")
public let syntaxOtherInstanceVariablesAndGlobals: CSS.Color = `var`(
  "--color-syntax-other-instance-variables-and-globals")
public let syntaxOtherPreprocessorMacros: CSS.Color = `var`(
  "--color-syntax-other-preprocessor-macros")
public let syntaxOtherTypeNames: CSS.Color = `var`("--color-syntax-other-type-names")
public let syntaxParamInternalName: CSS.Color = `var`("--color-syntax-param-internal-name")
public let syntaxPlainText: CSS.Color = `var`("--color-syntax-plain-text")
public let syntaxPreprocessorStatements: CSS.Color = `var`("--color-syntax-preprocessor-statements")
public let syntaxProjectClassNames: CSS.Color = `var`("--color-syntax-project-class-names")
public let syntaxProjectConstants: CSS.Color = `var`("--color-syntax-project-constants")
public let syntaxProjectFunctionAndMethodNames: CSS.Color = `var`(
  "--color-syntax-project-function-and-method-names")
public let syntaxProjectInstanceVariablesAndGlobals: CSS.Color = `var`(
  "--color-syntax-project-instance-variables-and-globals")
public let syntaxProjectPreprocessorMacros: CSS.Color = `var`(
  "--color-syntax-project-preprocessor-macros")
public let syntaxProjectTypeNames: CSS.Color = `var`("--color-syntax-project-type-names")
public let syntaxStrings: CSS.Color = `var`("--color-syntax-strings")
public let syntaxTypeDeclarations: CSS.Color = `var`("--color-syntax-type-declarations")
public let syntaxUrls: CSS.Color = `var`("--color-syntax-urls")
